#!/bin/sh
# Re-generate external executable cmd macros:
# different platforms may have different full/realpaths
: ${distdir="/usr/local/cbsd"}
# MAIN
if [ -z "${workdir}" ]; then
	[ -z "${cbsd_workdir}" ] && . /etc/rc.conf
	[ -z "${cbsd_workdir}" ] && exit 0
	workdir="${cbsd_workdir}"
fi

[ ! -f "${distdir}/cbsd.conf" ] && exit 0

. ${distdir}/cbsd.conf

CMD_FILE=${workdir}/cmd.subr
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

MAIN_CMD="\
cc \
install \
sysrc \
cat \
ls \
grep \
egrep \
date \
tmux \
pw \
tr \
cut \
awk \
sed \
ifconfig \
truncate \
tee \
realpath \
sysctl \
xargs \
"

truncate -s0 ${CMD_FILE}

cat > ${CMD_FILE} <<EOF
if [ ! "\$_CBSD_CMD_SUBR" ]; then
_CBSD_CMD_SUBR=1
###
EOF

for i in ${MAIN_CMD}; do
	mycmd=
	mycmd=$( which ${i} )
	if [ ! -x "${mycmd}" ]; then
		echo "cmdboot: no such executable: ${i}"
		exit 1
	fi
	MY_CMD=$( echo ${i} | tr '[:lower:]' '[:upper:]' )
	MY_CMD="${MY_CMD}_CMD"

	echo "${MY_CMD}=\"${mycmd}\"" >> ${CMD_FILE}

done

cat >> ${CMD_FILE} <<EOF
###
fi
EOF
