#!/bin/sh
#
# create CBSD directory hierarchy
#

[ -z "${1}" ] && exit 1

cbsd_workdir="${1}"

chown cbsd:cbsd "${cbsd_workdir}"
chmod 0755 "${cbsd_workdir}"

[ ! -d  "${cbsd_workdir}"/.rssh ] && mkdir -p "${cbsd_workdir}"/.rssh
chmod 0700 "${cbsd_workdir}"/.rssh

[ ! -d "${cbsd_workdir}"/.ssh ] && mkdir -p "${cbsd_workdir}"/.ssh
chmod 0700 "${cbsd_workdir}"/.ssh

[ ! -d "${cbsd_workdir}"/.ssh/sockets ] && mkdir -p "${cbsd_workdir}"/.ssh/sockets
chmod 0700 "${cbsd_workdir}"/.ssh/sockets

[ ! -d "${cbsd_workdir}"/basejail ] && mkdir -p "${cbsd_workdir}"/basejail
chmod 0755 "${cbsd_workdir}"/basejail
chown 0:0 "${cbsd_workdir}"/basejail

for i in etc etc/defaults export ftmp import jails jails-data jails-fstab jails-rcconf jails-system share share/dialog share/helpers share/FreeBSD-jail-puppet-skel share/FreeBSD-jail-skel share/FreeBSD-jail-vnet-skel share/emulators src tmp var var/cron var/tabs var/db var/log var/mail var/run var/spool; do
	[ ! -d "${cbsd_workdir}"/${i} ] && mkdir "${cbsd_workdir}"/${i}
done

chown cbsd:cbsd "${cbsd_workdir}"/etc "${cbsd_workdir}"/.ssh "${cbsd_workdir}"/.rssh
chmod 0555 "${cbsd_workdir}"/jails
chown cbsd:cbsd "${cbsd_workdir}"/jails-data
chmod 0555 "${cbsd_workdir}"/jails-data
chown cbsd:cbsd "${cbsd_workdir}"/var
chmod 0770 "${cbsd_workdir}"/var
chown cbsd:cbsd "${cbsd_workdir}"/var/db
chmod 0770 "${cbsd_workdir}"/var/db
