#!/bin/sh
#
# mount and recopy data for directory
#
# $FreeBSD: $
#

# PROVIDE: tmpdir
# REQUIRE: FILESYSTEMS kld
# BEFORE:  netif
# KEYWORD: nojail

. /etc/rc.subr

name="tmpdir"
start_cmd="tmpdir_start"
stop_cmd=":"

tmpdir_start()
{
	echo "Populate tmpfsdir"

	if [ -f /mnt/etc/tmpfsdir ]; then
		/bin/cat /mnt/etc/tmpfsdir |while read tdir; do
			echo "   * dir: $tdir"
			[ -n "${tdir}" -a -d "${tdir}" ] && mount -t tmpfs tmpfs ${tdir} && cp -a /mnt${tdir} $( /usr/bin/dirname ${tdir} )
		done
	fi
}

load_rc_config $name
run_rc_command "$1"
