#!/bin/sh
#v9.2.2
globalconf="${workdir}/cbsd.conf";
MYARG="jname"
MYOPTARG=""
MYDESC="Chown for rc.conf/fstab/system directory to cbsd user"

set -e
. ${globalconf}
set +e

. ${subr}
. ${strings}
init $*

. ${jrcconf}

cbsd jstatus jname=${jname} > /dev/null 2>&1
RES=$?
[ ${RES} -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"

case $RES in
	0)
		err 1 "No such jail" 
	;;
	1)
		JAILRCCONF="${jailrcconfdir}/rc.conf_${jname}"
		JAILFSTAB=${mount_fstab}
	;;
	2)
		JAILRCCONF="${jailrcconfdir}/rc.conf_${jname}.slave"
		JAILFSTAB="${mount_fstab}.slave"
	;;
	*)
		err 1 "Unknown result from jstatus" 
	;;
esac

[ -f "${JAILFSTAB}" ] && chown ${cbsduser} ${JAILFSTAB}
[ -d "${jailsysdir}/${jname}" ] && find "${jailsysdir}/${jname}" -exec chown ${cbsduser} {} \;
