#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
MYARG="owner dest"
MYOPTARG=""
MYDESC="Chown for destrination directory in workdir"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

DST="${workdir}/${dest}"
[ -e ${DST} ] || err 1 "No such ${DST}"
find ${DST} -exec chown ${owner} {} \;

