#!/bin/sh
#v9.2.2
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="ver arch basename stable destdir"
MYDESC="Installbase from obj"
ADDHELP="ver=head for current.\n\
stable=1 for RELENG_X\n\
destdir= for alternative install path in root dir\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${color}
init $*

# By default ver=current version
. ${buildconf}

SRC="${srcdir}/src_${ver}"

if [ -z "${basename}" ]; then
    DST="${basejaildir}/${basejailpref}_${arch}_${ver}"
else
    DST="${basejaildir}/${basejailpref}_${basename}_${arch}_${ver}"
fi

if [ -z "${basename}" ]; then
    export __MAKE_CONF=${etcdir}/make.conf
else
    export __MAKE_CONF=${etcdir}/make-$basename.conf
fi

if [ -z "${basename}" ]; then
    export MAKEOBJDIRPREFIX=${srcdir}/obj_${arch}_${ver}
else
    export MAKEOBJDIRPREFIX=${srcdir}/obj_${basename}_${arch}_${ver}
fi

if [ -z "${basename}" ]; then
    export SRCCONF=${etcdir}/src.conf
else
    export SRCCONF=${etcdir}/src-${basename}.conf
fi

[ -n "${destdir}" ] && DST="${destdir}"
[ -d "${SRC}" ] || err 1 "${MAGENTA}No such source: ${GREEN}${SRC}${NORMAL}"
[ -d "${DST}" ] || /bin/mkdir -p ${DST}

if [ -z "${basename}" ]; then
    LOCKFILE=${SRC}.lock
else
    LOCKFILE=${SRC}-${basename}.lock
fi

case "${arch}" in
"i386")
    export MACHINE="i386"
    export UNAME_p="i386"
    export UNAME_m="i386"
    export TARGET="i386"
    export TARGET_ARCH="i386"
    export MACHINE_ARCH="i386"
    export BUILD_ARCH="i386"
    ;;
"amd64")   
    export MACHINE="amd64"
    export UNAME_p="amd64"
    export UNAME_m="amd64"
    export TARGET="amd64"
    export TARGET_ARCH="amd64"
    export MACHINE_ARCH="amd64"
    export BUILD_ARCH="amd64"
    ;;
esac

makelock $LOCKFILE
/usr/bin/make -C ${SRC}/src installworld distribution DESTDIR=${DST} TARGET=${arch}
[ $? -ne 0 ] && err 1 "${MAGENTA}Installworld error${NORMAL}"
[ -z "${destdir}" ] && cbsd preparebase dst=$DST
