#!/bin/sh
#v10.0.4
globalconf="${workdir}/cbsd.conf";
MYARG="jname"
MYOPTARG="cmd"
MYDESC="Execution for command inside jail"
CBSDMODULE="jail"

# by jid not supported yet
[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${strings}
init $*

[ -z "${jname}" ] && err 1 "Give me jname"

shift  # todo: jname and cmd may have reverse order

[ -z "${cmd}" ] && cmd=${@}
[ -n "${cmd}" ] || err 1 "Empty command"

. ${jrcconf}
[ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
[ "${emulator}" = "bhyve" ] && err 1 "${MAGENTA}Not for bhyve mode${NORMAL}"

[ ${jid} -ne 0 ] || err 1 "Not running"

#rctl/limits area
. ${workdir}/rctl.subr
[ -z "${nice}" ] && nice="0"
#

if [ ${exec_fib} -eq 0 ]; then
    SETFIB=""
else
    SETFIB="setfib ${exec_fib}"
fi

if [ "${cpuset}" = "0" ]; then
    CPUSET=""
else
    CPUSET="cpuset -c -l ${cpuset}"
fi

/usr/bin/nice -n ${nice} ${SETFIB} ${CPUSET} /usr/sbin/jexec ${jid} ${cmd}
