#!/bin/sh
#v9.2.2
globalconf="${workdir}/cbsd.conf";
MYARG="jname"
MYOPTARG="compress imgname"
MYDESC="Export jail into image"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${color}
. ${strings}
init $*

[ -z "${imgname}" ] && imgname="${jname}.img"
. ${jrcconf}
[ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"

DEST="${exportdir}/${imgname}"
JAILRCCONF="${jailrcconfdir}/rc.conf_${jname}"

trap "rm -f ${JAILRCCONF}" HUP INT ABRT BUS TERM EXIT
cbsd jmkrcconf jname=${jname} > $JAILRCCONF

# check for already existance and offline
[ ! -d "${data}" ] && err 1 "${MAGENTA}No jail data for ${jname}: ${GREEN}${data}${NORMAL}"

SPACER="___NCSTART_HEADER=1_ \
___NCSTART_RCCONF=1 \
___NCSTART_FSTAB=1 \
___NCSTART_PKGINFO=1 \
___NCSTART_DESCR=1 \
___NCSTART_INFO=1 \
___NCSTART_LOCALFSTAB=1
___NCSTART_SYSDATA=1 \
___NCSTART_DATA=1"

for _part in ${SPACER}; do
    case ${_part} in
	___NCSTART_HEADER*)
	    cbsd imgpart mode=pack jname=${jname} part=header out=${DEST}
	;;
	___NCSTART_RCCONF*)
	    #currenlty we import/export operation for rc.conf via ascii format
	    #cause diffrence node can have version of cbsd with incompattible jail schema
	    #so create rc.conf for pack operation
	    cbsd imgpart mode=pack jname=${jname} part=rcconf out=${DEST}
	;;
	___NCSTART_PKGINFO*)
	    cbsd imgpart mode=pack jname=${jname} part=pkginfo out=${DEST}
	;;
	___NCSTART_DESCR*)
	    cbsd imgpart mode=pack jname=${jname} part=descr out=${DEST}
	;;
	___NCSTART_INFO*)
	    cbsd imgpart mode=pack jname=${jname} part=info out=${DEST}
	;;
	___NCSTART_FSTAB*)
	    TMPFSTAB="${ftmpdir}/fstab.$$"
	    [ ! -f "${mount_fstab}" ] && touch ${mount_fstab}
	    cp ${mount_fstab} ${TMPFSTAB}
	    cbsd replacewdir file0="${mount_fstab}" old=${workdir} new="CBSDROOT"
	    cbsd imgpart mode=pack jname=${jname} part=fstab out=${DEST}
	    mv ${TMPFSTAB} ${mount_fstab}
	;;
	___NCSTART_LOCALFSTAB*)
	    cbsd imgpart mode=pack jname=${jname} part=localfstab out=${DEST}
	;;
	___NCSTART_SYSDATA*)
	    cbsd imgpart mode=pack jname=${jname} part=sysdata out=${DEST}
	;;
	___NCSTART_DATA*)
	    #test for zfs mounted & mount if not
	    case $zfsfeat in
		1) . $zfstool
		    zfsmnt ${data}
		    if [ $? -eq 2 ]; then
			WASNOMOUNT=1
		    else
			WASNOMOUNT=0
		    fi
		    [ $WASNOMOUNT -eq 1 ] && zfs mount "${ZPOOL}"
		    ;;
	    esac
	    cbsd imgpart mode=pack jname=${jname} part=data out=${DEST}
	    [ "$WASNOMOUNT" = "1" ] && zfs unmount "${ZPOOL}"
	;;
    esac
done
