#!/bin/sh
#v9.2.2
globalconf="${workdir}/cbsd.conf";
MYARG="jname"
MYOPTARG="mode"
MYDESC="Generate jail secrets phrase sequence for rsync"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

[ -z "${jname}" ] && err 1 "Give me jname"

PW=`head -c 30 /dev/random | uuencode -m - | tail -n 2 | head -n1`

SECFILE="${workdir}/etc/${jname}.secrets"
[ -f "${SECFILE}" -a "${mode}" != "force" ] && err 1 "Secrets already exist"
echo "${PW}" > ${SECFILE}
echo "${jname}:${PW}" >> ${SECFILE} 
chown root:wheel ${SECFILE} && chmod 0600 ${SECFILE}
