#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
MYARG="jname"
MYOPTARG=""
MYDESC="Populate rsyncd.conf for jail part"

# TODO
# lock is needet
[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

[ -n "${jname}" ] || err 1 "Empty jailname"
[ -f ${etcdir}/rsyncd.conf ] || err 1 "no such rsyncd.conf  file";

## here we can use dir location from conffile for rsync to correct place
## but now is hardcode for prototype test and security reason (empty jaildir can delete root)
##
if [ `grep "^\[${jname}\]" ${etcdir}/rsyncd.conf|wc -l` -eq "0" ]; then
cat >> ${etcdir}/rsyncd.conf << EOF
[${jname}]
list = no
uid = root
gid = wheel
read only = no
path = ${jaildatadir}/${jname}-data.slave
auth users = ${jname}
secrets file = ${etcdir}/${jname}.secrets
EOF
fi
