#!/bin/sh
#v9.2.2
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="ver arch name stable"
MYDESC="Remove base dir"
ADDHELP="ver=9_1 for 9.1 ver=. for current.\n\
stable=1 for RELENG_X\n"

set -e

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${system}
. ${inventory}

init $*

. ${buildconf}

[ -z "${name}" ] && name="GENERIC"
SRC="${srcdir}/src_${ver}"
DST="${basejaildir}/kernel_${name}_${arch}_${ver}"

[ -d "${DST}" ] || err 1 "No such dir: $DST"

LOCKFILE=${SRC}.lock
makelock $LOCKFILE
chflags -R noschg ${DST} && rm -rf ${DST}
