#!/bin/sh
#v9.2.2
globalconf="${workdir}/cbsd.conf";
MYARG="jname mode"
MYOPTARG=""
MYDESC="Generate secrets file for jail"

[ -f "${globalconf}" ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

SECFILE="${etcdir}/$jname.secrets"

[ ! -f "${SECFILE}" ] && exit 0

case $mode in
	"on")
		chown root:wheel ${SECFILE} && chmod 0600 ${SECFILE}
	;;
	"off")
		chown ${cbsduser}:${cbsduser} ${SECFILE} && chmod 0666 ${SECFILE}
	;;
esac
