#!/bin/sh
#v11.0.0
globalconf="${workdir}/cbsd.conf"
CBSDMODULE="bsdconf"
MYARG=""
MYOPTARG="jname"
MYDESC="cbsd service wrapper"
ADDHELP="jname= work in with jail\n"
EXTHELP="modules/bsdconf.d.html"

set -e
. ${globalconf}
set +e

. ${subr}
. ${strings}
. ${system}
init $*

#defines
_MYDIR=$( dirname `realpath $0` )

[ -n "${jname}" ] && shift # skip for jname

cmd="${@}"
[ -z "${cmd}" ] && err 1 "${MAGENTA}Empty command${NORMAL}"

## MAIN ##
if [ -n "${jname}" ]; then
	. ${jrcconf}
	[ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
	[ ${jid} -eq 0 ] && err 1 "Not running"
	exec_cmd="/usr/sbin/jexec ${jid} /usr/sbin/service"
else
	data=""
	exec_cmd="/usr/sbin/service"
fi

[ ! -d "${data}/etc" ] && err 1 "${MAGENTA}No such etc dir: ${GREEN}${data}/etc${NORMAL}"
exec ${exec_cmd} ${cmd}
