.Dd May 20, 2016
.Dt cbsd 8
.Os
.Sh NAME
.Nm cbsd
.Nd FreeBSD jail management tools

.Sh SYNOPSIS
.Nm cbsd
.Op cmd
.Nm cbsd
.Op cmd
.Op param=val
.Nm cbsd
.Op --help

.Sh DESCRIPTION
.Nm
is a jails and VMs management tools. It builds upon and extends standard
tools used for jails and bhyve manipulation.
.Nm
allows jails creation, backups, snapshoting, cloning and changing different
jails options. It also allows to control the order in which the jails should be
started. When using more than one node runnning
.Nm
it allows to clone jails between nodes and even allows to
control the remote node(s) from the "master" of the farm.
.Pp
All commands begin with
.Nm
prefix.
.Pp
The
.Nm
commands can accept arguments which are written in a "param=value" form.
.Nm
commands can have both obligatory arguments and arguments which are optional.
To receive list of all available commands type: cbsd --help
.Pp
Each subcommand has a short usage help available when typing cbsd <subcommand>
--help and an extended manual page accessible by typing "man cbsd-subcommand".

.Sh ENVIRONMENT
By default, CBSD displays text in color (using escape sequences ANSII).
If for some reason the color is unpleasant, or you want to use output from
CBSD utilities in your scripts, you can disable the color through the
environment variable NOCOLOR=1. For example:

.Dl % env NOCOLOR=1 cbsd jls

.Sh FILES

.Sh EXIT STATUS
.Ex -std
The codes are usually described in the --help section for the command/subcommand.

.Sh EXAMPLES
.Tp
Show list of jails:
.Pp
.Nm Cm jls
.Pp
.Tp
Show help for jlogin command:
.Pp
.Nm Cm jlogin --help
.Pp
.Tp
Run DIALOG-based jail configuration tools:
.Pp
.Nm Cm jconstruct-tui

.Sh DIAGNOSTICS
To enable debugging via sh xtrace and trace all operations, use --debug
argument after the CBSD command, for example:

.Dl	% env NOCOLOR=1 cbsd jls --debug

.Sh SEE ALSO
.Xr cpuset 1
.Xr carp 4
.Xr bhyve 8
.Xr hastd 8
.Xr ipfw 8
.Xr jail 8
.Xr pfctl 8
.Xr rctl 8
.Xr zfs

.Sh AUTHORS
.An Oleg Ginzburg Aq Mt olevole@olevole.ru
.Pp
WWW: http://www.bsdstore.ru
