.Dd May 20, 2016
.Dt cbsd 8
.Os
.Sh NAME
.Nm cbsd
.Nd FreeBSD jail management tools
.Sh SYNOPSIS
.Nm cbsd
.Op cmd
.Nm cbsd
.Op cmd
.Op param=val
.Nm cbsd
.Op --help
.Sh DESCRIPTION
.Nm
is a jails and VMs management tools. It builds upon and extends standard
tools used for jails and bhyve manipulation.
.Nm
allows jails creation, backups, snapshoting, cloning and changing different
jails options. It also allows to control the order in which the jails should be
started. When using more than one node runnning
.Nm
it allows to clone jails between nodes and even allows to
control the remote node(s) from the "master" of the farm.
.Pp
All commands begin with
.Nm
prefix.
.Pp
The
.Nm
commands can accept arguments which are written in a "param=value" form.
.Nm
commands can have both obligatory arguments and arguments which are optional.
To receive list of all available commands type: cbsd --help
.Pp
Each subcommand has its help available when typing cbsd <subcommand> --help
.Sh EXAMPLES
.Tp
Show list of jails:
.Pp
.Nm Cm jls
.Pp
.Tp
Show help for jlogin command:
.Pp
.Nm Cm jlogin --help
.Pp
.Tp
Run DIALOG-based jail configuration tools:
.Pp
.Nm Cm jconstruct-tui
.Pp
.Sh EXIT STATUS
cbsd returns a zero exist status if it succeeds. Non zero is returned in case
of a failure or non-standard conclusion, the codes are usually described in
the --help parameter to a command/subcommand.
.Sh SEE ALSO
.Xr jail 8
.Pp
WWW: http://www.bsdstore.ru
