#!/bin/sh
#v10.1.5
globalconf="${workdir}/cbsd.conf"
CBSDMODULE="helpers"
MYARG="devs mnt pool arch ver"
MYOPTARG="swap quiet srcdata url"
MYDESC="mfsBSD ZFS install script"
ADDHELP=""
EXTHELP="modules/pkg.d.html"

# ${_MYDIR}/zfsinstall -u /usr/freebsd-dist ${DSKARG} -p zroot -m ${MPT}

set -e
. ${globalconf}
set +e

. ${subr}
. ${strings}
. ${system}
. ${tools}

init $*

# get default jailskeldir
readconf jail-freebsd-default.conf

#defines
_MYDIR=$( /usr/bin/dirname `/bin/realpath $0` )
noname=0

set -e
	. ${_MYDIR}/zfsinstall.subr
set +e

if [ -n "${srcdata}" ]; then
	[ ! -d "${srcdata}" ] && err 1 "${MAGENTA}No such srcdata: ${GREEN}${srcdata}${NORMAL}"
fi

# for populate_freebsd_world
data="${mnt}"
baserw=1
applytpl=1

[ -z "${quiet}" ] && quiet="0"

SWAP_ARG=""

[ -n "${swap}" -a "${swap}" != "0" ] && SWAP_ARG="-s ${swap}"

readconf buildworld.conf
. ${workdir}/universe.subr
. ${workdir}/freebsd_world.subr

. ${buildconf}

init_target_arch
init_srcdir
init_supported_arch
init_basedir
init_kerneldir

echo zfsinstall_run -d ${devs} -p ${pool} -m ${mnt} ${SWAP_ARG}
zfsinstall_run -d ${devs} -p ${pool} -m ${mnt} ${SWAP_ARG}

#                d) DEVS="$DEVS ${OPTARG##/dev/}" ;;
#                u) URL="${OPTARG}" ;;
#                t) ARCHIVE="${OPTARG}" ;;
#                p) POOL="${OPTARG}" ;;
#                s) SWAP="${OPTARG}" ;;
#                m) MNT="${OPTARG}" ;;
#                r) RAID="${OPTARG}" ;;
#                z) ZPART="${OPTARG}" ;;
#                V) VERSION="${OPTARG}" ;;
#                C) COMPAT=1 ;;
#                c) LZJB=1 ;;
#                l) LEGACY=1 ;;
#                4) FLETCHER=1 ;;
