#!/bin/sh
#
# PROVIDE: cbsd
# REQUIRE: DAEMON sshd
# KEYWORD: shutdown
#
#
# cbsd_enable="YES"
#

. /etc/rc.subr

name=cbsd
rcvar=cbsd_enable
load_rc_config $name

: ${cbsd_enable="NO"}

export workdir="${cbsd_workdir}"
export PATH=${PATH}:/usr/local/bin:/usr/local/sbin/

globalconf=${cbsd_globalconf:-"${workdir}/cbsd.conf"}

if [ ! -f ${globalconf} ]; then
    echo "no such conf file";
    exit
fi

. ${globalconf}
. ${inventory}
. ${mdtools}
. ${subr}

if [ ! -f ${localcbsdconf} ]; then
    echo "no such local conf file";
    exit
fi

. ${localcbsdconf}

start_precmd=${name}_prestart
stop_precmd=${name}_prestop
stop_postcmd=${name}_poststop

command="${workdir}/sbin/${name}"
pidfile="/var/run/$name.pid"

cbsd_prestart() {
    ${rcddir}/cleartmp start
    ${rcddir}/cbsdtaskd start

    if [ ${mdtmp} -gt 0 -a ${mdtmp} -lt 100 ]; then
	mdmfs -M -S -o async -s ${mdtmp}m md ${ftmpdir}
    fi

    ${rcddir}/jails-astart start
    #/usr/sbin/daemon ${sbindir}/nodeinetd 200 ${sbindir}/sbin/ncctld
    #${rcddir}/nodepinger start

    [ -n "$nat_enable" ] && /usr/local/bin/cbsd naton

    if [ ${ipfw_enable} -eq 1 -a -n "`sysctl -qn net.inet.ip.fw.enable`"  ]; then
	echo "Setup FW counter"
	FWIN=${fwcount_st}
	FWOUT=$((FWIN + 1))

	### FWIN
	FW=`/sbin/ipfw show ${FWIN}`
	RCODE=$?
	if [ ${RCODE} -ne 0 ]; then
	    /sbin/ipfw -q add ${FWIN} count ip from any to me
	 else
	    /sbin/ipfw -q delete ${FWIN}
	    /sbin/ipfw -q add ${FWIN} count ip from any to me
	fi

	### FWOUT
	FW=`/sbin/ipfw show ${FWOUT}`
	RCODE=$?
	if [ ${RCODE} -ne 0 ]; then
	    /sbin/ipfw -q add ${FWOUT} count ip from me to any
	else
	    /sbin/ipfw -q delete ${FWOUT}
	    /sbin/ipfw -q add ${FWOUT} count ip from me to any
	fi
    fi
}

cbsd_prestop()
{
    ${rcddir}/jails-astart stop
    ${rcddir}/cbsdtaskd stop
    #${rcddir}/nodepinger stop

    [ -n "${nat_enable}" ] && /usr/local/bin/cbsd natoff

    if [ ${ipfw_enable} -eq 1 -a -n "`sysctl -qn net.inet.ip.fw.enable`" ]; then
	echo "Setup FW counter"
	FWIN=${fwcount_st}
	FWOUT=$((FWIN + 1))
	### FWIN
	FW=`/sbin/ipfw show ${FWIN}`
	RCODE=$?
	if [ ${RCODE} -eq 0 ]; then
	    /sbin/ipfw -q delete ${FWIN}
	fi
	### FWOUT
	FW=`/sbin/ipfw show ${FWOUT}`
	RCODE=$?
	if [ ${RCODE} -eq 0 ]; then
	    /sbin/ipfw -q delete ${FWOUT}
	fi
    fi
}


cbsd_poststop()
{
    if [ ${mdtmp} -gt 0 -a ${mdtmp} -lt 100 ]; then
	# search for slow jails and wait him before destroy ftmp
	# wait_for_jstop
	/usr/local/bin/cbsd unmountmd jroot="$ftmpdir"
    fi
}


run_rc_command "$1"
