#!/bin/sh
#
# PROVIDE: cbsd_statsd
# REQUIRE: LOGIN FILESYSTEMS sshd
# KEYWORD: shutdown
#
# cbsd_statsd_enable="YES"
#

. /etc/rc.subr

name=cbsd_statsd
rcvar=cbsd_statsd_enable
load_rc_config $name

: ${cbsd_statsd_enable:="NO"}

start_cmd=${name}_start
#status_cmd="${name}_status"
#stop_cmd=${name}_stop
restart_cmd=${name}_restart
extra_commands="restart"

command="${cbsd_workdir}/tools/racct-statsd"
pidfile="/var/run/$name.pid"
command_args="&"

# Set defaults
: ${cbsd_statsd_enable:="NO"}
: ${cbsd_statsd_interval:="15"}
: ${cbsd_statsd_root:="/tmp/metrics/rctl"}

pidfile=/var/run/racct-statsd.pid

cbsd_statsd_start()
{
	env workdir=${cbsd_workdir} ${cbsd_workdir}/tools/racct-statsd > /dev/null 2>&1
	# > /tmp/cbsd_statsd.log 2>&1
}

cbsd_statsd_restart()
{
	cbsd_statsd_stop
	cbsd_statsd_start
}

run_rc_command "$1"
