#!/bin/sh
. /etc/rc.conf

workdir="${cbsd_workdir}"
globalconf="${workdir}/cbsd.conf";

[ -f "${globalconf}" ] || {
    echo "no globalconf file"
    exit 1
}

. ${globalconf}
. ${subr}

export PATH=${PATH}:/usr/local/bin:/usr/local/sbin/

jails_stop() {
    local _J _jid
    for _J in  `/usr/local/bin/cbsd jorder`; do
	. ${jailrcconfdir}/rc.conf_${_J}
	[ -z "${jname}" ] && continue
	[ $baserw -eq 1 ] && path=$data

	get_jid
	_jid=$?

	[ ${_jid} -ge 0 ] && {
	    echo "Stopping ${jname} ..."
	    /usr/sbin/daemon -p ${ftmpdir}/jstop.${jname}.$$ /usr/local/bin/cbsd jstop ${jname}
	    cbsd pwait --pid=`cat ${ftmpdir}/jstop.${jname}.$$` --timeout=5
	    sync
	}
    done
}

jails_start() {
    local _J
    for _J in  `/usr/local/bin/cbsd jorder`; do
	. ${jailrcconfdir}/rc.conf_${_J}
	[  -z "${jname}" ] && continue
	if [ "$astart" -eq 1 ]; then
	    /usr/sbin/daemon -p ${ftmpdir}/jstart.${jname}.$$ /usr/local/bin/cbsd jstart jname=${jname} inter=0
	    cbsd pwait --pid=`cat ${ftmpdir}/jstart.${jname}.$$` --timeout=5
	fi
    done
}

#### MAIN ####
case $1 in
    start) jails_start ;;
    stop) jails_stop ;;
esac
