#!/bin/sh
. /etc/rc.conf

workdir="${cbsd_workdir}"
globalconf="${workdir}/cbsd.conf";

[ -f "${globalconf}" ] || {
    echo "no globalconf file"
    exit 1
}

. ${globalconf}
. ${subr}
. ${inventory}
. ${color}

export PATH=${PATH}:/usr/local/bin:/usr/local/sbin/

jails_stop() {
    local _J _jid

    for _J in  `/usr/local/bin/cbsd jorder`; do
	. ${jailrcconfdir}/rc.conf_${_J}
	[ -z "${jname}" ] && continue

	ST=`/usr/local/bin/cbsd jstatus jname=${jname}`
	[ $ST -eq 0 ] && continue
#	[ "${astart}" != "1" ] && continue

	$ECHO "${MAGENTA}Auto-stop jail: ${GREEN}${jname}${NORMAL}"
	/usr/sbin/daemon -p ${ftmpdir}/jstop.${jname}.$$ /usr/local/bin/cbsd jstop jname=${jname}
	[ -f "${ftmpdir}/jstop.${jname}.$$" ] && PID=`cat ${ftmpdir}/jstop.${jname}.$$ 2>/dev/null`
	[ -n "${PID}" ] && /usr/local/bin/cbsd pwait --pid=`cat ${ftmpdir}/jstop.${jname}.$$` --timeout=${parallel}
    done

    wait_for_jstop
}

jails_start() {
    local _J

    for _J in  `/usr/local/bin/cbsd jorder`; do
	. ${jailrcconfdir}/rc.conf_${_J}
	[  -z "${jname}" ] && continue
	[ "${astart}" != "1" ] && continue
	/usr/sbin/daemon -p ${ftmpdir}/jstart.${jname}.$$ /usr/local/bin/cbsd jstart jname=${jname}
	[ -f "${ftmpdir}/jstart.${jname}.$$" ] && PID=`cat ${ftmpdir}/jstart.${jname}.$$ 2>/dev/null`
        [ -n "${PID}" ] && /usr/local/bin/cbsd pwait --pid=`cat ${ftmpdir}/jstart.${jname}.$$` --timeout=${parallel}
    done

    wait_for_jstart
}

#### MAIN ####
case $1 in
    start) jails_start ;;
    stop) jails_stop ;;
esac
