#!/bin/sh
#v10.0.2
globalconf="${workdir}/cbsd.conf";
CBSDMODULE="webdev"
MYARG=""
MYOPTARG="daemon"
MYDESC="WebDev install script. wrapper for zfsinstall"
ADDHELP="possible mode:\n"

set -e
. ${globalconf}
set +e

. ${subr}
init $*

#defines
_MYDIR=$(dirname `realpath $0`)

### MAIN Route ###
set -e
	. ${_MYDIR}/wb_zfs_install.subr
set +e

[ ! -f "${IS_DISTRIBUTION}" ] && err 1 "You running in not distribution media mode (${IS_DISTRIBUTION}). Exit"

if [ -z "${daemon}" ]; then
	echo "0:0:0" >${PROGRESS_FILE}
	chmod 0777 ${PROGRESS_FILE}
	/sbin/daemon /usr/local/bin/cbsd wb_reboot daemon=1 >/dev/null 2>&1
	exit 0
fi

sleep 3
/sbin/shutdown -r now
