#!/bin/sh
#v10.0.6
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="out jname pkgdbdir portname"
MYDESC="Show installed 'leaf' packages, that not referenced by any port"
ADDHELP="out=filename - update mode, redirect output to out=filename\n\
jname=jname info for jail jname\n\
pkgdbdir= use this path for info instead of query by jname\n\
filter= - additional argument to pkg info\n\
portname=nameport - query for nameport only\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${strings}
init $*

[ -z "${filter}" ] && filter=""
[ -z "${portname}" ] && portname=""

if [ -n "${jname}" ]; then
	. ${jrcconf}
	[ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
	DBDIR="${data}/var/db/pkg"
else
	if [ -n "${pkgdbdir}" ]; then
		DBDIR="${pkgdbdir}"
	else
		DBDIR="/var/db/pkg"
	fi
fi

if [ -n "${out}" ]; then
	[ ! -d $( dirname ${out} ) ] && mkdir -p $( dirname ${out} )
	truncate -s0 ${out}
else
	out="/dev/stdout"
fi

[ ! -d "${DBDIR}" ] && err 1 "No such pkg pkgdbdir"

for i in $( env PKG_DBDIR="${DBDIR}" /usr/sbin/pkg info -oqa ); do
	A=$( /usr/sbin/pkg query "%ro" $i )
	[ -z "${A}" ] && printf "/usr/ports/$i\n" >> ${out}
done
