BSDCFG_SHARE="/usr/share/bsdconfig"
. $BSDCFG_SHARE/common.subr || exit 1
f_dprintf "%s: loading includes..." "$0"
f_include $BSDCFG_SHARE/dialog.subr
f_include $BSDCFG_SHARE/mustberoot.subr

BSDCFG_LIBE="/usr/libexec/bsdconfig" APP_DIR="080.console"

: ${msg_yes:="Yes"}
: ${msg_no:="No"}
: ${msg_ok:="Ok"}
: ${msg_cancel:="Cancel"}


if [ -n "${EXTHELP}" ]; then
	cbsd_help="--help-button --help-label \"\$msg_help\""
else
	cbsd_help=
fi

