if [ ! "$_CBSD_TIME_SUBR" ]; then
_CBSD_TIME_SUBR=1
###

# convert seconds to human readable time
displaytime()
{
	local T=$1
	local D=$((T/60/60/24))
	local H=$((T/60/60%24))
	local M=$((T/60%60))
	local S=$((T%60))
	[ ${D} -gt 0 ] && printf '%d days ' $D
	[ $H -gt 0 ] && printf '%d hours ' $H
	[ $M -gt 0 ] && printf '%d minutes ' $M
	[ $D -gt 0 -o $H -gt 0 -o $M -gt 0 ] && printf 'and '
	printf '%d seconds\n' $S
}

###
fi
