if [ ! "$_CBSD_BSDCONFIG_SUBR" ]; then
_CBSD_BSDCONFIG_SUBR=1
###

: ${CIX_DISTDIR:=/usr/local/cbsd}
BSDCFG_SHARE="${CIX_DISTDIR}/share/bsdconfig"
. $BSDCFG_SHARE/common.subr || exit 1
f_include $BSDCFG_SHARE/dialog.subr
BSDCFG_LIBE="${CIX_DISTDIR}/share/bsdconfig" APP_DIR="cbsd"

ipgm=$( f_index_menusel_keyword $BSDCFG_LIBE/$APP_DIR/INDEX "$pgm" )
[ $? -eq $SUCCESS -a "$ipgm" ] && pgm="$ipgm"

###
fi
