# This file can be used for integration any external /bin/sh script
# with CBSD, e.g:
# --
# #!/bin/sh
#[ -z "${CIX_DISTDIR}" ] && CIX_DISTDIR="/usr/local/cbsd"
#[ ! -r "${CIX_DISTDIR}/subr/cbsdbootstrap.subr" ] && exit 1
#. ${CIX_DISTDIR}/subr/cbsdbootstrap.subr || exit 1
# --
if [ ! "$_CBSDBOOTSTRAP_SUBR" ]; then
_CBSDBOOTSTRAP_SUBR=1
###
[ -z "${CIX_DISTDIR}" ] && CIX_DISTDIR="/usr/local/cbsd"
[ ! -r "${CIX_DISTDIR}/cbsd.conf" ] && exit 1

# support for workdir and cbsd_workdir (prefered) variable
if [ -n "${cbsd_workdir}" -a -n "${workdir}" ]; then
	workdir="${cbsd_workdir}"
elif [ -n "${cbsd_workdir}" ]; then
	workdir="${cbsd_workdir}"
elif [ -n "${workdir}" ]; then
	cbsd_workdir="${workdir}"
else
	. /etc/rc.conf
	workdir="${cbsd_workdir}"
fi

[ -z "${cbsd_workdir}" ] && exit 1

. ${CIX_DISTDIR}/cbsd.conf
. ${CIX_DISTDIR}/subr/tools-lite.subr

###
fi
