if [ ! "$_CBSD_EMULATOR_SUBR" ]; then
_CBSD_EMULATOR_SUBR=1
###

init_usermode_emul()
{
	# for qemu user mode
	if [ -n "${emulator}" ]; then
		[ "${emulator}" = "jail" ] && return 0
		[ "${emulator}" = "bhyve" ] && return 0
		capture emultest command -v ${emulator}
		[ $? -eq 1 -o -z "${emultest}" ] && err 1 "no such emulator: ${emulator}"
		_check_static_elf()
		{
			${LDD_CMD} ${1} 2>&1 | ${GREP_CMD} "not a dynamic ELF"
		}
		capture static_test _check_static_elf ${emultest}
		[ -z "${static_test}" ] && err 1 "${emultest} must be static. Please rebuild them"
	else
		err 1 "No such emulator variable"
	fi
}

###
fi
