if [ ! "$_CBSD_FORMS_SUBR" ]; then
_CBSD_FORMS_SUBR=1
###

get_custom_id()
{
	local _id=

	[ -z "${formfile}" ] && err 1 "${N1_COLOR}get_custom_id: formfile empty${N0_COLOR}"
	[ ! -r "${formfile}" ] && err 1 "${N1_COLOR}get_custom_id: formfile not exist: ${N2_COLOR}${formfile}${N0_COLOR}"

	_id=$( ${SQLITE3_CMD} ${formfile} "SELECT COUNT(param) FROM forms WHERE param LIKE '%${1}%'" 2>/dev/null | ${AWK_CMD} '{printf $1'} )
	[ -z "${_id}" ] && _id=0
	_id=$(( _id + 1 ))
	printf "${_id}"
}

###
fi
