if [ ! "$_CBSD_JCREATE_SUBR" ]; then
_CBSD_JCREATE_SUBR=1
###

# export JARG
. ${distsharedir}/jail-arg

# postaction for bsdconf-related module action
# pkg, useradd, password etc
# $1 - set $jname
# $2 - jconf (for fromfile)
postcreate_module_action()
{
	local jname= jconf= _ret=0 _logfile=

	[ -z "${CIX_BIN}" ] && CIX_BIN="/usr/local/bin/cbsd"

	[ -n "${1}" ] && jname="${1}"
	[ -n "${2}" ] && jconf="${2}"

	[ -n "${opkg_bootstrap}" ] && pkg_bootstrap="${opkg_bootstrap}"

	capture _logfile ${MKTEMP_CMD}
	trap "${RM_CMD} -f ${_logfile}" HUP INT ABRT BUS TERM EXIT

	if [ -n "${user_pw_root_crypt}" ]; then
		passwd jname=${jname} login="root" epw="${user_pw_root_crypt}" > ${_logfile} 2>&1
	elif [ -n "${user_pw_root}" ]; then
		passwd jname=${jname} login="root" pw="${user_pw_root}" > ${_logfile} 2>&1
	fi

	if [ -n "${sysrc_enable}" ]; then
		for _i in ${sysrc_enable}; do
			# use CBSD sysrc from bsdconf.d
			sysrc jname=${jname} ${_i}_enable="YES" > ${_logfile} 2>&1
		done
	fi

	if [ -n "${user_add}" ]; then
		if [ -n "${jconf}" ]; then
			${ECHO} "${N1_COLOR}Adding users: ${N2_COLOR}${user_add}${N0_COLOR}"
			# use CBSD adduser from bsdconf.d
			adduser jname=${jname} mode=add fromfile="${jconf}" > ${_logfile} 2>&1
		fi
	fi

	[ -n "${odelpkglist}" ] && delpkglist="${odelpkglist}"
	[ -z "${delpkglist}" ] && delpkglist=0

	#[ ${applytpl} -eq 1 ] && ${miscdir}/config_pkgrepo -t ${etcdir}/pkg.conf -v ${ver} -a ${arch} ${data}
	# pkg area
	if [ "${pkg_bootstrap}" = "1" ]; then
		# Dup for modules/pkg/pkg.subr init_path func
		if [ "${platform}" != "DragonFly" ]; then
			# not for DFLY: https://mirror-master.dragonflybsd.org/dports/bootstraps/bootstrap_pkg_03_x86-64.tar.xz have old pkg, we use pkg-static from the base,
			# thanks to preparebase
			if [ "${ver}" != "empty" ]; then
				# bootstrap in parallel when no pkglist
				if [ -z "${pkglist}" ]; then
					${miscdir}/daemonize ${CIX_BIN} pkg mode=bootstrap jname=${jname} cbsd_pkg_verbose=0 > /dev/null 2>&1
				else
					pkg mode=bootstrap jname=${jname} cbsd_pkg_verbose=0 > ${_logfile} 2>&1
					_ret=$?
					if [ ${_ret} -ne 0 ]; then
						${ECHO} "${N1_COLOR}${CIX_APP}: ${W1_COLOR}pkg bootstrap error:${N0_COLOR}"
						${ECHO} "--"
						${CAT_CMD} ${_logfile}
						${ECHO} "--"
						${RM_CMD} -f ${_logfile}
						return ${_ret}
					fi
				fi
			fi
		fi
		if [ -n "${pkglist}" ] && [ "${pkglist}" != "NO" ] && [ "${ver}" != "empty" ]; then
			if [ ! -r "${pkglist}" ]; then
				# use CBSD pkg from pkg.d
				# bootstrap in parallel when no pkglist
				if [ -z "${pkglist}" ]; then
					${miscdir}/daemonize ${CIX_BIN} pkg mode=install jname=${jname} ${pkglist} cbsd_pkg_verbose=1 > /dev/null 2>&1
				else
					pkg mode=install jname=${jname} ${pkglist} cbsd_pkg_verbose=1 > ${_logfile} 2>&1
					_ret=$?
					if [ ${_ret} -ne 0 ]; then
						${CAT_CMD} ${_logfile}
						${RM_CMD} -f ${_logfile}
						return ${_ret}
					else
						${CAT_CMD} ${_logfile}
					fi
				fi
			else
				# use CBSD pkg from pkg.d
				pkg mode=install pkglist="${pkglist}" jname=${jname} cbsd_pkg_verbose=1 > ${_logfile} 2>&1
				_ret=$?
				[ ${delpkglist} -eq 1 ] && ${RM_CMD} -f ${pkglist}
				if [ ${_ret} -ne 0 ]; then
					${CAT_CMD} ${_logfile}
					${RM_CMD} -f ${_logfile}
					return ${_ret}
				else
					${CAT_CMD} ${_logfile}
				fi
			fi
		fi
	fi

	${RM_CMD} -f ${_logfile}
	return ${_ret}
}

# users custom stop script
# -s - is source dir (stop.d start.d)
# -a auto-start if status off (create.d)
external_exec_script()
{
	local _res=
	local _dir=
	local _astart=0
	local _shutdown=0
	local _fexist=

	while getopts "as:" opt; do
		case "${opt}" in
			a) _astart="1" ;;
			s) _dir="${OPTARG}" ;;
		esac
		shift $(( OPTIND - 1 ))
	done

	[ -z "${_dir}" ] && return 1

	capture _fexist cix_read_dir ${jailsysdir}/${jname}/${_dir} 2>/dev/null
	[ $? -ne 0 ] && return 0

	#_fexist=$( ${FIND_CMD} ${jailsysdir}/${jname}/${_dir}/ -mindepth 1 -maxdepth 1 -type f -and -not -name placeholder -exec ${BASENAME_CMD} {} \; )
	[ -z "${_fexist}" ] && return 0
	[ -d "${data}/tmp/${_dir}" ] && ${RM_CMD} -rf "${data}/tmp/${_dir}"
	${CP_CMD} -a "${jailsysdir}/${jname}/${_dir}" ${data}/tmp/${_dir}

	. ${subrdir}/rcconf.subr

	if [ ${jid} -eq 0 ] && [ ${_astart} -eq 1 ]; then
		# Jail should be running
		${ECHO} "${N1_COLOR}Jail has custom exec script [${_fexist}], run it for a while...${N0_COLOR}"
		_shutdown=1
		jstart ${jname}
	fi

	${FIND_CMD} "${data}/tmp/${_dir}" -mindepth 1 -maxdepth 1 \( -type l -or -type f \) -and  \( -perm -u=x -o -perm -g=x -o -perm -o=x \) -exec ${BASENAME_CMD} {} \; | while read _file; do
		${ECHO} "${N1_COLOR}Execute script: ${N2_COLOR}${_file}${N0_COLOR}"
		jexec jname="${jname}" /tmp/${_dir}/${_file}
	done

	if [ ${_shutdown} -eq 1 ]; then
		# Jail was offline, stop
		jstop ${jname}
	fi

	${RM_CMD} -rf "${data}/tmp/${_dir}"
}

# users custom stop for executing in master host
# $1 - is source dir name ( master_poststop.d master_prestop.d )
# can be full path to dir when started by '/'
external_exec_master_script()
{
	local _res=
	local _dir="${1}"
	local _prefix
	local _srcdir

	[ -z "${_dir}" ] && return 1

	capture _prefix substr --pos=0 --len=1 --str="${_dir}"
	if [ "${_prefix}" = "/" ]; then
		_srcdir="${_dir}"
	else
		_srcdir="${jailsysdir}/${jname}/${_dir}"
	fi

	if ! cix_read_dir "${_srcdir}" > /dev/null 2>&1; then
		return 0
	fi

#	[ ! -d "${_srcdir}" ] && return 0
#	[ -z "$( ${LS_CMD} ${_srcdir}/ )" ] && return 0

	[ -z "${quiet}" ] && quiet=0

	local _CBSDPATH="${PATH}"
	# reset CBSD PATH
	# it is necessary that the calling of any commands from external hooks
	# does not conflict with the same CBSD commands that the user does not expect
	export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

	# reset CBSD_CWD/CIX_PWD ( can affect when work via CBSDfile )
	local _OCBSD_CWD="${CBSD_CWD}"
	local _OCIX_PWD="${CIX_PWD}"
	export CBSD_CWD=""
	export CIX_PWD=""

	${FIND_CMD} "${_srcdir}" -mindepth 1 -maxdepth 1 \( -type l -or -type f \) -and  \( -perm -u=x -o -perm -g=x -o -perm -o=x \) -exec ${BASENAME_CMD} {} \; | while read _file; do
		[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}Execute master script: ${N2_COLOR}${_file}${N0_COLOR}"
		[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR} :: ${_srcdir}/${_file}${N0_COLOR}"
		${_srcdir}/${_file}
	done

	# restore CBSD PATH
	export PATH="${_CBSDPATH}"

	# restore CBSD_CWD/CIX_PWD
	export CBSD_CWD="${_OCBSD_CWD}"
	export CIX_PWD="${_OCIX_PWD}"
}

# users custom local script for external operate with data
# $1 - is source dir name ( clone.d rename.d .. )
# return code:
#   - 0 - no custom local script ( skip )
#   - 1 - script(s) exist and executed successful
#   - 2 - script(s) exist but execution failed ( cancel operation )
external_exec_local_script()
{
	local _res=
	local _dir="${1}"
	local _ret=0

	[ -z "${_dir}" ] && return 1

	local _srcdir="${jailsysdir}/${jname}/${_dir}"

	if ! cix_read_dir "${_srcdir}" > /dev/null 2>&1; then
		return 0
	fi

#	[ ! -d "${_srcdir}" ] && return 0
#	[ -z "$( ${LS_CMD} ${_srcdir}/ )" ] && return 0

	local _CBSDPATH="${PATH}"
	# reset CBSD PATH
	# it is necessary that the calling of any commands from external hooks
	# does not conflict with the same CBSD commands that the user does not expect
	export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

	${FIND_CMD} "${_srcdir}" -mindepth 1 -maxdepth 1 \( -type l -or -type f \) -and  \( -perm -u=x -o -perm -g=x -o -perm -o=x \) -exec ${BASENAME_CMD} {} \; | while read _file; do
		${ECHO} "${N1_COLOR}Execute local script: ${N2_COLOR}${_file}${N0_COLOR}"
		${ECHO} "${N1_COLOR} :: ${_srcdir}/${_file}${N0_COLOR}"
		${_srcdir}/${_file}
		_ret=$?
		[ ${_ret} -ne 0 ] && exit 2
	done

	_ret=$?

	# restore CBSD PATH
	export PATH="${_CBSDPATH}"
	return ${_ret}
}

exec_master_prestop()
{
	local _CMD=
	eval _CMD=\${exec_master_prestop}
	[ -z "${_CMD}" ] || [ "${_CMD}" = "0" ] && return 0

	local _CBSDPATH="${PATH}"
	# reset CBSD PATH
	# it is necessary that the calling of any commands from external hooks
	# does not conflict with the same CBSD commands that the user does not expect
	export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

	${ECHO} "${N1_COLOR}${jname} Master exec prestop: ${N2_COLOR}${_CMD}${N0_COLOR}"
	${_CMD}
	# restore CBSD PATH
	export PATH="${_CBSDPATH}"
}

exec_prestop()
{
	local _CMD=
	eval _CMD=\${exec_prestop}
	[ -z "${_CMD}" ] || [ "${_CMD}" = "0" ] && return 0

	local _CBSDPATH="${PATH}"
	# reset CBSD PATH
	# it is necessary that the calling of any commands from external hooks
	# does not conflict with the same CBSD commands that the user does not expect
	export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

	${ECHO} "${N1_COLOR}${jname} exec exec_prestop: ${N2_COLOR}${_CMD}${N0_COLOR}"
	${CHROOT_CMD} ${path} ${_CMD}
	# restore CBSD PATH
	export PATH="${_CBSDPATH}"
}


exec_master_poststop()
{
	local _CMD=
	eval _CMD=\${exec_master_poststop}
	[ -z "${_CMD}" ] || [ "${_CMD}" = "0" ] && return 0

	local _CBSDPATH="${PATH}"
	# reset CBSD PATH
	# it is necessary that the calling of any commands from external hooks
	# does not conflict with the same CBSD commands that the user does not expect
	export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

	${ECHO} "${N1_COLOR}${jname} Master exec afterstop: ${N2_COLOR}${_CMD}${N0_COLOR}"
	${_CMD}
	# restore CBSD PATH
	export PATH="${_CBSDPATH}"
}

exec_poststop()
{
	local _CMD=
	eval _CMD=\${exec_poststop}
	[ -z "${_CMD}" ] || [ "${_CMD}" = "0" ] && return 0

	local _CBSDPATH="${PATH}"
	# reset CBSD PATH
	# it is necessary that the calling of any commands from external hooks
	# does not conflict with the same CBSD commands that the user does not expect
	export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

	${ECHO} "${N1_COLOR}${jname} exec exec_poststop: ${N2_COLOR}${_CMD}${N0_COLOR}"
	${CHROOT_CMD} ${path} ${_CMD}
	# restore CBSD PATH
	export PATH="${_CBSDPATH}"
}

exec_master_poststart()
{
	local _CMD=
	eval _CMD=\${exec_master_poststart}
	[ -z "${_CMD}" ] || [ "${_CMD}" = "0" ] && return 0

	local _CBSDPATH="${PATH}"
	# reset CBSD PATH
	# it is necessary that the calling of any commands from external hooks
	# does not conflict with the same CBSD commands that the user does not expect
	export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

	${ECHO} "${N1_COLOR}${jname} Master exec afterstart: ${N2_COLOR}${_CMD}${N0_COLOR}"
	${_CMD}
	# restore CBSD PATH
	export PATH="${_CBSDPATH}"
}

exec_poststart()
{
	local _CMD=
	eval _CMD=\${exec_poststart}
	[ -z "${_CMD}" ] || [ "${_CMD}" = "0" ] && return 0

	${ECHO} "${N1_COLOR}${jname} exec exec_poststart: ${N2_COLOR}${_CMD}${N0_COLOR}"
	jexec jname=${jname} ${_CMD}
}

exec_cbsdjail_first_boot()
{
	if [ -f "${path}/etc/rc.cbsdjail_first_boot" ]; then
		jexec jname=${jname} /bin/sh /etc/rc.cbsdjail_first_boot
		${RM_CMD} -f "${path}/etc/rc.cbsdjail_first_boot"
	fi
}

exec_master_prestart()
{
	local _CMD=
	eval _CMD=\${exec_master_prestart}
	[ -z "${_CMD}" ] || [ "${_CMD}" = "0" ] && return 0

	local _CBSDPATH="${PATH}"
	# reset CBSD PATH
	# it is necessary that the calling of any commands from external hooks
	# does not conflict with the same CBSD commands that the user does not expect
	export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

	${ECHO} "${N1_COLOR}${jname} master exec prestart: ${N2_COLOR}${_CMD}${N0_COLOR}"
	${_CMD}
	# restore CBSD PATH
	export PATH="${_CBSDPATH}"
}

exec_prestart()
{
	local _CMD=
	eval _CMD=\${exec_prestart}
	[ -z "${_CMD}" ] || [ "${_CMD}" = "0" ] && return 0

	${ECHO} "${N1_COLOR}${jname} exec exec_prestart: ${N2_COLOR}${_CMD}${N0_COLOR}"
	jexec jname=${jname} ${_CMD}
}

# $* - additional vars, e.g: $data, $newdata
export_bhyve_data_for_external_hook()
{
	local _nic_id= _i= T=

	. ${subrdir}/vnet.subr		# for get_vm_uplink_interface

	# export variables for external hooks
	export jname=${jname}
	[ -n "${ip4_addr}" ] && geniplist "${ip4_addr}"

	for _i in ${JARG} ${MYCOL} ipv4_first_public ipv4_first_private ipv4_first ipv6_first_public ipv6_first_private ipv6_first bhyve_vnc_tcp_ipconnect $*; do
		T=
		eval T="\$$_i"
		export ${_i}="${T}"
	done

	# Export additional data to hooks
	if [ -r "${jailsysdir}/${jname}/vnc_port" ]; then
		capture vm_vnc_port ${CAT_CMD} ${jailsysdir}/${jname}/vnc_port
		export vm_vnc_port="${vm_vnc_port}"
	fi

	_nic_id=0

	eval $( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite "SELECT nic_hwaddr,nic_parent FROM bhyvenic" | while read nic_hwaddr nic_parent; do
		echo "export nic_hwaddr${_nic_id}=\"${nic_hwaddr}\""
		get_vm_uplink_interface -p ${nic_parent} -r 1
		echo "export nic_parent${_nic_id}=\"${interface}\""
		_nic_id=$(( _nic_id + 1 ))
	done )
	return 0
}

# $* - additional vars, e.g: $data, $newdata
export_xen_data_for_external_hook()
{
	local _nic_id= _i= T=

	. ${subrdir}/vnet.subr		# for get_vm_uplink_interface

	# export variables for external hooks
	export jname=${jname}
	[ -n "${ip4_addr}" ] && geniplist "${ip4_addr}"

	for _i in ${JARG} ${MYCOL} ipv4_first_public ipv4_first_private ipv4_first ipv6_first_public ipv6_first_private ipv6_first bhyve_vnc_tcp_ipconnect $*; do
		T=
		eval T="\$$_i"
		export ${_i}="${T}"
	done

	# Export additional data to hooks
	if [ -r "${jailsysdir}/${jname}/vnc_port" ]; then
		capture vm_vnc_port ${CAT_CMD} ${jailsysdir}/${jname}/vnc_port
		export vm_vnc_port="${vm_vnc_port}"
	fi

	_nic_id=0

	eval $( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite "SELECT nic_hwaddr,nic_parent FROM xennic" | while read nic_hwaddr nic_parent; do
		echo "export nic_hwaddr${_nic_id}=\"${nic_hwaddr}\""
		get_vm_uplink_interface -p ${nic_parent} -r 1
		echo "export nic_parent${_nic_id}=\"${interface}\""
		_nic_id=$(( _nic_id + 1 ))
	done )
	return 0
}

# $* - additional vars, e.g: $data, $newdata
export_qemu_data_for_external_hook()
{
	local _nic_id= _i= T=

	. ${subrdir}/vnet.subr		# for get_vm_uplink_interface

	# export variables for external hooks
	export jname=${jname}
	[ -n "${ip4_addr}" ] && geniplist "${ip4_addr}"

	# todo: spice
	for _i in ${JARG} ${MYCOL} ipv4_first_public ipv4_first_private ipv4_first ipv6_first_public ipv6_first_private ipv6_first qemu_vnc_tcp_ipconnect $*; do
		T=
		eval T="\$$_i"
		export ${_i}="${T}"
	done

	# todo: spice
	# Export additional data to hooks
	if [ -r "${jailsysdir}/${jname}/vnc_port" ]; then
		capture vm_vnc_port ${CAT_CMD} ${jailsysdir}/${jname}/vnc_port
		export vm_vnc_port="${vm_vnc_port}"
	fi

	_nic_id=0

	eval $( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite "SELECT nic_hwaddr,nic_parent FROM qemunic" | while read nic_hwaddr nic_parent; do
		echo "export nic_hwaddr${_nic_id}=\"${nic_hwaddr}\""
		get_vm_uplink_interface -p ${nic_parent} -r 1
		echo "export nic_parent${_nic_id}=\"${interface}\""
		_nic_id=$(( _nic_id + 1 ))
	done )
	return 0
}


# $* - additional vars, e.g: $data, $newdata
export_jail_data_for_external_hook()
{
	local _nic_id= _i= T=

	. ${subrdir}/vnet.subr		# for get_vm_uplink_interface

	# export variables for external hooks
	# todo: first_ipv4_addr + first_ipv6_addr
	export jname=${jname}

	[ -n "${ip4_addr}" ] && geniplist "${ip4_addr}"

	for _i in ${JARG} ipv4_first_public ipv4_first_private ipv4_first ipv6_first_public ipv6_first_private ipv6_first nic_address $*; do
		T=
		eval T="\$$_i"
		export ${_i}="${T}"
	done

	if [ -r "${jailsysdir}/${jname}/local.sqlite" ]; then
		cbsdsqlro_vars "${jailsysdir}/${jname}/local.sqlite" "SELECT nic_address FROM jailnic LIMIT 1"
		[ -z "${nic_address}" ] && nic_address="0"
	else
		nic_address="0"
	fi

	if [ ${vnet} -eq 1 ]; then
		_nic_id=0

		eval $( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite "SELECT nic_hwaddr,nic_parent,nic_address FROM jailnic" | while read nic_hwaddr nic_parent nic_address; do
			echo "export nic_hwaddr${_nic_id}=\"${nic_hwaddr}\""
			echo "export nic_address${_nic_id}=\"${nic_address}\""
			get_vm_uplink_interface -p ${nic_parent}
			echo "export nic_parent${_nic_id}=\"${interface}\""
			_nic_id=$(( _nic_id + 1 ))
		done )
	fi

	return 0
}

###
fi
