if [ ! "$_CBSD_LINUX_SUBR" ]; then
_CBSD_LINUX_SUBR=1
###

ECHO="echo"
MORE_CMD="/bin/more"
TOUCH_CMD="/bin/touch"
GREP_CMD="/bin/grep"
SYSRC_CMD="/usr/local/cbsd/misc/sysrc"


# idprio hack
IDLE_IONICE="ionice -c 3"

#_lock_cmd=$( which flock 2>/dev/null )
#if [ -n "${_lock_cmd}" -a -x ${_lock_cmd} ]; then
#	export LOCK_CMD="${_lock_cmd} -w0 -x "
#	unset _lock_cmd
#else
#	echo "No such lock management stuff (lockf, flock)"
#	exit 0
#fi

###
fi
