if [ ! "$_CBSD_NC_LITE_SUBR" ]; then
_CBSD_NC_LITE_SUBR=1
###

# fatal error. Print message to stdout then quit with exitval
err() {
	exitval=$1
	shift
	${ECHO} "$*" 1>&2
	exit ${exitval}
}


# getyesno var
# Show $1 strings and get answer in infinity loop
# return 0 when YES/1 and 1 when not
# return 3 if not interactive ($inter=0) (or INTER=0 env exist)
# if ALWAYS_YES=1 and inter=0, always return 0
# if ALWAYS_NO=1 and inter=0, always return 1
# $1 - pre-defined return: 1 - yes, 0 - no
getyesno()
{
	if [ -n "${2}" ]; then
		case "${2}" in
			1)
				return 0
				;;
			0)
				return 1
				;;
		esac
	fi

	if [ "${inter}" = "0" -o -n "${NOINTER}" ]; then
		[ "${ALWAYS_YES}" = "1" ] && return 0
		[ "${ALWAYS_NO}" = "1" ] && return 1
		return 3
	fi

	${ECHO} "${BOLD}${1}${N0_COLOR}"
	answ=
	while [ x$answ = x ]; do
		${ECHO} "[${N2_COLOR}yes(1) or no(0)${N0_COLOR}]"
		read reply leftover
		case $reply in
			# "yes", "true", "on", or "1"
			Y*|y*|1)
				return 0
			;;
			# "no", "false", "off", or "0"
			N*|n*|0)
				return 1
			;;
		esac
	done
}

# getyesnocancel var
# Show $1 strings and get answer (or cancel) in infinity loop
# return 0 when YES/1 and 1 when not
# return 2 when cancel
# return 3 if not interactive ($inter=0) (or INTER=0 env exist)
# if ALWAYS_YES=1 and inter=0, always return 0
# if ALWAYS_NO=1 and inter=0, always return 1
# $1 - pre-defined return: 1 - yes, 0 - no
getyesnocancel()
{
	if [ -n "${2}" ]; then
		case "${2}" in
			1)
				return 0
				;;
			0)
				return 1
				;;
		esac
	fi

	if [ "${inter}" = "0" -o -n "${NOINTER}" ]; then
		[ "${ALWAYS_YES}" = "1" ] && return 0
		[ "${ALWAYS_NO}" = "1" ] && return 1
		return 3
	fi

	${ECHO} "${BOLD}${1}${N0_COLOR}"
	answ=
	while [ x$answ = x ]; do
		${ECHO} "[${N2_COLOR}yes(1) or no(0) or cancel(2)${N0_COLOR}]"
		read reply leftover
		case ${reply} in
			# "yes", "true", "on", or "1"
			Y*|y*|1)
				return 0
			;;
			# "no", "false", "off", or "0"
			N*|n*|0)
				return 1
			;;
			C*|c*|2)
				return 2
			;;
		esac
	done
}

# value="YES" or "NO"
checkyesno()
{
	eval _value=\$${1}

	case $_value in
		# "yes", "true", "on", or "1"
		[Yy][Ee][Ss]|[Tt][Rr][Uu][Ee]|[Oo][Nn]|1)
			return 0
			;;
		# "no", "false", "off", or "0"
		[Nn][Oo]|[Ff][Aa][Ll][Ss][Ee]|[Oo][Ff][Ff]|0)
			return 1
			;;
		*)
		# echo "\$${1} is not set properly - see ${rcvar_manpage}."
			return 1
			;;
	esac
}

# check&make lockfile $1
# $2 - additional action for trap
# $3 - safe, for force
makelock()
{
	local _pid= _msg=
	local _traps=

	[ -n "${1}" ] && LOCKFILE="${1}"
	[ -z "${LOCKFILE}" ] && err 1 "${N1_COLOR}makelock: empty LOCKFILE vars${N0_COLOR}"
	[ -f "${LOCKFILE}" -a "${3}" = "safe" ] && ${RM_CMD} -f ${LOCKFILE}
	if [ -f "${LOCKFILE}"  ]; then
		read _pid _ < ${LOCKFILE}
		[ -n "${_pid}" ] && _msg="by ${_pid}"
		err 1 "locked ${_msg}: ${LOCKFILE}, try later"
	fi
	_traps="${RM_CMD} -f ${LOCKFILE};"

	if [ -n "${2}" ]; then
		_traps="${2}; ${_traps}"
	fi

	trap "${_traps}" HUP KILL INT ABRT BUS TERM EXIT
	[ "$3" = "safe" ] || ${TOUCH_CMD} ${LOCKFILE}
}

# wrapper for including config in $etcdir. $1 is name of the file
# At the first we try to include $etcdir/defaults/$1, in second: $etcdir/$1
# third: ${moduledir}/etc/$1
# finaly: in jailsysdir/jname/etc/
readconf()
{
	[ -z "${1}" ] && return 1

	local _path="${etcdir}/defaults/$1 ${etcdir}/$1"
	local _i=

	# keep order
	[ -n "${CBSDMODULE}" ] && _path="${_path} ${moduledir}/${CBSDMODULE}.d/etc/$1"
	[ -n "${jname}" ] && _path="${_path} ${jailsysdir}/${jname}/etc/${1}"

	for _i in ${_path}; do
		[ -r "${_i}" ] && . "${_i}"
	done

	return 0
}

###
fi
