#v10.0.4
# this is a temporary wrapper for version 9.2.2 is intended to make the transition to sqlite3 version if rc.conf more painless
# required:
# strings.subr
#

if [ ! "$_CBSD_RCCONF_SUBR" ]; then
_CBSD_RCCONF_SUBR=1
###

# load data from local $emulator settings
# $1 - jname
init_emulator_rcconf()
{
	local jname="${1}"
	[ -z "${jname}" ] && return 0
	local _ret=
	local _sqlfile="${dbdir}/${_datafile}.sqlite"
	local _query= _first=1 _i=
	local MYCOL=

	[ ! -r ${jailsysdir}/${jname}/local.sqlite ] && return 0

	. ${distsharedir}/${emulator}_settings.conf

	[ -z "${MYCOL}" ] && return 0

	# construct param1,param2,param3 from "param1 param2 param3" + unset vars
	for _i in ${MYCOL}; do
		unset ${_i}
		if [ ${_first} -eq 0 ]; then
			_query="${_query},${_i}"
		else
			_query="${_i}"
		fi
		_first=0
	done

	cbsdsqlro_vars "${jailsysdir}/${jname}/local.sqlite" "SELECT ${_query} FROM settings ORDER BY (created) DESC LIMIT 1;" ${MYCOL}
	[ $? -ne 0 ] && err 1 "${N1_COLOR}Unable to fetch vm data from: ${N2_COLOR}${jailsysdir}/${jname}/local.sqlite${N0_COLOR}"

	if [ "${emulator}" = "bhyve" ]; then
		cbsdsqlro_vars "${_sqlfile}" "SELECT mnt_start,mnt_stop FROM bhyve WHERE jname='$1'" mnt_start mnt_stop
	fi

	return 0
}


# init_rcconf ( $jname must be not empty )
# ( $sqlfile - specify sqlfile in dbdir for searching data. If empty - local file is prefered )
init_rcconf()
{
	local _ret= _source_emulator= myjid=0
	local _query= _first=1 _i= MYCOL= _datafile="local"

	[ -n "${2}" ] && _datafile="${2}"
	_sqlfile="${dbdir}/${_datafile}.sqlite"

	[ ! -f "${_sqlfile}" ] && return 0

	. ${distsharedir}/local-jails.schema

	# construct param1,param2,param3 from "param1 param2 param3" + unset vars
	for _i in ${MYCOL}; do
		unset ${_i}
		if [ ${_first} -eq 0 ]; then
			_query="${_query},${_i}"
		else
			_query="${_i}"
		fi
		_first=0
	done

	cbsdsqlro_vars "${_sqlfile}" "SELECT ${_query} FROM jails WHERE jname='$1'" ${MYCOL}
	_ret=$?
	[ ${_ret} -ne 0 ] && return 1

	# qemu-user mode
	case "${emulator}" in
		qemu-arm-static|qemu-mips64-static)
			_source_emulator="${emulator}"
			;;
		qemu-aarch64-static)
			_source_emulator="${emulator}"
			arch="arm64"
			target_arch="aarch64"
			;;
		qemu-ppc64-static)
			_source_emulator="${emulator}"
			arch="powerpc"
			target_arch="powerpc64"
			;;
		qemu-riscv64-static)
			_source_emulator="${emulator}"
			arch="riscv"
			target_arch="riscv64"
			;;
	esac

	# skip for wrong emulator
	if [ -n "${_source_emulator}" ]; then
		[ "${_source_emulator}" != "${emulator}" ] && continue
	fi

#	case "${emulator}" in
#		bhyve|virtualbox|xen|qemu)
#			MYCOL=
#			. ${distsharedir}/${emulator}.conf
#			jid=0
#			_ALLBCOL=$( echo ${_BCOL} | ${TR_CMD} " " "," )
#			local sqldelimer="|"
#			_A=$( 2>/dev/null cbsdsqlro ${_sqlfile} "SELECT ${_ALLBCOL} FROM ${emulator} WHERE jname='$1'" )
#			unset sqldelimer
#			sqllist "${_A}" ${_BCOL}
#			;;
#	esac

	init_jail_path

	# real-time sanity check that jid and status are similar to the real state, for localhost  only
	if [ "${_datafile}" = "local" ]; then
		get_jid
		case "${emulator}" in
			"bhyve")
				if [ -e "/dev/vmm/${jname}" ]; then
					[ ${status} -ne 3 ] && status="1"	# if not in maintenance, update status to online
					cbsdsqlro_vars "local" "SELECT jid FROM jails WHERE jname='${jname}'" myjid
					# temp work-around for CBSD 11.1.0 wherei PID was introduced and where old machine
					# still run with 0 jid: change jid to non zero to proper status
					[ -z "${myjid}" -o "${myjid}" = "0" ] && myjid=1
					jid="${myjid}"
				fi
				;;
			"virtualbox")
				. ${subrdir}/virtualbox.subr
				_state=$( ${VBOX_MGMT_CMD} showvminfo ${jname} | ${AWK_CMD} '/^State: /{print $2}' )
				if [ "${_state}" = "running" ]; then
					[ ${status} -ne 3 ] && status="1"	# if not in maintenance, update status to online
					myjid="1"
					jid="1"
				else
					[ ${status} -ne 3 ] && status="0"	# if not in maintenance, update status to offline
					myjid="0"
					jid="0"
				fi
				;;
			"xen")
				. ${subrdir}/xen.subr
				_state=$( ${XL_CMD} list ${jname} > /dev/null 2>&1 )
				if [ $? -eq 0 ]; then
					check_for_xen_process -j ${jname}
					status="1"	# if not in maintenance, update status to online
					myjid="${vm_pid}"
					jid="${myjid}"
					[ -z "${myjid}" ] && myjid=0 && status=0
					[ -z "${jid}" ] && jid=0 && status=0
				else
					status="0"	# if not in maintenance, update status to offline
					myjid="0"
					jid="0"
				fi
				;;
			"qemu")
				. ${subrdir}/qemu.subr
				if [ -r ${jailsysdir}/${jname}/qemu.pid ]; then
					read -r _test_pid= ${jailsysdir}/${jname}/qemu.pid
					if [ -n "${_test_pid}" ]; then
						${PS_CMD} -p ${_test_pid} > /dev/null 2>&1
						_ret=$?
						if [ ${_ret} -eq 0 ]; then
							status=1	# if not in maintenance, update status to online
							myjid="${_test_pid}"
							jid="${_test_pid}"
						else
							status="0"	# if not in maintenance, update status to offline
							myjid="0"
							jid="0"
						fi
					else
						status="0"	# if not in maintenance, update status to offline
						myjid="0"
						jid="0"
					fi
				else
					status="0"	# if not in maintenance, update status to offline
					myjid="0"
					jid="0"
				fi
				[ -z "${myjid}" ] && myjid=0 && status=0
				[ -z "${jid}" ] && jid=0 && status=0
				;;
		esac

		# check jid when sqlite information is wrong and update it
		if [ ${myjid} -ne ${jid} ]; then
			jid=${myjid}
			cbsdsqlrw ${dbdir}/local.sqlite "UPDATE jails SET jid='${myjid}' WHERE jname='${1}'"
		fi

		# fix for status only for 0,1, not for slave or maintenace
		if [ ${status} -eq 0 -o ${status} -eq 1 ]; then
			if [ ${myjid} -ne 0 -a ${status} -eq 0 ]; then
				status=1
				cbsdsqlrw ${dbdir}/local.sqlite "UPDATE jails SET status='1' WHERE jname='${1}'"
			fi
			if [ ${myjid} -eq 0 -a ${status} -ne 0 -a ${status} -ne 2 ]; then
				status=0
				cbsdsqlrw ${dbdir}/local.sqlite "UPDATE jails SET status='0' WHERE jname='${1}'"
			fi
		fi
	else
		# remote resource
		cbsdsqlro_vars "${_sqlfile}" "SELECT jid FROM jails WHERE jname='${jname}'" jid

		case ${jid} in
			0)
				status=0
				;;
			*)
				status=1
				;;
		esac
	fi

	# clean some variables if equal 0
	[ "${basename}" = "0" ] && unset basename
	[ "${slavenode}" = "0" ] && unset slavenode
	[ "${masterhost}" = "0" ] && unset masterhost
	[ "${exec_stop}" = "0" ] && unset exec_stop
	[ "${exec_poststart}" = "0" ] && unset exec_poststart
	[ "${exec_poststop}" = "0" ] && unset exec_poststop
	[ "${exec_prestart}" = "0" ] && unset exec_prestart
	[ "${exec_prestop}" = "0" ] && unset exec_prestop

	case "${emulator}" in
		bhyve|xen|qemu)
			init_emulator_rcconf ${1}
			;;
	esac
}

###
fi

init_rcconf ${jname} ${sqlfile}
