if [ ! "$_CBSD_RCTL_SUBR" ]; then
_CBSD_RCTL_SUBR=1
###

#v10.0.2
# this is a temporary wrapper for version 9.2.2 is intended to make the transition to sqlite3 version if rc.conf more painless
# required:
# strings.subr
#

# init_rctlconf ( $jname must be not empty )
# ( $sqlfile - specify sqlfile in dbdir for searching data. If empty - local file is prefered )
init_rctlconf()
{
	local _A= _ALLCOL= _i= _sqlfile= _datafile="local"

	[ -n "${2}" ] && _datafile="${2}"
	_sqlfile="${dbdir}/${_datafile}.sqlite"

	[ ! -f "${_sqlfile}" ] && return 0

	. "${distsharedir}/rctl.conf"

	#sets to default
	for _i in ${MYCOL}; do
		[ "${_i}" = "jname" ] && continue
		eval ${_i}=0
	done

	_ALLCOL=$( echo "${MYCOL}" | ${TR_CMD} " " "," )

	cbsdsqlro_vars "${_sqlfile}" "SELECT ${_ALLCOL} FROM rctl WHERE jname='$1'"
	return 0
}

init_rctlconf "${jname}" "${sqlfile}"

###
fi
