if [ ! "$_CBSD_STRINGS_SUBR" ]; then
_CBSD_STRINGS_SUBR=1
###

# sqllist "this|is|  it" a b c
# echo $a
# sqllistdelimer for "|" alternative delimer
sqllist()
{
	local _i _str IFS _key _T

	_str="$1"
	if [ -n "${sqllistdelimer}" ]; then
		IFS="${sqllistdelimer}"
	else
		IFS="|"
	fi
	_i=2

	for _key in ${_str}; do
		eval _T=\${${_i}}
		_i=$((_i + 1))
		export ${_T}="${_key}"
	done
}

conv_status()
{
	case "${status}" in
		0)
			status="Off"
			;;
		1)
			status="On"
			;;
		2)
			status="Slave"
			;;
		3)
			status="Maintenance"
			;;
		*)
			status="Unknown"
		;;
	esac
}

# return 0 when '-b XX' is included in '-a YY'
# mystr="one two three"
# 1)
# e=$( show_match -a "${mystr}" -b "two" )
# echo $e
# 2)
# if show_match -a "${mystr}" -b "two"; then
#   echo "matched"
# fi
show_match()
{
	local _a= _b= _i= _j=
	local _list= _match=0

	while getopts "a:b:" opt; do
		case "${opt}" in
			a) _a="${OPTARG}" ;;
			b) _b="${OPTARG}" ;;
		esac
		shift $(($OPTIND - 1))
	done

	for _i in ${_a}; do
		_match=0
			for _j in ${_b}; do
				if [ "${_i}" = "${_j}" ]; then
					if [ -z "${_list}" ]; then
						_list="${_i}"
					else
						_list="${_list} ${_i}"
					fi
					break
				fi
			done
	done

	if [ -n "${_list}" ]; then
		echo "${_list}"
		return 0
	else
		return 1
	fi
}

###
fi
