if [ ! "$_CBSD_TIME_SUBR" ]; then
_CBSD_TIME_SUBR=1
###

# convert seconds to human readable time
displaytime()
{
	local T=$1
	local D=$((T/60/60/24))
	local H=$((T/60/60%24))
	local M=$((T/60%60))
	local S=$((T%60))
	[ ${D} -gt 0 ] && printf '%d days ' $D
	[ $H -gt 0 ] && printf '%d hours ' $H
	[ $M -gt 0 ] && printf '%d minutes ' $M
	[ $D -gt 0 -o $H -gt 0 -o $M -gt 0 ] && printf 'and '
	printf '%d seconds\n' $S
}


# st_time should exist
time_stats()
{
	local _diff_time= _end_time=

	[ -z "${st_time}" ] && return 0

	gettime _end_time

	_diff_time=$(( _end_time - st_time ))

	if [ ${_diff_time} -gt 5 ]; then
		_diff_time_color="${W1_COLOR}"
	else
		_diff_time_color="${H1_COLOR}"
	fi

	capture _diff_time displaytime ${_diff_time}

	_abs_diff_time=$(( _end_time - FULL_ST_TIME ))
	capture _abs_diff_time displaytime ${_abs_diff_time}

	# promstat here

	[ "${quiet}" = "1" ] && return 0
	${ECHO} "${*} ${N2_COLOR}in ${_diff_time_COLOR}${_diff_time}${N2_COLOR} ( absolute: ${W1_COLOR}${_abs_diff_time} ${N2_COLOR})${N0_COLOR}" 1>&2
}

###
fi
