#!/bin/sh
#v9.0.0
# return 0 - not in NC pool range
# return 1 - all ok
# return 2 - ip already in use
globalconf="${workdir}/cbsd.conf";
# check = 0 - do not check on local interface
# check = 1 - check for local interface
# check = 2 - do not check for pool
MYARG="ip check"
MYOPTARG=""
MYDESC="Check for IP exist or in pool"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${tools}
init $*

CL_RANGE=`/bin/echo ${ip} |/usr/bin/tr "/" " "`
CL_IP=`/bin/echo ${CL_RANGE} |/usr/bin/awk {'printf $1'}`
INNET=0

## skip it when check =2
if [ $check -ne 2 ]; then

for IPPOOL in ${nodeippool}; do
NC_RANGE=`/bin/echo ${IPPOOL} |/usr/bin/tr "/" " "`
cbsd netmask ${NC_RANGE} ${CL_IP} > /dev/null 2>&1
res=$?

if [ ${res} -eq 1 ]; then
INNET=$((INNET + 1))
fi

done

if [ ${check} -eq 0 ]; then
[ ${INNET} -gt 0 ] || err 0 "Not in pool"
err 1 "Ip Ok"
fi

fi
### end skip check=2

#/usr/sbin/arp -d ${CL_IP} > /dev/null 2>&1
#/sbin/ping -t2 -c1 ${CL_IP} > /dev/null 2>&1
#arp -an |/usr/bin/grep "(${CL_IP})" |grep "incomplete" > /dev/null 2>&1

#return 0 errcode for undefined type
#return 1 errcode for ipv4
#return 2 errcode for ipv6
iptype ${CL_IP}
case $? in
1)
    ping -t1 -i1 -c1 -S ${CL_IP} ${CL_IP} > /dev/null 2>&1
    [ $? -eq 1 ] || err 2 "Ip4 in use"
    err 1 "IP4 OK"
    ;;
2)
    ping6 -i1 -c1 -S ${CL_IP} ${CL_IP} > /dev/null 2>&1
    [ $? -eq 1 ] || err 2 "Ip6 in use"
    err 1 "IP6 OK"
    ;;
esac

err 0 "Unknown IP check error"
