#!/bin/sh
#v9.1.0
globalconf="${workdir}/cbsd.conf";
MYARG="listfile destdir baseroot"
MYOPTARG=""
MYDESC="Make minibase by listing"
ADDHELP="listfile = ascii file with list of file\n\
destdir = destination directory\n\
baseroot = usr directory for source file and lib"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${initenv}
. ${tools}
init $*


MROOT=`dirname $0`
FILES="$1"
#FILES="${MROOT}/files.txt"
#BASEROOT="/usr/jails/basejail/base_amd64_9_1"
DSTDIR="/tmp/minicbsd"
LABEL="CBSDMINI"
ISO="/tmp/minicbsd.iso"
KERNEL="/root/boot/kernel/kernel"

make_mtree()
{
mtree -deU -f ${BASEROOT}/etc/mtree/BSD.root.dist -p ${DSTDIR} >/dev/null
mtree -deU -f ${BASEROOT}/etc/mtree/BSD.usr.dist -p ${DSTDIR}/usr >/dev/null
mtree -deU -f ${BASEROOT}/etc/mtree/BSD.var.dist -p ${DSTDIR}/var >/dev/null
mtree -deU -f ${BASEROOT}/etc/mtree/BIND.chroot.dist -p ${DSTDIR}/var/named >/dev/null
}

make_libmap()
{
A=`mktemp /tmp/libtxt.XXX`
B=`mktemp /tmp/libtxtsort.XXX`
trap "rm -f ${A} ${B}" 0 1 2 3 4 5

cat ${FILES} |while read line; do
    [ -z "${line}" -o `echo ${line} |grep -n ^#` ] && continue
    ldd -f "%p\n" ${BASEROOT}${line} >> $A 2>/dev/null
done

sort -u ${A} > ${B}
}

copy_binlib()
{
cat ${FILES}| while read line; do
    [ -z "${line}" -o `echo ${line} |grep -n ^#` ] && continue
    D=`chroot ${BASEROOT} dirname ${line}`
#    rsync --stats -axzvl --numeric-ids --delete --relative  
    cp -al ${BASEROOT}${line} ${DSTDIR}${D}
    A=`readlink ${BASEROOT}${line}`
    [ -n "${A}" -a -f "${D}/${A}" ] && {
	echo "SYM: $A"
	cp -al ${D}/${A} ${DSTDIR}${D}
	}
done

cat ${B}| while read line; do
    [ -z "${line}" ] && continue
    D=`chroot ${BASEROOT} dirname ${line}`
#    rsync --stats -axzvl --numeric-ids --delete --relative ${BASEROOT}${line} ${DSTDIR}
    cp -al ${BASEROOT}${line} ${DSTDIR}${D}

done
}

prepare_dir()
{
cat > ${DSTDIR}/boot/loader.conf << EOF
tmpfs_load="YES"
#geom_uzip_load="YES"
#rootfs_load="YES"
#rootfs_type="mfs_root"
#rootfs_name="/boot/mfsroot.gz"
#vfs.root.mountfrom="ufs:/dev/ufs/ROOTFS"
EOF

cp -rP ${BASEROOT}/etc ${DSTDIR}/

cat > ${DSTDIR}/etc/fstab << EOF
/dev/iso9660/${LABEL} / cd9660 ro 0 0
tmpfs /tmp tmpfs rw 0 0
tmpfs /var tmpfs rw 0 0
EOF

cat > ${DSTDIR}/etc/rc.conf << EOF
hostname="minicbsd"
EOF
}

makeisofs()
{
cp ${KERNEL} ${DSTDIR}/boot/kernel
cd ${DSTDIR}/boot/kernel
gzip -f -9 kernel
cd /
bootable="-o bootimage=i386;$4/boot/cdboot -o no-emul-boot"
/usr/sbin/makefs -t cd9660 $bootable -o rockridge -o label=$LABEL $ISO $DSTDIR
}


[ -f "${FILES}" ] || { echo "No file ${FILES}"; exit; }

chflags -R noschg ${DSTDIR} && rm -rf ${DSTDIR}
mkdir ${DSTDIR}
make_mtree
make_libmap
copy_binlib
prepare_dir
makeisofs
