#!/bin/sh
MYDESC="Detect host emulation"

if [ "$1" = "--help" ]; then
    echo $MYDESC
    exit
fi

case "$(kenv smbios.system.product)" in
VirtualBox)
  echo "emulation: VIRTUALBOX"
  exit 0
  ;;
VMware*)
  echo "emulation: VMWARE"
  exit 0
  ;;
*)
  echo "emulation: NO"
  exit 1
  ;;
esac
