#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="jname update quiet all"
MYDESC="Return or update node for jail"
ADDHELP="jname1 [jname2] - return node array\n\
update=1 for re-generate file\n\
quiet=1 - no jailname before node ip\n\
all=1 - list all jails\n"

[ -f "${globalconf}" ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

update()
{
TEMPMAP="/tmp/jmap.$$"
trap "rm -f ${TEMPMAP}" 0 1 2

# Get all jaillist from node
cbsd jls alljails=1 shownode=1 |grep On$ |awk {'printf $1" "$2"\n"'} > ${TEMPMAP}
truncate -s0 ${jailmapdb}
# and sort them into par=val form
for i in `cat ${TEMPMAP} |awk {'printf $2"\n"'}`; do
    A=`grep " $i$" ${TEMPMAP}| awk {'printf $1" "'}`
    echo $i=\"$A\" >>${jailmapdb}
    sed -i '' 's/ \"/\"/' ${jailmapdb}
done
sort -u ${jailmapdb} > ${TEMPMAP} && mv ${TEMPMAP} ${jailmapdb}
}

[ -z "$1" ] && err 1 "Give me args"
[ "${update}" = "1" ] && update && exit
[ -f "$jailmapdb" ] || err 1 "No map file, run update=1 first"

if [ "$all" = "1" ]; then

    if [ "${quiet}" = "1" ]; then
	cut -d "=" -f1 ${jailmapdb}
    else
	cat ${jailmapdb}
    fi
exit
fi

. ${jailmapdb}

for i in $*; do
    eval node=\"\$${i}\"
    [ -z "${node}" -o "${i}" = "quiet=1" ] && break
	if [ "${quiet}" = "1" ]; then
	    echo "${node}"
	else
	    echo "$i: ${node}"
	fi
done
