#!/bin/sh
#v9.1.0
globalconf="${workdir}/cbsd.conf";
MYARG="jname fqdn ips vnet"
MYOPTARG="ver basename baserw srcmount portsmount astart oninterface vnet applytpl floatresolv arch inter"
MYDESC="jail create by shell args"
ADDHELP="inter=0 to prevent any questions and to accept answers by default\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
init $*

gen_newjail_conf()
{
DT=`date "+%Y%m%d_%H_%M"`
TMPFILE="${ftmpdir}/${DT}-${jname}.jconf"
data="${jaildatadir}/${jname}-${jaildatapref}"
rootdir="${jaildir}/${jname}"
fstab="${jailfstabdir}/${jailfstabpref}${jname}"
rcconf="${jailrcconfdir}/rc.conf_${jname}"


cat > ${TMPFILE} << EOF
jname="${jname}";
path="${rootdir}";
host_hostname="${fqdn}";
ip4_addr="${ips}";
mount_devfs="1";
allow_mount="1";
allow_devfs="0";
allow_nullfs="0";
mount_fstab="${fstab}";
arch="${arch}";
mkhostsfile="1";
devfs_ruleset="4";
EOF

if [ $oninterface -eq 1 ]; then
A=`cbsd getnics-by-ip ip=$ips`
if [ -n "${A}" ]; then

cat >> ${TMPFILE} << EOF
interface="${A}";
EOF
fi
fi

cat >> ${TMPFILE} << EOF
ver="${ver}";
basename="${basename}";
slavenode="";
baserw="$baserw";
basename="$basename";
srcmount="$srcmount";
objmount="$objmount";
portsmount="$portsmount";
astart="$astart";
data="${data}";
vnet_interface="$vnet";
applytpl="${applytpl}";
rcconf="${jailrcconfdir}/rc.conf_${jname}";
floatresolv="${floatresolv}";
exec_start="/bin/sh /etc/rc";
exec_stop="/bin/sh /etc/rc.shutdown";

exec_poststart="";
exec_poststop="";
exec_prestart="";
exec_prestop="";

exec_master_poststart="";
exec_master_poststop="";
exec_master_prestart="";
exec_master_prestop="";

EOF


getyesno "Do you want to create jail immediately?"
[ $? -eq 1 -o $? -eq 3 ] && err 0 "You can make now: cbsd jcreate jconf=${TMPFILE}"
cbsd jcreate jconf=${TMPFILE}
[ $? -ne 0 ] && err 1 "Config file for jconf: ${TMPFILE}"
return 0
}

#### [ MAIN AREA ] ####
if [ ! -f ${localcbsdconf} ]; then
err 1 "no such conf file"
fi
. ${localcbsdconf}

#defaults
. $buildconf

[ -z "${baserw}" ] && baserw=0
[ -z "${srcmount}" ] && srcmount=0
[ -z "${portsmount}" ] && portsmount=1
[ -z "${astart}" ] && astart=1
[ -z "${oninterface}" ] && oninterface=1
[ -z "${vnet}" ] && vnet=0
[ -z "${applytpl}" ] && applytpl=1
[ -z "${floatresolv}" ] && floatresolv=1

gen_newjail_conf
