#!/bin/sh
globalconf="${workdir}/cbsd.conf";
GENUMARG=0
MYNUMARG=$#
MYDESC="Collect and store inventory information"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${tools}
. ${inventory}

init ${1}

ncpu=`/sbin/sysctl -n hw.ncpu`
physmem=$((`/sbin/sysctl -n hw.realmem` / 1048576))
disks=`/sbin/sysctl -n kern.disks|tr " " ","`
ifaces=`cbsd nics-list | xargs|tr " " ","`

modconf ${inventory} jail_interface "${ifaces}"
modconf ${inventory} ncpu "${ncpu}"
modconf ${inventory} physmem "${physmem}"
modconf ${inventory} disks "${disks}"

cbsd inventorysql --dbfile=${dbdir}/inv.${nodename} --action=update --param=jail_interface --value=${ifaces}
cbsd inventorysql --dbfile=${dbdir}/inv.${nodename} --action=update --param=ncpu --value=${ncpu}
cbsd inventorysql --dbfile=${dbdir}/inv.${nodename} --action=update --param=physmem --value=${physmem}
cbsd inventorysql --dbfile=${dbdir}/inv.${nodename} --action=update --param=disks --value=${disks}
