#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
MYARG="jroot fstab"
MYOPTARG=""
MYDESC="Mount jail by fstab file"
ADDHELP="jroot - root of jail, fstab - fstab file\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

SYSMNT=`/sbin/mount |grep " on " |awk {'printf $3" "'}`
[ -f "${fstab}" ] || err 1 "${fstab} does not exist"
[ -d "${jroot}" ] || err 1 "${jroot} does not exist"

cat ${fstab} | while read _device _mountpt _fs _mode _a _b; do
case ":${_device}" in
:#* | :)
continue
;;
*)
A=`echo ${_device} |grep ^/`
if [ ! -z "${A}" ]; then
	if [ ! -d "${_device}" ]; then
	echo "No source dir ${_device} in fstab" > "${fstab}.err"
	fi
fi
;;
esac

done

if [ -f "${fstab}.err" ]; then
A=`cat ${fstab}.err`
rm -f "${fstab}.err"
err 1 "${A}"
fi

cat ${fstab} | while read _device _mountpt _fs _mode _a _b; do
case ":${_device}" in
:#* | :)
continue
;;
esac

mnt=0
for _MNT in ${SYSMNT}; do
    if [ "${_MNT}" = "${jroot}${_mountpt}" ]; then
    echo "${jroot}${_mountpt} already mounted"
    mnt=1
    fi
done

if [ ${mnt} -eq 0 ]; then
    [ ! -d "${jroot}${_mountpt}" ] && mkdir -p ${jroot}${_mountpt}
    [ ! -d "${jroot}${_mountpt}" ] && echo "Warning: Can't create ${jroot}${_mountpt} - permission problem ?"
    /sbin/mount -t ${_fs} -o${_mode} ${_device} ${jroot}${_mountpt}
fi
done
