#!/bin/sh
#v9.1.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG=""
MYDESC="Enable NAT service for RFC1918 Networks"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
init $*

case "${nat_enable}" in
"ipnat")
    [ -f "${etcdir}/ipnat.rules" ] || err 1 "No ipnat.rules. run cbsd natcfg first"
    kldstat -qm pf || kldload pf
    kldstat -qm ipl  || kldload ipl
    kldstat -qm ipfilter || kldload ipfilter
    ping -c1 -S ${natip} 127.0.0.1 > /dev/null 2>&1 || err 1 "Cant assign nat address ${natip}. Probably wrong ip. Nat cfg skipped"
    ipnat -CF -f ${etcdir}/ipnat.rules
;;
"ipfw")
    [ -f "${etcdir}/ipfw.rules" ] || err 1 "No ipfw.rules. run cbsd natcfg first"
    kldstat -qm alias || kldload libalias
    kldstat -qm ipfw_nat || kldload ipfw_nat
    service ipnat onestop
    /sbin/ipfw delete 65000
    ping -c1 -S ${natip} 127.0.0.1 > /dev/null 2>&1 || err 1 "Cant assign nat address ${natip}. Probably wrong ip. Nat cfg skipped"
    sh ${etcdir}/ipfw.rules
;;
esac
