#!/bin/sh
#v9.0.0.
globalconf="${workdir}/cbsd.conf";
MYDESC="List of object file"
MYARG=""
MYOPTARG=""

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

ls -1 ${srcdir} |grep ^obj
