#!/bin/sh
#v9.1.0
globalconf="${workdir}/cbsd.conf";
MYARG="action"
# action=list,get,put
# source=src,obj,base,kernel,img
MYOPTARG="mode arch ver sources name basename stable"
#mode=check,update,upgrade
MYDESC="Working with CBSD Repository"
ADDHELP="action can be: list, get, put
sources can be: src, obj, base, kernel, img\n
mode can be: check, update, upgrade, quiet\n\
stable=1 for RELENG_X\n\
ver=any for mode=list for show all version (no for cur. version only\n\
arch=any for mode=list for show all arch (no for cur. arch only\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
init $*

fetchme()
{
cbsd cfetch -u $1 -o ${TF}
return $?
}

checkmd5()
{
DIR=$1
GOOD=0

for i in `find ${DIR} -type f -depth 1 -name *.md5 -print`; do
FILE=`echo $i |sed 's/\.md5//g'`
OMD5=`cat ${FILE}.md5`
RMD5=`md5 -q ${FILE}`
if [ "${RMD5}" != "${OMD5}" ]; then
    GOOD=$((GOOD + 1))
fi
done

return $GOOD
}



REPO=`cbsd getinfo -q repo`
checkrepo()
{
if [ -z $1 ]; then
printf "Check for repository: ${REPO} ..."
fi

if fetchme "${REPO}/cbsd.index" >/dev/null 2>&1; then
    cat ${TF}
else
    echo "Offline"
exit
fi
}


getsrc()
{
if [ -d "${srcdir}/${DIR}" ]; then
    [ $UPGRADE -eq 1 ] || err 1 "You already have ${ver}"
    cbsd removesrc ver=${ver}
fi


MIRROR="${REPO}/src_${ver}/mirror.html"

cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1

if [ $? -eq 0 ]; then
    REPO=`cat ${TF}`
    echo "Found new mirror for ${ver}: ${REPO}"
fi

cbsd cfetch -o ${MYDIR}/src.txz -u ${REPO}/${DIR}/src.txz
[ $? -eq 0 ] || err 1 "No such files in repo"
cbsd cfetch -o ${MYDIR}/src.txz.md5 -u ${REPO}/${DIR}/src.txz.md5 >/dev/null 2>&1
[ $? -eq 0 ] || err 1 "No such md5 files in repo"

[ -d "${MYDIR}" ] || err 1 "No source dir"

if checkmd5 ${MYDIR}; then
    echo "MD5sum correct."
	else
    err 1 "MD5sum incorrect."
fi

ARCHIVE="${workdir}/tmp/src_${ver}.txz"
[ ! -f "${ARCHIVE}" ] || rm -f ${ARCHIVE}

echo "Extracting..."
cd $workdir/tmp
tar xfz ${MYDIR}/src.txz
rm -f ${MYDIR}/src.txz
mkdir -p ${srcdir}/src_${ver}
mv ${workdir}/tmp/src_${ver} ${srcdir}/
echo "Done..."
DT=`/bin/date "+%Y%m%d"`
#nc -U ${workdir}/tmp/cbsd.sock  << EOF
#update src_${ver} ${DT}
#EOF
}

getbase()
{
if [ -z "${basename}" ]; then
    BDIR="${basejailpref}_${arch}_${ver}"
else
    BDIR="${basejailpref}_${basename}_${arch}_${ver}"
fi

DST="${basejaildir}/${BDIR}"
MIRROR="http://ftp.freebsd.org"
BSDBASE_DISTSITE="$MIRROR/pub/FreeBSD/releases/${arch}/${arch}/${ver}-RELEASE/base.txz"

if [ -d "${DST}" ]; then
    [ $UPGRADE -eq 1 ] || err 1 "You already have ${ver}"
    cbsd removebase ver=${ver} arch=${arch}
fi

if [ "$fbsdrepo" = "1" -a -z "${basename}" ]; then
    ## Official fbsd repo
    printf "Looking for official FreeBSD mirror.."
    ARCHIVE="$MYDIR/base.txz"
    cbsd cfetch -u ${BSDBASE_DISTSITE} -o ${ARCHIVE}
    if [ $? -eq 0 ]; then
	printf "\nExtracting base...\n"
	mkdir $DST
	cd $DST
	tar xfz ${ARCHIVE}
	rm -f ${ARCHIVE}
	BSDBASE_DISTSITE="$MIRROR/pub/FreeBSD/releases/${arch}/${arch}/${ver}-RELEASE/lib32.txz"
	ARCHIVE="$MYDIR/lib32.txz"
	cbsd cfetch -u ${BSDBASE_DISTSITE} -o ${ARCHIVE}
	    if [ $? -eq 0 ]; then
		printf "\nExtracting lib32...\n"
		cd $DST
		tar xfz ${ARCHIVE}
		rm -f ${ARCHIVE}
	    else
		printf "Lib32 not found\n"
	    fi
	cbsd preparebase dst=${DST}
	echo "Done..."
	return 0
    fi

    printf "Not found\n"
    ### Official fbsd repo end ###
fi

if [ -z "${basename}" ]; then
        MIRROR="${REPO}/base_${arch}_${ver}/mirror.html";
    else
        MIRROR="${REPO}/base_${basename}_${arch}_${ver}/mirror.html";
fi

cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1

if [ $? -eq 0 ]; then
    REPO=`cat ${TF}`
    echo "Found new mirror for ${basename}: ${REPO}"
fi

if [ -z "${basename}" ]; then
    cbsd cfetch -o ${MYDIR}/base_${arch}_${ver}.txz -u ${REPO}/${DIR}/base_${arch}_${ver}.txz
    [ $? -eq 0 ] || err 1 "No such files in repo"
    cbsd cfetch -o ${MYDIR}/base_${arch}_${ver}.txz.md5 -u ${REPO}/${DIR}/base_${arch}_${ver}.txz.md5 >/dev/null 2>&1
    [ $? -eq 0 ] || err 1 "No such md5 files in repo"
else
    cbsd cfetch -o ${MYDIR}/base_${basename}_${arch}_${ver}.txz -u ${REPO}/${DIR}/base_${basename}_${arch}_${ver}.txz
    [ $? -eq 0 ] || err 1 "No such files in repo"
    cbsd cfetch -o ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5 -u ${REPO}/${DIR}/base_${basename}_${arch}_${ver}.txz.md5 >/dev/null 2>&1
    [ $? -eq 0 ] || err 1 "No such md5 files in repo"
fi

if checkmd5 ${MYDIR}; then
echo "MD5sum correct."
    else
err 1 "MD5sum incorrect."
fi

if [ -z "${basename}" ]; then
    rm -f  ${MYDIR}/base_${arch}_${ver}.txz.md5
else
    rm -f ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5
fi

echo "Extracting..."
[ -d "$basejaildir" ] | mkdir -p ${basejaildir}
#/base_${arch}_${ver}
cd $basejaildir
#/base_${arch}_${ver}

if [ -z "${basename}" ]; then
    tar xfz ${MYDIR}/base_${arch}_${ver}.txz
    rm -f ${MYDIR}/base_${arch}_${ver}.txz.md5
else
    tar xfz ${MYDIR}/base_${basename}_${arch}_${ver}.txz
    rm -f ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5
fi

echo "Done..."
return 0
}


getobj()
{
if [ -z "${basename}" ]; then
    DST="${srcdir}/obj_${arch}_${ver}"
else
    DST="${srcdir}/obj_${basename}_${arch}_${ver}"
fi


if [ -z "${basename}" ]; then
        MIRROR="${REPO}/obj_${arch}_${ver}";
    else
        MIRROR="${REPO}/obj_${basename}_${arch}_${ver}";
fi

if [ -d "${DST}" ]; then
    [ $UPGRADE -eq 1 ] || err 1 "You already have ${ver}"
    cbsd removeobj ver=${ver} arch=${arch}
fi

cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1

if [ $? -eq 0 ]; then
    REPO=`cat ${TF}`
    echo "Found new mirror for ${basename}: ${REPO}"
fi

cbsd cfetch -o ${MYDIR}/obj_${arch}_${ver}.txz -u ${REPO}/${DIR}/obj_${arch}_${ver}.txz
[ $? -eq 0 ] || err 1 "No such files in repo"
cbsd cfetch -o ${MYDIR}/obj_${arch}_${ver}.txz.md5 -u ${REPO}/${DIR}/obj_${arch}_${ver}.md5 >/dev/null 2>&1
[ $? -eq 0 ] || err 1 "No such md5 files in repo"

if checkmd5 ${MYDIR}; then
echo "MD5sum correct."
    else
err 1 "MD5sum incorrect."
exit
fi

rm -f ${MYDIR}/obj_${arch}_${ver}.txz.md5

echo "Extracting..."
cd $srcdir
tar xfz ${MYDIR}/obj_${arch}_${ver}.txz
rm -f ${MYDIR}/obj_${arch}_${ver}.txz
echo "Done..."
#DT=`/bin/date "+%Y%m%d"`
#nc -U ${workdir}/tmp/cbsd.sock  << EOF
#update obj_${ver} ${DT}
#EOF
}


getkernel()
{
[ -z "${name}" ] && name="GENERIC"
DST="${basejaildir}/kernel_${name}_${arch}_${ver}"

if [ -d "${DST}" ]; then
    [ $UPGRADE -eq 1 ] || err 1 "You already have kernel ${name} for ${ver} "
    cbsd removekernel ver=${ver} arch=${arch} name=${name}
fi

MIRROR="${REPO}/kernel_${name}_${arch}_${ver}/mirror.html"

cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1

if [ $? -eq 0 ]; then
    REPO=`cat ${TF}`
    echo "Found new mirror for ${name}: ${REPO}"
fi

cbsd cfetch -o ${MYDIR}/kernel_${name}_${arch}_${ver}.txz -u ${REPO}/${DIR}/kernel_${name}_${arch}_${ver}.txz
[ $? -eq 0 ] || err 1 "No such files in repo"
cbsd cfetch -o ${MYDIR}/kernel_${name}_${arch}_${ver}.txz.md5 -u ${REPO}/${DIR}/kernel_${name}_${arch}_${ver}.md5 >/dev/null 2>&1
[ $? -eq 0 ] || err 1 "No such md5 files in repo"

if checkmd5 ${MYDIR}; then
echo "MD5sum correct."
    else
err 1 "MD5sum incorrect."
exit
fi

rm -f ${MYDIR}/kernel_${name}_${arch}_${ver}.txz.md5

echo "Extracting..."
cd $basejaildir
tar xfz ${MYDIR}/kernel_${name}_${arch}_${ver}.txz
rm -f ${MYDIR}/kernel_${name}_${arch}_${ver}.txz
echo "Done..."
}


getimg()
{
DST="${importdir}/${name}.img"
[ ! -f "${DST}" ] || err 1 "You already have ${DST}"

JAILRCCONF="${jailrcconfdir}/rc.conf_${name}"
[ ! -f  ${JAILRCCONF} ] || err 1 "You already have installed jail ${name}"

MIRROR="${REPO}/img_${arch}_${ver}_${name}/mirror.html"

cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1

if [ $? -eq 0 ]; then
    REPO=`cat ${TF}`
    echo "Found new mirror for ${name}: ${REPO}"
fi

echo "Fetching ${name}..."
cbsd cfetch -o ${DST} -u ${REPO}/${DIR}
[ $? -eq 0 ] || err 1 "No such remote file or network problem"
echo "Done... Importing..."
cbsd jimport jname=${name}
}

#### MAIN ####
UPGRADE=0
QUIET=0
TF="${ftmpdir}/test.$$"
MYDIR="${workdir}/tmp/src.$$"

[ -z "${action}" ] && err 1 "Give me action"

case "${mode}" in
    "upgrade") UPGRADE=1;;
    "quiet") QUIET=1;;
esac

case "${action}" in
"ping")
    if [ $QUIET -eq 1 ]; then
	checkrepo quiet
    else
	checkrepo
    fi
;;
"list")
if fetchme "${REPO}/${sources}ls" >/dev/null 2>&1; then
	echo "Available sources:"
	if [ "${ver}" = "any" ]; then
	    ver="[[:alnum:]]"
	else 
	    [ -z "${ver}" ] && ver=`/sbin/sysctl -n kern.osrelease|cut -d "-" -f1 |tr "." "_"`
	fi
	if [ "${arch}" = "any" ]; then
	    arch="[[:alnum:]]"
	else
	    [ -z "${arch}" ] && arch=`/sbin/sysctl -n hw.machine_arch`
	fi

#	    echo grep -E ${arch}_${ver} ${TF}
	    grep -E ${arch}_${ver} ${TF}
#rm -f ${TF}
fi
;;
"get")
. $buildconf
[ -z "${sources}" ] && err 1 "Give me sources"

case "${sources}" in
"src")
    DIR="src_${ver}"; 
    DST="${srcdir}/src_${ver}"
    LOCKFILE=${DST}.lock
    makelock ${LOCKFILE} "rm -f ${TF}; rm -rf ${MYDIR}" safe
    mkdir -p ${MYDIR}
    getsrc ;;
"base")
    if [ -z "${basename}" ]; then
	DIR="base_${arch}_${ver}"; 
    else
	DIR="base_${basename}_${arch}_${ver}"; 
    fi
    SRC="${srcdir}/src_${ver}"
    LOCKFILE=${SRC}.lock
    makelock $LOCKFILE "rm -f ${TF}; rm -rf ${MYDIR}" safe
    mkdir -p ${MYDIR}
    getbase ;;
"obj")
    if [ -z "${basename}" ]; then
	DIR="obj_${arch}_${ver}";
    else
	DIR="obj_${basename}_${arch}_${ver}";
    fi

    SRC="${srcdir}/src_${ver}"
    LOCKFILE=${SRC}.lock
    makelock $LOCKFILE "rm -f ${TF}; rm -rf ${MYDIR}" safe
    mkdir -p ${MYDIR}
    getobj ;;
"kernel")
    [ -z "${name}" ] && name="GENERIC"
    DIR="kernel_${name}_${arch}_${ver}"
    SRC="${srcdir}/src_${ver}"
    LOCKFILE=${SRC}.lock
    makelock $LOCKFILE "rm -f ${TF}; rm -rf ${MYDIR}" safe
    mkdir -p ${MYDIR}
    getkernel ;;
"img")
    [ -z "${name}" ] && err 1 "Give me name"
    DIR="img_${arch}_${ver}_${name}/${name}.img"
    LOCKFILE="${jaildir}/${name}.lock"
    makelock ${LOCKFILE} "rm -f ${TF}; rm -rf ${MYDIR}"
    mkdir -p ${MYDIR}
    getimg ;;
esac ## END of source case

esac ## END of action case
