#!/bin/sh

jname="cbsd_test_jstart"

oneTimeSetUp() {
    cbsd jdestroy jname="${jname}"
}

setUp() {
    cbsd jcreate runasap=0 jname="${jname}"
}

tearDown() {
    cbsd jdestroy jname="${jname}"
}

test_jstart(){
    cbsd jstart jname="${jname}"
    _test=$(jexec "${jname}" whoami)
    assertEquals "${_test}" "root"
}


# https://github.com/cbsd/cbsd/issues/649
test_issue649_1() {
    cbsd jset jname="${jname}" hostname="one"
    _test=$(cbsd jget jname="${jname}" hostname)
    assertEquals "one" "${_test}"

    cbsd jstart jname="${jname}"
    cbsd jset jname="${jname}" hostname="two"
    cbsd jrestart jname="${jname}"
    _test=$(cbsd jget jname="${jname}" hostname)
    assertEquals "two" "${_test}"
}

test_issue649_2() {
    cbsd jstart jname="${jname}"
    cbsd jexec jname="${jname}" sysrc hostname="lollipop"
    cbsd jstop jname="${jname}"
    cbsd jstart jname="${jname}"
    _test=$(cbsd jexec jname="${jname}" hostname)
    assertEquals "${_test}" "lollipop"
}

. shunit2
