#!/bin/sh

ALL_TESTS=$( find /usr/local/cbsd/tests/ -type f -name cbsd\*.sh )

for i in ${ALL_TESTS}; do
	echo "--- ${i} ---"
	${i}
	ret=$?
	if [ ${ret} -ne 0 ]; then
		echo "FAILED: ${i}"
		exit ${ret}
	fi
done

exit 0
