#!/bin/sh
#v9.1.0
globalconf="${workdir}/cbsd.conf";
MYARG="jname"
MYOPTARG="mode"
MYDESC="Configure for jail"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

shift  # todo: jname and cmd may have reverse order

JAILRCCONF="${jailrcconfdir}/rc.conf_${jname}"
[ -f  ${JAILRCCONF} ] || err 1 "no conf rc.conf file for jail"
. ${JAILRCCONF}

CMDDIR="${jailsysdir}/${jname}/bin/"

if [ "${mode}" = "list" ]; then
    echo "Config command available:"
    [ -d "${CMDDIR}" ] && ls -1 ${CMDDIR}
    exit
fi

[ -z "${cmd}" ] && cmd=${1}
[ -n "${cmd}" ] || err 1 "Empty command"

shift
cfgargs="$@"

[ -f "${CMDDIR}/${cmd}" ] || err 1 "No such cmd: ${cmd}"

. ${CMDDIR}${cmd}

myconf ${cfgargs}
