#!/bin/sh
#v9.1.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="jname mode editor"
MYDESC="Show or modify jail description"
ADDHELP="mode=update for update information\n\
jname - specify jname\n\
editor=mcedit for altrnative editor\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

showall()
{

for j in `cd ${jailsysdir} && ls -1`; do

cbsd jstatus $j > /dev/null 2>&1
[ $? -eq 0 ] && continue
echo "$j {"
cbsd jdescr jname=$j
echo "}"
done
exit
}


[ -f ${sharedir}/jail-arg ] || err 1 "no jail-arg file";
. ${sharedir}/jail-arg

[ -z "${editor}" ] && editor="vi"

[ -z "${jname}" ] && {
    showall
    exit
}

JAILRCCONF="${jailrcconfdir}/rc.conf_${jname}"

[ -f  "${JAILRCCONF}" ] || err 1 "no conf rc.conf file for jail"
. ${JAILRCCONF}
SYSDIR="${jailsysdir}/${jname}"
PDESCR="${SYSDIR}/${jname}-descr"

if [ "${mode}" = "update" ]; then
    echo "edit description"
    [ ! -d "${SYSDIR}" ] && mkdir -p ${SYSDIR}
    ${editor} "${PDESCR}"
else
    [ -f "${PDESCR}" ] || err 1 "No such jail descr file"
    cat ${PDESCR}
fi
