#!/bin/sh
#v9.1.0
globalconf="${workdir}/cbsd.conf";
# jailget <jname> param param ...
# -q -quiet
MYARG="jname"
MYOPTARG="update"
MYDESC="Generate jail package list"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

[ -f ${sharedir}/jail-arg ] || err 1 "no jail-arg file";
. ${sharedir}/jail-arg

JAILRCCONF="${jailrcconfdir}/rc.conf_${jname}"

[ -f  "${JAILRCCONF}" ] || err 1 "no conf rc.conf file for jail"
. ${JAILRCCONF}

PINFO="${jailsysdir}/${jname}/${jname}-pkg_info"

if [ -n "${update}" ]; then
    JAILDBDIR="${jaildatadir}/${jname}-${jaildatapref}/var/db/pkg"
    [ -d "${JAILDBDIR}" ] || err 1 "No such pkgdb dir in jail"
    [ ! -d "${jailsysdir}/${jname}" ] && mkdir -p ${jailsysdir}/${jname}
    env PKG_DBDIR="${JAILDBDIR}" /usr/sbin/pkg info > ${PINFO}
    err 0 "Updated"
else
    [ -f "${PINFO}" ] || err 1 "No such jail pkg_info file"
    cat ${PINFO}
fi
