#!/bin/sh
#v9.1.0
globalconf="${workdir}/cbsd.conf";

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${settingstui}

MYARG="jname"
MYOPTARG="${JARG} outfile"

[ ! -f "${sharedir}/jail-arg" ] && {
    echo "No such jail-arg skel"
    exit 1
}
. ${sharedir}/jail-arg
MYOPTARG="${JARG}"
MYDESC="Ncurses based setup for jail-arg"

init $*

commit()
{
for i in ${JARG}; do
    eval VAL=\$$i
    [ -n "${VAL}" -a "${i}" != "jname" ] && cbsd jset mode=quiet jname=${jname} $i=\"${VAL}\"
done

exit
}


mainmenu()
{
COUNT=


for i in ${JARG}; do
    eval VAL=\$$i
    [ -n "${VAL}" -a "${i}" != "jname" ] && {
    eval ${i}=`cbsd jget mode=quiet jname=${jname} ${VAL}`
    COUNT=$((COUNT + 1))
}
done

COUNT=$((COUNT+3))

while [ 1 ]; do

MENU_OPTIONS=

for i in ${JARG}; do
    eval VAL=\$$i
    [ -n "${VAL}" -a "${i}" != "jname" ] && {
    MENU_OPTIONS="${MENU_OPTIONS} $i ${VAL}"
}
done

$DIALOG --clear --title "Setup for ${jname}" \
--menu "\n\
select action for ${jname}:" -1 70 ${COUNT} \
        ${MENU_OPTIONS} \
	"COMMIT" "Save changes and quit" \
        "EXIT" "EXIT!" 2> ${TMPFILE}
retval=$?

choice=`cat ${TMPFILE}`
rm -f ${TMPFILE}
case $retval in
    0)
    [ $choice = "jname" ] && get_jname
    [ $choice = "fqdn" ] && get_jail_fqdn
    [ $choice = "ip4_addr" ] && get_jail_ips
    [ $choice = "ver" ] && get_jail_base
    [ $choice = "baserw" ] && get_jail_baserw
    [ $choice = "srcmount" ] && get_jail_srcmount
    [ $choice = "portsmount" ] && get_jail_portsmount
    [ $choice = "astart" ] && get_jail_astart
    [ $choice = "interface" ] && get_jail_oninterface
    [ $choice = "vnet" ] && get_jail_vnet
    [ $choice = "applytpl" ] && get_jail_applytpl
    [ $choice = "floatresolv" ] && get_jail_floatresolv
    [ $choice = "arch" ] && get_jail_arch
    [ $choice = "COMMIT" ] && commit
    [ $choice = "EXIT" ] && exit
;;
*)	exit;;
esac
done
}





### MAIN

JAILRCCONF="${jailrcconfdir}/rc.conf_${jname}"
[ ! -f  ${JAILRCCONF} ] && err 1 "no conf rc.conf file for ${jname}"

mainmenu
