msg_repo="Browse CBSD Repository"
msg_repo_bases="CBSD FreeBSD Base Repository"
msg_repo_kernels="CBSD FreeBSD Kernel Repository"
msg_repo_images="CBSD FreeBSD Jail Repository"

msg_show_remote_images="Pre-configured FreeBSD Jails"
msg_show_remote_bases="FreeBSD bases"
msg_show_remote_kernel="FreeBSD kernel"

hline_arrows_tab_enter="Press arrows, TAB or ENTER"

msg_exit="Exit"
msg_select="Select"
