{
 "title": "CBSD Jail cluster",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pool",
    "label": "Pool:",
    "query": {
     "query": "label_values(cbsd_pool_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "current pool: jails up",
   "type": "stat",
   "description": "Shows total number of all jails in  in state \"up\".\n\nSee `http://vmagent-host:8429/targets` to get list of all targets. \n",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jails_up:{instance=\"$pool\"})",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "current pool: jails down",
   "type": "stat",
   "description": "Shows total number of all configured jails in state \"down\".\n\nSee `http://vmagent-host:8429/targets` to get list of all targets. \n",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jails_down:{instance=\"$pool\"})",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "cluster: jails up",
   "type": "stat",
   "description": "Shows total number of all jails in  in state \"up\".\n\nSee `http://vmagent-host:8429/targets` to get list of all targets. \n",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(jails_up:)", "legendFormat": "up" }
   ]
  },
  {
   "title": "clusters: jails down",
   "type": "stat",
   "description": "Shows total number of all configured jails in state \"down\".\n\nSee `http://vmagent-host:8429/targets` to get list of all targets. \n",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(jails_down:)", "legendFormat": "up" }
   ]
  },
  {
   "title": "Uptime",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "sort((time() - vm_app_start_timestamp{instance=~\"vmagent1.convectix.com:9429\"}) or (up{instance=~\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(sum(14) by (job, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "pcpu",
   "type": "timeseries",
   "description": "jail cpu usage",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "jail_pcpu{instance=\"$pool\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "memoryuse",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "jail_memoryuse{instance=\"$pool\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{name}} "
    }
   ]
  },
  {
   "title": "disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "jail_readiops{instance=\"$pool\"}",
     "legendFormat": "{{name}} read"
    },
    {
     "expr": "jail_writeiops{instance=\"$pool\"}",
     "legendFormat": "{{name}} write"
    }
   ]
  },
  {
   "title": "disk bps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "jail_readbps{instance=\"$pool\"}",
     "legendFormat": "{{name}}-read"
    },
    {
     "expr": "jail_writebps{instance=\"$pool\"}",
     "legendFormat": "{{name}}-write "
    }
   ]
  },
  {
   "title": "processes",
   "type": "timeseries",
   "description": "max proc",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jail_maxproc{instance=\"$pool\"}",
     "legendFormat": "{{name}} "
    }
   ]
  }
 ]
}