#!/bin/sh
#v9.2.2
globalconf="${workdir}/cbsd.conf";
MYARG="jname"
MYOPTARG="mode"
MYDESC="Configure for jail"
ADDHELP="mode=list for list of jails external command\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${color}
. ${strings}
. ${inventory}
init $*

shift  # todo: jname and cmd may have reverse order

. ${jrcconf}
[ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"

CMDDIR="${jailsysdir}/${jname}/bin/"

if [ "${mode}" = "list" ]; then
    ${ECHO} "${MAGENTA}Configure command available: ${GREEN}jconfig jname=${jname} <cmd>:${NORMAL}"
    [ -d "${CMDDIR}" ] && find ${CMDDIR} -type f -depth 1 -maxdepth 1 -exec basename {} \;
    exit
fi

vimage=""
[ -z "${cmd}" ] && cmd=${1}
[ "${vnet}" ] && vimage="vnet"

shift
cfgargs="$@"

if [ -z "${cmd}" ]; then
    cbsd jsetup-tui jname=${jname} host_hostname ip4_addr mount_devfs allow_mount allow_devfs allow_nullfs mkhostsfile devfs_ruleset ver baserw mount_src mount_ports astart applytpl floatresolv interface ${vimage}
elif [ -f "${CMDDIR}${cmd}" ]; then
    . ${CMDDIR}${cmd}
    myconf ${cfgargs}
fi
