#!/bin/sh
#v9.2.1
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="jname mode editor"
MYDESC="Show or modify jail description"
ADDHELP="mode=update for update information\n\
jname - specify jname\n\
editor=mcedit for altrnative editor\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${color}

init $*

showall()
{
    local _j

    for _j in `cd ${jailsysdir} && ls -1`; do
	cbsd jstatus ${_j} > /dev/null 2>&1
	[ $? -eq 0 ] && continue
	${ECHO} "${BOLD}${_j} {${NORMAL}"
	    cbsd jdescr jname=${_j}
	    ${ECHO} "${BOLD}}${NORMAL}"
    done
}

[ -z "${editor}" ] && editor="vi"

if [ -z "${jname}" ]; then
    showall
    exit
fi

JAILRCCONF="${jailrcconfdir}/rc.conf_${jname}"

[ ! -f  "${JAILRCCONF}" ] && err 1 "${MAGENTA}no conf rc.conf file for jail: ${GREEN}${jname}${NORMAL}"

. ${JAILRCCONF}

SYSDIR="${jailsysdir}/${jname}"
PDESCR="${SYSDIR}/descr"

if [ "${mode}" = "update" ]; then
    [ ! -d "${SYSDIR}" ] && mkdir -p ${SYSDIR}
    ${editor} "${PDESCR}"
else
    [ ! -f "${PDESCR}" ] && exit 0
    cat ${PDESCR}
fi
