#!/bin/sh
#v9.2.2
globalconf="${workdir}/cbsd.conf";
CBSDMODULE="jail"
MYARG="jname"
MYOPTARG="mode"
#mode=update
MYDESC="Update or view jail info"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${strings}
. ${color}
init $*

[ -f ${sharedir}/jail-arg ] || err 1 "no jail-arg file";
. ${sharedir}/jail-arg

[ -z "${jname}" ] && err 1 "Give me jname"
. ${jrcconf}
[ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"

INFO="${jailsysdir}/${jname}-info"

if [ "${mode}" = "update" ]; then
    if [ ! -f "${INFO}" ]; then
	cat > ${INFO} << EOF
JAILNAME=""
JAILVERSION=""
JAILDTVERSION=""
MASTER_SITES=""
MAINTAINER=""
ARCH=""
BASE=""
EOF
    fi
    vi ${INFO}
else
    [ -f "${INFO}" ] || err 1 "No such jail info file"
    cat ${INFO}
fi
