#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
MYARG="ip jname"
MYOPTARG=""
MYDESC="Clone jail to remote machine"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

[ -n "${ip}" ] || err 1 "Give me node"
[ -n "${jname}" ] || err 1 "Give me jail"

# all error on this stage is dangerouse, so break exec in any error
#set -e
printf "Rcloging"
cbsd j2prepare ip=${ip} jname=${jname} > $DEBLOG 2>&1
dot "j2prepare"
cbsd j2slave ip=${ip} jname=${jname} > $DEBLOG 2>&1
dot "j2slave"
err 0 "ok"
