#!/bin/sh
#v9.2.1
globalconf="${workdir}/cbsd.conf";
MYARG="ip jname"
MYOPTARG=""
MYDESC="Clone jail to remote machine"
CBSDMODULE="jail"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${color}

init $*

[ -z "${ip}" ] && err 1 "${MAGENTA}Give me node${NORMAL}"
[ -z "${jname}" ] && err 1 "${MAGENTA}Give me jail${NORMAL}"

# all error on this stage is dangerouse, so break exec in any error
#set -e
printf "${MAGENTA}jrcloning${NORMAL}"
cbsd j2prepare ip=${ip} jname=${jname} > $DEBLOG 2>&1
dot "j2prepare"
cbsd j2slave ip=${ip} jname=${jname} > $DEBLOG 2>&1
dot "j2slave"
err 0 "${GREEN}ok${NORMAL}"
