#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="jname"
MYDESC="Destroy jail"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${jfs}
init $*

if [ -n "$jname" ]; then
    JLIST=$jname
else
    JLIST=$*
fi

[ -n "$JLIST" ] || err 1 "Give me jname"

for jname in ${JLIST}; do

DST="${jaildatadir}/${jname}-${jaildatapref}"
JAILDIR="${jaildir}/${jname}"
JAILFSTAB="${jailfstabdir}/${jailfstabpref}${jname}"
JAILRCCONF="${jailrcconfdir}/rc.conf_${jname}"

ST=`cbsd jstatus jname=${jname}`
if [ $? -eq 0 ]; then
    echo "No such jail ${jname}"
    continue
fi
[ ${ST} -eq 0 ] || cbsd jstop jname=${jname}

[ -d "${DST}" ] && removedata ${DST}

# Slave die too
[ ! -d "${DST}.slave" ] || chflags -R noschg ${DST}.slave && rm -rf ${DST}.slave
[ ! -d ${JAILDIR} ] ||  chflags -R noschg ${JAILDIR} && rm -rf ${JAILDIR}
[ ! -f ${JAILFSTAB} ] || rm -f ${JAILFSTAB}
# Slave die too
[ ! -f ${JAILFSTAB}.slave ] || rm -f ${JAILFSTAB}.slave
[ ! -f ${JAILRCCONF} ] || rm -f ${JAILRCCONF}
# Slave die too
[ ! -f ${JAILRCCONF}.slave ] || rm -f ${JAILRCCONF}.slave
[ ! -d "${jailsysdir}/${jname}" ] || removedata "${jailsysdir}/${jname}"

done
