#!/bin/sh
#v9.2.0
globalconf="${workdir}/cbsd.conf";
MYARG="old new"
MYOPTARG="host_hostname ip4_addr"
MYDESC="Rename jail"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${tools}
. ${inventory}
. ${jfs}
init $*

[ -z "${old}" ] && err 1 "Give me old jname"
[ -z "${new}" ] && err 1 "Give me new jname"

DST="${jaildatadir}/${new}-${jaildatapref}"
SRC="${jaildatadir}/${old}-${jaildatapref}"
JAILDIR="${jaildir}/${new}"
JAILFSTAB="${jailfstabdir}/${jailfstabpref}${new}"
JAILFSTABORIG="${jailfstabdir}/${jailfstabpref}${old}"
JAILRCCONF="${jailrcconfdir}/rc.conf_${new}"
JAILRCCONFORIG="${jailrcconfdir}/rc.conf_${old}"
SYSDIROLD="${jailsysdir}/${old}"
SYSDIRNEW="${jailsysdir}/${new}"


[ -d "${SRC}" ] || err 1 "No jail data at ${SRC}"
[ ! -d "${DST}" ] || err 1 "${DST} jail already exist"

[ -d "${JAILDIR}" ] || mkdir -p ${JAILDIR}
[ -d "${jailfstab}"  ] || mkdir -p $jailfstabdir
[ -d "${jailrcconf}"  ] || mkdir -p $jailrcconfdir

ST=`cbsd jstatus jname=${old}`
[ $? -eq 0 ] && err 1 "No such jail"

[ ${ST} -ne 0 ] && err 1 "Jail is online. Please stop them"

printf "Rename"
cp ${JAILRCCONFORIG} ${JAILRCCONF}
dot "cp"
cp ${JAILFSTABORIG} ${JAILFSTAB}
dot "cp"
/usr/bin/sed "s/\/${old}/\/${new}/g" ${JAILFSTABORIG} > ${JAILFSTAB}
dot "sed"
/usr/bin/sed "s/_${old}_/_${new}_/g" ${JAILRCCONFORIG} > ${JAILRCCONF}
dot "sed"
modconf ${JAILRCCONF} jname ${new} > $DEBLOG 2>&1
dot "modconf"
cbsd jset jname=${new} path="${jaildir}/${new}" > $DEBLOG 2>&1
dot "jset rootdir"
cbsd jset jname=${new} mount_fstab="${jailfstabdir}/${jailfstabpref}${new}" > $DEBLOG 2>&1
dot "jset fstab"
cbsd jset jname=${new} data="${jaildatadir}/${new}-${jaildatapref}" > $DEBLOG 2>&1
dot "jset data"
cbsd jset jname=${new} rcconf="${jailrcconfdir}/rc.conf_${new}" > $DEBLOG 2>&1
dot "jset rcconf"

if [ -n "${host_hostname}" ]; then
    cbsd jset jname=${new} host_hostname=${host_hostname} rcconf="${jailrcconfdir}/rc.conf_${new}" > $DEBLOG 2>&1
    dot "jset rcconf hostname"
fi

if [ -n "${ip4_addr}" ]; then
    cbsd jset jname=${new} ip4_addr=${ip4_addr} rcconf="${jailrcconfdir}/rc.conf_${new}" > $DEBLOG 2>&1
    dot "jset rcconf ip4_addr"
fi

rm -f ${JAILRCCONFORIG} ${JAILFSTABORIG}
jname=${new}
mvdata ${SRC} ${DST}
dot "cp"

#rename zfs fs source
case $zfsfeat in
    1) . $zfstool
	zfsmnt ${DST}
	if [ $? -eq 2 -o $? -eq 1 ]; then
	    OLDPOOL=$ZPOOL
	    DATA=`zfs get -Ho value name ${jaildatadir}`
	    NEWPOOL="${DATA}/${new}"
	    zfs unmount -f ${SRC}
    	    sleep 5  #Hack - sometimes we got "cannot rename: dataset is busy"
    	    zfs unmount -f ${SRC} > /dev/null 2>&1
	    zfs rename ${OLDPOOL} ${NEWPOOL}
	    [ $? -eq 0 ] && zfs mount ${NEWPOOL} && rm -rf ${SRC}
	fi
    ;;
esac

[ -d "$SYSDIROLD" ] && mv $SYSDIROLD ${SYSDIRNEW}

removedata ${SRC}
err 0 "ok"
