#!/bin/sh
#v9.2.2
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="jname"
MYDESC="Return jail ID in output and jail existance as error code (0 -no jail, 1 - jail exist, 2 - slave)\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

getjid()
{
    local _errcode

    . ${JAILRCCONF}

    [ $baserw -eq 1 ] && path=$data

    get_jid
    echo "${myjid}"
    exit 1
}

[ -z "$jname" ] && jname=$1
JAILRCCONF="${jailrcconfdir}/rc.conf_${jname}"

if [ ! -f  "${JAILRCCONF}" ]; then
    if [ -f "${JAILRCCONF}.slave" ]; then
	errcode=2
    else
	errcode=0
    fi
    exit $errcode
fi

getjid

