#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="jname"
MYDESC="Return jail ID or status. exitcode=0 - no such jail"
ADDHELP="result in output - Jail ID (0 if not running). Error code 0 = no such jail, 1 -exist, 2 - slave\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

getjid()
{
. ${JAILRCCONF}
eval rootdir=\"\$jail_${jname}_rootdir\"
eval baserw=\"\$jail_${jname}_baserw\"
eval data=\"\$jail_${jname}_data\"
eval hostname=\"\$jail_${jname}_hostname\"
[ $baserw -eq 1 ] && rootdir=$data

get_jid
jid=$?
err 1 $jid
}

[ -z "$jname" ] && jname=$1
JAILRCCONF="${jailrcconfdir}/rc.conf_${jname}"

if [ ! -f  "${JAILRCCONF}" ]; then
    [ -f "${JAILRCCONF}.slave" ] && err 2 "0"
    err 0 "0"
fi

getjid

