#!/bin/sh
# v9.2.0
globalconf="${workdir}/cbsd.conf";
MYARG="jname"
MYOPTARG="dbfile mode"
MYDESC="Register jail records to SQLite from ASCii config or re-populate ASCii config from SQLite"
ADDHELP="mode= set (apply), unset, show (show current state) or get (show limits)\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${color}
init $*

JAILRCCONF="${jailrcconfdir}/rc.conf_${jname}"
[ -f  ${JAILRCCONF} ] || err 1 "${MAGENTA}no conf rc.conf file for jail: ${GREEN}${jname}${NORMAL}"
. ${JAILRCCONF}
[ -z "${dbfile}" ] && dbfile="${dbdir}/local.sqlite"
[ ! -f "${dbfile}" ] && err 1 "${MAGENTA}inventorydb not found. You must create them first via cbsd inventorysql: ${GREEN}${dbfile}${NORMAL}"

. ${sharedir}/jail-arg

delete_full()
{
    [ -z "${jname}" ] && return 0
    cbsd jailsql --dbfile=${dbdir}/local.sqlite --action=delete --param=${jname} > /dev/null 2>&1
}



#main
delete_full
