#!/bin/sh
# fetch http://pkgmir.pkg.freebsd.org/freebsd:11:x86:64/latest/packagesite.txz
#v10.0.3
globalconf="${workdir}/cbsd.conf"
CBSDMODULE="helpers"
MYARG="mode"
MYOPTARG="jname pkglist name repodir pkgconf chroot nomount"
MYDESC="cbsd pkg wrapper"
ADDHELP="jname= work in with jail\n\
pkglist= use package list from file\n\
name= name of pkg\n\
repodir= repository configuration directory\n\
pkgconf= specify pkg.conf to use for pkg\n\
nomount=1 do not mount/unmount jail fs\n\
mode=add,bootstrap,install,info,query,remove,update,upgrade\n"
EXTHELP="modules/pkg.d.html"

set -e
. ${globalconf}
set +e

. ${subr}
. ${inventory}
. ${strings}
. ${system}
init $*

#defines
_MYDIR=$( dirname `realpath $0` )
noname=0

set -e
	. ${_MYDIR}/pkg.subr
set +e

[ -n "${mode}" ] && shift
if [ -n "${nomount}" ]; then
	shift
	nomount=${nomount}
else
	nomount=0
fi

PKGARGS=""
TRAP=""
# for chroot/jail env
PKG_PRE=""

if [ -n "${jname}" ]; then
	. ${jrcconf}
	[ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
	[ $baserw -eq 1 ] && path=$data

	. ${workdir}/universe.subr
	readconf buildworld.conf
	init_target_arch
	init_srcdir
	init_basedir
	init_kerneldir

	[ ${jid} -eq 0 -a ${nomount} -eq 0 ] && prepare_jail
	PKG_PRE="/usr/sbin/chroot ${path}"
	shift
else
	path=""
fi

if [ -n "${pkglist}" ]; then
	[ ! -f "${pkglist}" ] && err 1 "${MAGENTA}No such file: ${GREEN}${pkglist}${NORMAL}"
	pkgtarget=$( /bin/cat ${pkglist} |/usr/bin/xargs )
else
	pkgtarget="$*"
fi

# init path and bootstrap pkg if necessary
init_path

[ -n "${repodir}" ] && PKGARGS="${PKGARGS} -R ${repodir}"
[ -n "${chroot}" ] && PKGARGS="${PKGARGS} -c ${chroot}"

case "${mode}" in
	bootstrap)
		[ -z "${jname}" ] && err 1 "${MAGENTA}bootstrap for jail only${NORMAL}"
		pkg_bootstrap
		;;
	install|add)
		pkg_install "${pkgtarget}"
		;;
	"remove")
		pkg_remove "${pkgtarget}"
		;;
	"info")
		pkg_info "${pkgtarget}"
		;;
	"query")
		pkg_query "${pkgtarget}"
		;;
	"update")
		pkg_update "${pkgtarget}"
		;;
	"upgrade")
		pkg_upgrade "${pkgtarget}"
		;;
	*)
		err 1 "${MAGENTA}Unknown mode${NORMAL}"
esac

