menu_list="
	'freebsd'	'FreeBSD-kernel based distros'		'FreeBSD, FreeNAS, pfSense, ZFSguru, kFreeBSD, ArchBSD and so on..'
	'linux'		'Linux-kernel based distros'		'Debian, Ubuntu, RHEL, Oracle and about 1024+ names ;-) also'
	'openbsd'	'OpenBSD-kernel based distros'		'OpenBSD-based guests'
	'netbsd'	'NetBSD-kernel based distros'		'NetBSD-based guests'
	'dflybsd'	'DragonFlyBSD-kernel based distros'	'DragonFlyBSD-based guests'
" # END-QUOTE
