#!/bin/sh
#v9.1.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="ver arch maxjobs clean basename stable distcc ccache"
MYDESC="Buildworld from sources"
ADDHELP="ver=head for current.\n\
stable=1 for RELENG_X\n\
distcc=1 - enable distcc\n\
ccache=1 - enable ccache\n"

set -e

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

. ${buildconf}
. ${distccacheconf}
. ${inventory}

if [ "${distcc}" = "1"  ]; then
    if ! distcc_check; then
	distcc=0
    fi
else
    distcc=0
fi

if [ "${ccache}" = "1"  ]; then

    ccache_prefix="cbsd buildworld $ver $arch $basename"
    ccache_dir="/var/cache/ccache"
    init_ccache_dir
    export CCACHE_DIR=$ccache_realdir

    if ! ccache_check; then
	ccache=0
    fi
else
    ccache=0
fi

SRC="${srcdir}/src_${ver}"
[ -d "${SRC}" ] || err 1 "No such version at ${SRCDIR}"
[ "${arch}" = "amd64" -o "${arch}" = "i386" ] || err 1 "Only amd64 or i386 arch supported"

if [ `uname -m` = "i386" -a "${arch}" = "amd64" ]; then
    err 1 "Cannot build amd64 on i386 hosts"
fi

truncate -s0 ${ftmpdir}/make.$$.conf

if [ -z "${basename}" ]; then
    [ -f "${etcdir}/make.conf" ] && origmakeconf="${etcdir}/make.conf"
else
    [ -f "${etcdir}/make-$basename.conf" ] && origmakeconf="${etcdir}/make-$basename.conf"
fi

export __MAKE_CONF=${ftmpdir}/make.$$.conf

[ $ccache -eq 1 -o $distcc -eq 1 ] && prepare_make_conf ${origmakeconf} ${__MAKE_CONF}

if [ -z "${basename}" ]; then
    export MAKEOBJDIRPREFIX=${srcdir}/obj_${arch}_${ver}
else
    export MAKEOBJDIRPREFIX=${srcdir}/obj_${basename}_${arch}_${ver}
fi

if [ -z "${basename}" ]; then
    export SRCCONF=${etcdir}/src.conf
else
    export SRCCONF=${etcdir}/src-${basename}.conf
fi

NUMJOBS=""
[ $maxjobs -eq 0 ] || NUMJOBS="-j${maxjobs}"

NOCLEANUP=""
[ ${clean} -eq 1 ] || NOCLEANUP="-DNO_CLEAN"

DST="${srcdir}/src_${ver}/src"
LOCKFILE=${ftmpdir}/src_${ver}.lock
makelock ${LOCKFILE} "rm -f ${ftmpdir}/make.$$.conf"

/usr/bin/make $NUMJOBS -C ${SRC}/src buildworld TARGET=${arch} ${NOCLEANUP}
