#!/bin/sh
# v9.2.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="ver stable rev svnbase dst"
MYDESC="CSUP from official cvsup server"
ADDHELP="ver=head for current.\n\
stable=1 for STABLE_X\n\
rev=XXX where XXX - svn revision\n\
svnbase - alt. svn base, default: svn://svn.freebsd.org/base\n\
dst - alternative dst dir\n"

set -e

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${color}

init $*

[ -f "/usr/local/bin/svn" ] || err 1 "${MAGENTA}No svn in the base. Please install subversion${NORMAL}"
[ -z "${svnbase}" ] && svnbase="svn://svn.freebsd.org/base"

. ${buildconf}

if [ "${stable}" = "1" ]; then
    SVN_URL="${svnbase}/stable/${ver}"
else
    SVN_URL="${svnbase}/releng/${ver}"
fi

[ -z "${dst}" ] && dst="${srcdir}/src_${ver}/src"

LOCKFILE=${ftmpdir}/src_`md5 -qs ${dst}`.lock
makelock ${LOCKFILE}

[ -d "${dst}" ] || /bin/mkdir -p ${dst}

[ "$ver" = "10.0" -o "${ver}" = "10" ] && SVN_URL="${svnbase}/head"

if [ -d "${dst}/.svn" ]; then
    cd ${dst}
    /usr/local/bin/svn upgrade > /dev/null 2>&1
    /usr/local/bin/svn cleanup > /dev/null 2>&1
fi

/usr/local/bin/svn checkout -r ${rev} ${SVN_URL} ${dst}

case "${ver}" in
"9")
    set +e
    [ -f "${distdir}/upgrade/patch/patch-9x-sys-sys-param.h" ] && cd ${dst}/sys/sys/ && patch --check -N < ${distdir}/upgrade/patch/patch-9x-sys-sys-param.h > /dev/null 2>&1
    [ $? -eq 0 ] && $ECHO "${MAGENTA}apply patch for: ${GREEN}MAXLOGNAME${NORMAL}" && patch < ${distdir}/upgrade/patch/patch-9x-sys-sys-param.h
    set -e
    # ---
#    ${ECHO} "${MAGENTA}apply patch for: ${GREEN}pr=180236${NORMAL}"
#    [ -f "${distdir}/upgrade/patch/patch-9x-sys-fs-nullfs-null_vnops.c" ] && cd ${dst}/sys/fs/nullfs && patch --check -N < ${distdir}/upgrade/patch/patch-9x-sys-fs-nullfs-null_vnops.c
#    [ $? -eq 0 ] && patch < ${distdir}/upgrade/patch/patch-9x-sys-fs-nullfs-null_vnops.c
    ;;
esac

if [ ! -f "${dst}/Makefile" ]; then
    rm -rf ${dst}
    err 1 "No source code for ${ver}"
fi


