#!/bin/sh
# v9.2.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="ver stable rev svnbase dst"
MYDESC="CSUP from official cvsup server"
ADDHELP="ver=head for current.\n\
stable=1 for RELENG_X\n\
rev=XXX where XXX - svn revision\n\
svnbase - alt. svn base, default: svn://svn.freebsd.org/base\n\
dst - alternative dst dir\n"

set -e

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

[ -z "${svnbase}" ] && svnbase="svn://svn.freebsd.org/base"
[ -f "/usr/local/bin/svn" ] || err 1 "No svn in base. Please install subversion"

. ${buildconf}

[ -z "${dst}" ] && dst="${srcdir}/src_${ver}/src"
LOCKFILE=${ftmpdir}/src_`md5 -qs ${dst}`_${ver}.lock
makelock ${LOCKFILE}

[ -d "${dst}" ] || /bin/mkdir -p ${dst}

if [ "$ver" = "10.0"  ]; then
    SVN_URL="${svnbase}/head"
else
    SVN_URL="${svnbase}/releng/${ver}"
fi

[ "${stable}" = "1" ] && SVN_URL="${svnbase}/stable/${ver}"

[ -d "${dst}/.svn" ] && /usr/local/bin/svn cleanup ${dst}
/usr/local/bin/svn checkout -r ${rev} ${SVN_URL} ${dst}

if [ -f "$dst/Makefile" ]; then
	return 0
else
    rm -rf ${dst}
    err 1 "No source code for ${ver}"
fi
