#!/bin/sh
#v10.0.3
globalconf="${workdir}/cbsd.conf";
CBSDMODULE="build"
MYARG=""
MYOPTARG="ver arch target_arch basename stable destdir"
MYDESC="Installbase from obj"
ADDHELP="ver=head for current.\n\
stable=1 for RELENG_X\n\
destdir= for alternative install path in root dir\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${color}
readconf buildworld.conf
. ${workdir}/universe.subr
init $*

# By default ver=current version
. ${buildconf}

init_distcc
init_notify
init_target_arch
init_srcdir
init_supported_arch
init_basedir

[ ! -d "${BASE_DIR}" ] && /bin/mkdir -p ${BASE_DIR}

LOCKFILE=${ftmpdir}/$( md5 -qs ${MAKEOBJDIRPREFIX} ).lock

makelock $LOCKFILE

/usr/bin/make -C ${SRC_DIR} installworld distribution DESTDIR=${BASE_DIR} TARGET=${arch} TARGET_ARCH=${arch}
[ $? -ne 0 ] && err 1 "${MAGENTA}Installworld error${NORMAL}"
cbsd preparebase dst=${BASE_DIR} emulator=${EMULATOR}
