#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="ver arch name"
MYDESC="Remove base dir"

set -e

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${system}

init $*

# By default ver=current version
[ -n "${ver}" ] || ver=`uname -r|cut -d "-" -f1 |tr "." "_"`
[ -n "${arch}" ] || arch=`uname -m`

SRC="${srcdir}/src_${ver}"
DST="${basejaildir}/${basejailpref}_${arch}_${ver}"

if [ -z "${name}" ]; then
    DST="${basejaildir}/${basejailpref}_${arch}_${ver}"
else
    DST="${basejaildir}/${basejailpref}_${name}_${arch}_${ver}"
fi

[ -d "${DST}" ] || err 1 "No such dir: $DST"

if  on_mounted "${DST}"; then
    err 1 "Current dir in use. Unmount first"
fi

LOCKFILE=${SRC}.lock
makelock $LOCKFILE
chflags -R noschg ${DST} && rm -rf ${DST}
