#!/bin/sh
#v9.2.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="ver stable"
MYDESC="Remove src-dir"
ADDHELP="ver=9_1 for 9.1 ver=. for current.\n\
stable=1 for RELENG_X\n"

set -e

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
init $*

. ${buildconf}

DST="${srcdir}/src_${ver}"

[ -d "${DST}" ] || err 1 "No such dir: ${DST}"

LOCKFILE=${DST}.lock
makelock $LOCKFILE
rm -rf ${DST}
