#!/bin/sh
#v9.2.1
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="tag pri"
MYDESC="Task management"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

TABSPATH="${crontabsdir}"
JOBNAME=`basename \`env TMPDIR=${TABSPATH} mktemp -q -t cbsd.nolog\``
echo $JOBNAME
chown ${cbsduser} ${TABSPATH}/${JOBNAME} && chmod 0600 ${TABSPATH}/${JOBNAME}
echo "* * * * * $* > ${TABSPATH}/${JOBNAME}.log 2>&1" > ${TABSPATH}/${JOBNAME}
