#!/bin/sh
#v9.2.0
globalconf="${workdir}/cbsd.conf";
CBSDMODULE="build"
MYARG=""
MYOPTARG="ver arch maxjobs clean basename stable distcc ccache notify"
MYDESC="Buildworld from sources + install world"
ADDHELP="ver=head for current.\n\
stable=1 for RELENG_X\n\
distcc=1 - enable distcc\n\
ccache=1 - enable ccache\n"

set -e
. ${globalconf}
set +e

. ${subr}
init $*

/usr/local/bin/cbsd buildworld $@ && /usr/local/bin/cbsd installworld $@

