.Dd January 10, 2013
.Dt cbsd 8
.Os
.Sh NAME
.Nm cbsd
.Nd FreeBSD jail management tools
.Sh SYNOPSIS
.Nm cbsd
.Op cmd
.Nm cbsd
.Op cmd
.Op param=val
.Nm cbsd
.Op --help
.Sh DESCRIPTION
All commands begin with
.Nm
prefix.
.Pp
The
.Nm
commands can accept arguments which are written in a "param=value" form.
.Nm
commands can have both obligatory arguments and arguments which can be lowered. 
To receive the list of arguments it is possible on command:
cbsd --help
.Pp
.Sh EXAMPLES
.Tp
Show list jails:
.Pp
.Nm Cm jls
.Pp
.Tp
Show help for jlogin command:
.Pp
.Nm Cm jlogin --help
.Pp
.Tp
Run DIALOG-based jail configuration tools:
.Pp
.Nm Cm jconstruct-tui
.Pp
.Sh EXIT STATUS
cbsd returns a zero exist status it it succeeds. Non zero is returned in case of failure or non-standart
conclusion, the codes of which is usually described in the --help parameter to a command.
.Sh SEE ALSO
.Xr jail 8
.Pp
WWW: http://www.bsdstore.ru
