#!/bin/sh
. /etc/rc.conf

workdir="${cbsd_workdir}"
globalconf="${workdir}/cbsd.conf";

[ -f "${globalconf}" ] || {
    echo "no globalconf file"
    exit 1
}

. ${globalconf}
. ${subr}

jails_stop()
{
for J in  `/bin/ls ${jailrcconfdir}`; do
. ${jailrcconfdir}/${J}

[ -z "${jname}" ] && continue
eval host_hostname=\"\$host_hostname\"
eval path=\"\$path\"
eval baserw=\"\$baserw\"
eval data=\"\$data\"
[ $baserw -eq 1 ] && path=$data

get_jid
jid=$?

[ ${jid} -ge 0 ] && {
    echo "Stopping ${jname} ..."
    /usr/local/bin/cbsd jstop ${jname}
}

done
}


jails_start()
{
for J in  `ls ${jailrcconfdir}`; do
    . ${jailrcconfdir}/${J}
    [  -z "${jname}" ] && continue
    eval astart=\"\$astart\"
    [ "$astart" -eq 1 ] && /usr/local/bin/cbsd jstart ${jname}
done
}


#### MAIN ####
case $1 in
start) jails_start ;;
stop) jails_stop ;;
esac

