#!/bin/sh
#v9.2.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="mode editor"
MYDESC="Show or modify node description"
ADDHELP="mode=update for update information\n\
editor=mcedit for altrnative editor\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}

init $*

[ -z "${editor}" ] && editor="vi"

if [ "${mode}" = "update" ]; then
    echo "edit description"
    ${editor} "${nodedescr}"
else
    [ -f "${nodedescr}" ] || err 1 "No such node descr file"
    cat ${nodedescr}
fi
