#!/bin/sh
#v9.2.2
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="node"
MYDESC="Login to remote node"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${color}
init $*

[ -z "${node}" ] && node=$1
[ -z "${node}" ] && err 1 "${MAGENTA}Empty node${NORMAL}"

shift
CMD="$@"

SSHOP=`cbsd nodesql --dbfile=${dbdir}/nodes.sqlite --action=sshopt --nodename=${node} 2>/dev/null`
IP=`cbsd nodesql --dbfile=${dbdir}/nodes.sqlite --action=get --nodename=${node} --param=ip 2>/dev/null`

[ -z "$SSHOP" -o -z "${IP}" ] && err 1 "${MAGENTA}No such node ${GREEN}${node}${MAGENTA} in database or have no ip/scpopt${NORMAL}"

if [ -n "${CMD}" ]; then
    su -m ${cbsduser} -c "/usr/bin/ssh ${SSHOP} -C \"${CMD}\""
else
    su -m ${cbsduser} -c "/usr/bin/ssh ${SSHOP}"
fi
