#!/bin/sh
globalconf="${workdir}/cbsd.conf";
GENUMARG=0
MYNUMARG=$#
MYDESC="Node to pinger"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init ${1}

TO="${ftmpdir}/pinnger.$$"
FROM="${ftmpdir}/nodes.$$"
NEW="${ftmpdir}/newnode.$$"

cbsd nodepingerls > ${TO}
cbsd nodels |cut -d "_" -f 2 |awk {'printf $1"\n"'}> ${FROM}

cat ${FROM} | while read ip; do
A=`grep $ip ${TO}`
if [ $? -eq 1 ]; then
nc -U ${tmpdir}/nodepinger.sock  << EOF
add ${ip}
EOF
fi
done

rm -f ${TO} ${FROM} ${NEW}
