#!/bin/sh
#v9.2.2
globalconf="${workdir}/cbsd.conf";
MYARG="node mode"
MYOPTARG="msg scr sql name"
MYDESC="MSG wrapper"
ADDHELP="mode can: list,exec,dele,send\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${color}
init $*

mail_list()
{
    find ${maildir}/local -depth 1 -maxdepth 1 -exec basename {} \;
}

exec_scr()
{
    [ ! -f "${maildir}/local/${name}" ] && err 1 "No such name"
    env workdir=${workdir} /usr/bin/su -m ${cbsduser} -c "exec ${maildir}/local/${name}"
}

#dele_scr()
#{
#    [ -f "${MYDIR}/${name}" ] && /usr/bin/su -m cbsd -c "rm -f ${MYDIR}/${name}"
#}

send_msg()
{
    local _scrname _ip

    _scrname="${nodename}-$$-`basename ${scr}`.sh"
    cbsd nodescp ${scr} ${node}:var/mail/local/${_scrname}

    if [ $? -ne 0 ]; then
	[ ! -d "${maildir}/${node}" ] && mkdir -p "${maildir}/${node}"
	cp ${scr} ${maildir}/${node}/${_scrname}
	_ip=`cbsd nodesql --dbfile=${dbdir}/nodes.sqlite --action=get --nodename=${node} --param=ip`
	daemon cbsd sendnodemsg -t ${nodename} -h ${_ip} yhm
    fi
}

case "${mode}" in
	"list")
	    [ ! -d "${MYDIR}" ] && return 0
	    mail_list
	    ;;
	"sendscr")
	    [ -z "${node}" ] && err 0 "${MAGENTA}Empty node${NORMAL}"
	    [ -z "${scr}" -o ! -f "${scr}" ] && err 0 "${MAGENTA}Scripts not found: ${GREEN}${scr}${NORMAL}"
	    send_msg
	    ;;
	"exec")
	    [ ! -d "${MYDIR}" ] && return 0
	    [ -z "${name}" ] && err 1 "Script name is necessary via name="
	    exec_scr
	    ;;
	"dele")
	    [ ! -d "${MYDIR}" ] && return 0
	    [ -z "${name}" ] && err 1 "Script name is necessary via name="
	    dele_scr
	    ;;
	*)
	    echo "Unknown mode"
	    ;;
esac
