#!/bin/sh
#v9.2.0
globalconf="${workdir}/cbsd.conf";
CBSDMODULE="node"
MYARG="md5name ip port pw"
MYOPTARG=""
MYDESC="Get rsa get from remote node"

set -e
. ${globalconf}
set +e

. ${subr}
init $*

LOCALKEY="${rsshdir}/${md5name}.id_rsa"
REMOTEKEY=".ssh/${md5name}.id_rsa"

cbsd cbsdsftp ${ip} ${port} ${cbsduser} ${pw} ${REMOTEKEY} ${LOCALKEY}
RESULT=$?

case ${RESULT} in
	0)
		chmod 0400 ${LOCALKEY}
		chown ${cbsduser}:${cbsduser} ${LOCALKEY}
		err 0 "${MAGENTA}Key has been added succesfull:${GREEN} ${LOCALKEY}${NORMAL}"
		;;
	1)
		err 1 "${MAGENTA}Bad user or password.${NORMAL}"
		;;
	2)
		err 2 "${MAGENTA}No such key on remote host:${GREEN} ${REMOTEKEY}${NORMAL}"
		;;
	*)
		err 3 "${MAGENTA}Unknown error.${NORMAL}"
		;;
esac
