#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
MYARG="node port pw"
MYOPTARG=""
MYDESC="Add remote node key"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${tools}
init $*

if iptype $node; then
    resolvhost ${node}
    node=$HST
fi

[ -n "${node}" ] || err 1 "Empty ip"

NODENAME=`cbsd cbsdssh $node $port $cbsduser $pw cbsd getinfo -q nodename`

case $? in
0)
[ -z "$NODENAME" ] && err 1 "No nodename found. Check remote cbsd settings"
echo "$node has nodename ${NODENAME}"
;;
1)
err 1 "Connection problem with $node"
;;
2)
err 1 "Bad password or system user"
;;
esac

MD5NAME=`md5 -qs ${NODENAME}`
cbsd nodeaddkey md5name=${MD5NAME} ip=${node} port=${port} pw=${pw} > $DEBLOG 2>&1

case $? in
0)
echo "${node} Added successfull"

LOCALKEY="${rsshdir}/${MD5NAME}.id_rsa"
modconf ${rsshdir}/${NODENAME}.node SSHKEY $LOCALKEY
modconf ${rsshdir}/${NODENAME}.node IP $node
modconf ${rsshdir}/${NODENAME}.node PORT $port

;;
1)
    cat ${DEBLOG}
    err 1 "Error: Bad password" ;;
2)
    cat ${DEBLOG}
    err 1 "Error: No key found or wrong hostname. Make initenv on remote machine" ;;
*)
    cat ${DEBLOG}
    err 1 "Error: Unkown error" ;;
esac
