#!/bin/sh
#v9.2.1
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG=""
MYDESC="get put file to remove nodes\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${tools}
. ${color}
init $*

getnode()
{
    local _t

    _t=`echo ${1} |grep ":"`

    [ $? -ne 0 ] && return 1

    node=${1%%:*}
    rfile=${1##*:}

}

[ $# -ne 2 ] && err 1 "${MAGENTA}$0 host1:remotefile1 localfile1 [ localfile2 host2@:remotefile2 ]${NORMAL}"

node=""
rfile=""
rarg=0

if getnode $1; then
    if getnode $2; then
	err 1 "${MAGENTA}Only one remote path${NORMAL}"
    fi
    rarg=1
else
    if getnode $2; then
	rarg=2
    fi
fi

[ -z "${node}" -o -z "${rfile}" ] && err 1 "${MAGENTA}remove path via node:path records not determine${NORMAL}"

SCPOP=`cbsd nodesql --dbfile=${dbdir}/nodes.sqlite --action=scpopt --nodename=${node} 2>/dev/null`
SSHOP=`cbsd nodesql --dbfile=${dbdir}/nodes.sqlite --action=sshopt --nodename=${node} 2>/dev/null`
IP=`cbsd nodesql --dbfile=${dbdir}/nodes.sqlite --action=get --nodename=${node} --param=ip 2>/dev/null`

[ -z "$SCPOP" -o -z "${IP}" ] && err 1 "${MAGENTA}No such node ${GREEN}${node}${MAGENTA} in database or have no ip/scpopt${NORMAL}"

if [ $rarg -eq 1 ]; then
    DIR=`dirname ${2}`
    [ ! -d "${DIR}" ] && mkdir -p ${DIR}
    /usr/bin/lockf -s -t0 ${ftmpdir}/sftp_${IP}.lock scp ${SCPOP} -r ${cbsduser}@${IP}:${rfile} ${2}
else
    DIR=`dirname ${rfile}`
    /usr/bin/lockf -s -t0 ${ftmpdir}/sftp_${IP}.lock ssh $SSHOP -l ${cbsduser} <<EOF
[ ! -d "${DIR}" ] && mkdir -p "${DIR}"
EOF
    /usr/bin/lockf -s -t0 ${ftmpdir}/sftp_${IP}.lock scp ${SCPOP} -r ${1} ${cbsduser}@${IP}:${rfile}
fi
