#!/bin/sh
cat > /etc/network/interfaces<<EOF
# manager by tiny-cloud + CBSD backend
auto lo
iface lo inet loopback

iface eth0 inet static
        address %%ci_ip4_addr%%
        gateway %%ci_gw4%%

EOF

/sbin/ifdown eth0
/sbin/ifup eth0
