# Copyright (c) 2026 The FreeBSD Foundation
#
# SPDX-License-Identifier: BSD-2-Clause
#
# This file was written by Alfonso Sabato Siciliano <asiciliano@FreeBSD.org>
# under sponsorship from the FreeBSD Foundation.

### bsddialog theme - Wed Apr  8 00:15:07 2026

## Settings
# Available colors: black, red, green, yellow, blue, magenta, cyan, white.
# Available attributes: bold, reverse, underline, blink, halfbright, highlight.
# Prefix f_* indicates the focused state of an element, whether selected or not.

version 1.2-wip

# Terminal
theme.screen.color white blue bold

# Shadow
theme.shadow.color black black
# shift down right from main widget
theme.shadow.y 1
theme.shadow.x 2

# Main widget
theme.dialog.color black white
theme.dialog.delimtitle true
theme.dialog.titlecolor blue white bold
theme.dialog.lineraisecolor black white
theme.dialog.linelowercolor black white
theme.dialog.bottomtitlecolor black white bold
theme.dialog.arrowcolor blue white

# Menus: --checklist, --menu, --radiolist
# prefix [selector] shortcut name desc bottomdesc
theme.menu.f_prefixcolor black white
theme.menu.prefixcolor black white
theme.menu.f_selectorcolor white blue
theme.menu.selectorcolor black white
theme.menu.f_namecolor white blue
theme.menu.namecolor blue white
theme.menu.f_desccolor white blue
theme.menu.desccolor black white
theme.menu.f_shortcutcolor yellow blue
theme.menu.shortcutcolor yellow white
theme.menu.bottomdesccolor white blue
# bsddialog_menutype BSDDIALOG_SEPARATOR
theme.menu.sepnamecolor yellow white
theme.menu.sepdesccolor yellow white

# Forms
theme.form.f_fieldcolor white blue bold
theme.form.fieldcolor white cyan bold
theme.form.readonlycolor cyan white bold
theme.form.bottomdesccolor white blue

# Bar of --gauge, --mixedgauge, --pause, --rangebox
theme.bar.f_color white blue bold
theme.bar.color blue white bold

# Spinbox of --calendar, --datebox, --timebox
theme.spinbox.f_color white blue
theme.spinbox.color black white

# Buttons
theme.button.minmargin 1
theme.button.maxmargin 5
theme.button.leftdelim [
theme.button.rightdelim ]
theme.button.f_delimcolor white blue bold
theme.button.delimcolor black white
theme.button.f_color white blue bold
theme.button.color black white
theme.button.f_shortcutcolor cyan blue bold underline
theme.button.shortcutcolor blue white bold underline
