# srcup config for HardenedBSD platform
GITBASE="https://github.com/hardenedbsd/hardenedbsd-stable"
#SCM_GIT_BRANCH="hardened/11-stable/master"
checkout_method="git"

# extra git flags
#git_flags=
git_flags="--depth=1"
