# don't remove this line:
vm_profile="GhostBSD-26-x86_64"
vm_os_type="freebsd"
# this is one-string additional info strings in dialogue menu
long_description="GhostBSD: 26.01"

# fetch area:
fetch=1

# Official resources to fetch ISO's releases:
iso_site="\
https://soft41.ru/get/soft/system/distros/bsd/GhostBSD/26.1/ \
https://download.fr.ghostbsd.org/releases/amd64/26.1-R15.0p2/ \
https://download.ghostbsd.org/releases/amd64/26.1-R15.0p2/ \
https://download.za.ghostbsd.org/releases/amd64/26.1-R15.0p2/ \
https://ftp.icm.edu.pl/pub/BSD/ghostbsd/releases/amd64/26.1-R15.0p2/ \
https://ftp.hanmesoft.com/BSD/GhostBSD/release/amd64/26.1/ \
"

# Official CBSD project mirrors ( info: https://github.com/cbsd/mirrors )
cbsd_iso_mirrors="https://mirror.convectix.com/iso/ https://raw.githubusercontent.com/cbsd/mirrors/refs/heads/main/cbsd-iso.txt"

iso_img="GhostBSD-26.1-R15.0p2.iso"

# register_iso as:
register_iso_name="cbsd-iso-GhostBSD-26.1-R15.0p2"
register_iso_as="iso-GhostBSD-26.1-R15.0p2"

default_jailname="ghost"

# https://ghostbsd-documentation-portal.readthedocs.io/en/latest/user/installation-guide/getting-started.html#system-requirements
vm_ram="8g"
imgsize_min="15g"

# disable profile?
xen_active=1
bhyve_active=1
qemu_active=1

# Available in ClonOS?
clonos_active=1

# VNC
vm_vnc_port="0"
vm_efi="uefi"
xhci=1
tablet=0

vm_package="small1"

sha256sum="ff6c4df357df412d3b0c87e054204682b7c13e0cb90bcf61dcda58528a4f948e"
iso_img_dist_size="4652670976"

# VirtualBox Area
virtualbox_ostype="FreeBSD_64"

# enable birtio RNG interface?
virtio_rnd="1"

# default boot firmware
cd_boot_firmware="bhyve"
hdd_boot_firmware="bhyve"
