# don't remove this line:
vm_profile="ZorinOS-Core-18-x86_64"
vm_os_type="linux"
# this is one-string additional info strings in dialogue menu
long_description="ZorinOS: Core 18"

# custom settings:
fetch=1

# Official resources to fetch ISO's
iso_site="\
https://mirror.metanet.ch/zorinos/18/ \
https://mirror.umd.edu/zorin/18/ \
https://mirrors.edge.kernel.org/zorinos-isos/18/ \
https://plug-mirror.rcac.purdue.edu/zorin-iso/18/ \
https://mirror.webworld.ie/zorinos/18/ \
https://ftp.rnl.tecnico.ulisboa.pt/pub/zorinos/18/ \
https://ftp.lysator.liu.se/pub/zorinos/isos/18/ \
https://mirror.meowsmp.net/zorinos/18/ \
https://ftpmirror2.infania.net/mirror/zorinos/isos/18/ \
https://mirror.freedif.org/zorin/18/ \
https://distro.ibiblio.org/zorinos/18/ \
"

# Official CBSD project mirrors ( info: https://github.com/cbsd/mirrors )
cbsd_iso_mirrors="https://mirror.convectix.com/iso/ https://raw.githubusercontent.com/cbsd/mirrors/refs/heads/main/cbsd-iso.txt"

iso_img="Zorin-OS-18-Core-64-bit-r3.iso"

# register_iso as:
register_iso_name="cbsd-iso-zorinos-18-core-64-r3.iso"
register_iso_as="iso-zorinos-18-core-64-r3"

default_jailname="zorin"

vm_package="small1"

# https://help.zorin.com/docs/getting-started/system-requirements/
vm_ram="2g"
imgsize="16g"
imgsize_min="15g"

virtio_type="virtio-blk"
# on virtio, Debian installer staled/freezed on Detecting HW stage
#virtio_type="ahci-hd"

# VNC
vm_vnc_port="0"
vm_efi="uefi"

# disable profile?
xen_active=1
bhyve_active=1
qemu_active=1

# Available in ClonOS?
clonos_active=1

sha256sum="09959ce793b8a065b70207e46cd646b1de805fc7e0bad925ce28df6e04b7f807"
iso_img_dist_size="127295461"

# enable birtio RNG interface?
virtio_rnd="1"

cd_boot_firmware="bhyve"
hdd_boot_firmware="bhyve"
