# don't remove this line:
vm_profile="cloud-Minikube-x86_64"
vm_os_type="linux"
# this is one-string additional info strings in dialogue menu
long_description="Minikube: Debian-based, v1.35.1 (cloud)"

# fetch area:
fetch=1

# Official resources to fetch ISO's
iso_site="https://mirror.convectix.com/cloud/"

# Official CBSD project mirrors ( info: https://github.com/cbsd/mirrors )
cbsd_iso_mirrors="https://mirror.convectix.com/cloud/ https://raw.githubusercontent.com/cbsd/mirrors/refs/heads/main/cbsd-cloud.txt"

iso_img="Minikube-x86-0.1.raw"
iso_img_dist="Minikube-x86-0.1.raw.xz"

sha256sum="346ce43d854c9767d60098955dcdd8b60f70cf7292a5e2d1c32a4b7fb6611cf7"
iso_img_dist_size="2234837364"

# enp0sX
ci_adjust_inteface_helper=1

iso_img_type="cloud"

iso_extract="nice -n 19 ${IDLE_IONICE} ${XZ_CMD} -d ${iso_img_dist}"

# register_iso as:
register_iso_name="cbsd-cloud-Minikube-x86-1.0.raw"
register_iso_as="cloud-Minikube-x86-1.0"

default_jailname="minikube"

# disable profile?
xen_active=1
bhyve_active=1
qemu_active=1

# Available in ClonOS?
clonos_active=1

# Available for MyB? image name
myb_image="minikube"

# VNC
vm_vnc_port="0"
vm_efi="uefi"

vm_package="small1"

# VirtualBox Area
virtualbox_ostype="FreeBSD_64"

# is template for vm_obtain
is_template=1
is_cloud=1

vm_cpus="4"
vm_ram="4g"
imgsize_min="10g"
imgsize="16g"

# enable birtio RNG interface?
virtio_rnd="1"

## cloud-init specific settings ##
ci_template="centos9"
ci_user_pw_root='*'

ci_user_add='debian'

ci_user_gecos='debian user'
ci_user_home='/home/debian'
ci_user_shell='/bin/bash'
ci_user_member_groups='root'
ci_user_pw_crypt='*'
ci_user_pubkey=".ssh/id_rsa.pub"

default_ci_ip4_addr="DHCP"
default_ci_gw4="auto"

ci_nameserver_address="8.8.8.8"
ci_nameserver_search="my.domain"
## cloud-init specific settings end of ##
