#!/bin/sh
[ -z "${CIX_DISTDIR}" ] && CIX_DISTDIR="/usr/local/cbsd"
[ -z "${CIX_BIN}" ] && CIX_BIN="/usr/local/bin/cbsd"

${CIX_BIN} jstatus jname=cbsdpuppet1 > /dev/null 2>&1
ret=$?

if [ ${ret} -ne 1 ]; then
	echo "master_create_d puppet-apply script error:"
	echo "No such 'cbsdpuppet1' jail to apply Puppet's manifests"
	echo "Please create them first: cbsd jcreate jname=cbsdpuppet1 jprofile=cbsdpuppet"
	exit 1
fi

if [ ! -x ${CIX_DISTDIR}/modules/puppet.d/puppet ]; then
	echo "master_create_d puppet-apply script error:"
	echo "No such 'puppet.d' module"
	echo "Please create them first and active:"
	echo " cbsd module mode=install puppet"
	echo " echo 'puppet.d' >> ~cbsd/etc/modules.conf"
	echo " cbsd initenv"
	exit 1
fi

${CIX_BIN} puppet jname=${jname} mode=apply module=fs
ret=$?

exit ${ret}
