#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
CBSDMODULE="build"
MYARG=""
MYOPTARG=""
MYDESC="List of bases"

set -e
. ${globalconf}
set +e

. ${subr}
init $*

ls -1 ${basejaildir} |grep  ^${basejailpref}
