#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
CBSDMODULE="build"
MYARG=""
MYOPTARG=""
MYDESC="List of bases"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

ls -1 ${basejaildir} |grep  ^${basejailpref}
