#!/bin/sh
#v10.0.4
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG=""
MYDESC="Enable CARP configuration"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${tools}
. ${initenv}
init $*

if [ ! -f "/usr/local/etc/devd/cbsd_carp.conf" ]; then
	if getyesno "Configure cbsd_carp.conf notify in /usr/local/etc/devd directory?"; then
		[ ! -d "/usr/local/etc/devd" ] && mkdir -p /usr/local/etc/devd
		cp ${sharedir}/cbsd_carp.conf /usr/local/etc/devd/
		#Update inventory
		#  env sqlcolnames="1" ${miscdir}/sqlcli ${dbdir}/local.sqlite "SELECT * FROM local" > ${inventory}
		/usr/sbin/service devd restart
	fi
fi
