#!/bin/sh
#v9.2.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="conf"
MYDESC="create package repo dialog-based UI"
ADDHELP="conf= alternarive config path instead of workdir/etc/cpr.conf\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${distccacheconf}

init $*

DIALOG=${DIALOG=/usr/bin/dialog}
BACKTITLE="--backtitle \Z1${0}\Zn --colors"

[ -z "${conf}" ] && conf="$etcdir/cpr.conf"

choice_arch()
{
 $DIALOG ${BACKTITLE} --title "Select architecture."  --clear \
         --default-item "${arch}" --menu "Make your choice." 10 50 2 \
         "i386" "Processor arch." \
         "amd64" "Processor arch." 2> ${TMPFILE}

 retval2=$?
 choice2=`cat ${TMPFILE}`

 case $retval2 in
    0) arch="${choice2}"
	;;
 esac

 return $retval2
}

choice_commit()
{
local _cdir
_cdir="/tmp/`md5 -qs \"${ver}${arch}${repoversion}${basename}\"`"

echo cbsd cpr ver=${ver} arch=${arch} new=${NEWREPO} destdir=${DESTDIR} cdir="${_cdir}" pkglist="${SOURCES}" repoversion=${REPOVERSION}
exit 0
}




create_repoversion()
{
$DIALOG ${BACKTITLE} --title "Create new repoversion"  --clear \
     --inputbox "Enter one-work repoversion name (e.g: mycompany)" 10 55 2> ${TMPFILE}

 retval2=$?
 choice2=`cat ${TMPFILE}`

 case $retval2 in
    0) [ -z "${choice2}" ] && return 0
    REPOVERSION="${choice2}"
    mkdir -p ${dbdir}/ports-${repoversion}
	;;
 esac

 return $retval2
}

choice_destdir()
{
$DIALOG ${BACKTITLE} --title "Output directory"  --clear \
     --inputbox "Enter destination directory path  (e.g: /tmp/myrepo)" 10 55 2> ${TMPFILE}

 retval2=$?
 choice2=`cat ${TMPFILE}`

 case $retval2 in
    0) [ -z "${choice2}" ] && return 0
    DESTDIR="${choice2}"
	;;
 esac

 return $retval2
}

choice_sources()
{
    local _dir="/"

    while [ 1 ]; do
	$DIALOG --clear --title "ascii-file with port list ot 'pkg_cutleaves'" --fselect $DIR/ 30 55 2> /tmp/out

	case $? in
	    0)
    		_res=`cat /tmp/out`
    		[ -f "${_res}" ] && SOURCES=${_res} && return 0
		[ "${_res}" = "pkg_cutleaves" ] && SOURCES="pkg_cutleaves" && return 0
    		SOURCES="`realpath ${_res}`"
	    ;;
	    1) return 1
	esac
    done
}


choice_ver()
{
local _i _options _num

    _options=""
    _num=0

    for _i in $KNOWN_RELEASES; do
	_options="${_options} ${_i} ${_i}"
	_num=$((_num + 1))
    done

    $DIALOG ${BACKTITLE} --title "Select version."  --clear \
        --default-item "${ver}" --menu "Make your choice." 0 30 ${_num} \
	${_options} 2> ${TMPFILE}

    retval312=$?
    choice312=`cat ${TMPFILE}`

    case $retval312 in
	0)
	    ver="${choice312}"
	;;
    esac

    return $retval312
}

choice_newrepo()
{
    $DIALOG ${BACKTITLE} --title "New repository?"  --clear \
        --default-item "yes" --yesno "Create new repository (yes) \
or continue (no) the last build. \n\
When 'yes' (new repo) selected, previous directory with \
packages will be removed first. \
When 'no' selected the presence of first-built packages \
will be installed first" 10 60

    retval=$?

    case $retval in
	0)
    	    NEWREPO=1;;
	1)
    	    NEWREPO=0;;
    esac
}


choice_repoversion()
{
local _i _options _num 

cat > ${_menufile} << EOF
--extra-button --extra-label "Browse" --help-button --help-label "Create" --item-help --ok-label "Select"\
 --clear --default-item "${repoversion}" --radiolist "This is list of current repoversion\n\
You can browse or edit options inside every version\n\
or create another one\n" 20 61 5 \
  "default" "system" on "Hint: /var/db/ports"
EOF
    _num=1

    for _i in `find ${dbdir} -type d -name ports-\* | cut -d - -f2`; do
cat >> ${_menufile} << EOF
"${_i}" "${_i}" "off" "Hint: ${dbdir}/ports-${_i}"
EOF
            _num=$((_num + 1))
    done

$DIALOG ${BACKTITLE} --file ${_menufile} 2>${TMPFILE}

    retval=$?
    choice=`cat ${TMPFILE}`

    case $retval in
	0)
    	    REPOVERSION=${choice} ;;
	2) 
	    create_repoversion ;;
	3)
	    REPOVERSION="${choice}" 
	    if [ "${REPOVERSION}" = "default" ]; then
		/usr/local/bin/cbsd options-tui portsdir=/usr/ports optionsdir=/var/db/ports
	    else
		/usr/local/bin/cbsd options-tui portsdir=/usr/ports optionsdir=${dbdir}/ports-${REPOVERSION}
	    fi
	;;
    esac
}


#MAIN
. ${conf}
. ${buildconf}

[ -z "${NEWREPO}" ] && NEWREPO=1
[ -z "${REPOVERSION}" ] && REPOVERSION="default"
[ -z "${basename}" ] && basename="default"
[ -z "${FREEBSDBASE}" ] && FREEBSDBASE=1
[ -z "${DESTDIR}" ] && DESTDIR="/usr/home/web/pkgupdate.my.domain"
[ -z "${SOURCES}" ] && SOURCES="pkg_cutleaves"


TMPFILE="${ftmpdir}/inputbox.$$"
_menufile="${ftmpdir}/choicerepo.$$"
trap "rm -f ${TMPFILE} ; rm -f ${_menufile}" EXIT

while [ 1 ]; do

$DIALOG ${BACKTITLE} --title "create package reposiory"  --clear \
        --default-item "commit" --menu "\n cbsd cpr settings" 20 55 20 \
	newrepo "${NEWREPO}" \
	repoversion "${REPOVERSION}" \
	freebsdbase "${FREEBSDBASE}" \
	ccachefs "${CCACHEFS}" \
        arch "${arch}" \
        ver "${ver}" \
        sources "${SOURCES}" \
        basename "${basename}" \
	notify "${CBSDRCPT}" \
	destdir "${DESTDIR}" \
        shedule "${SCHEDULE}" \
        commit "" 2> ${TMPFILE}

retval=$?
case $retval in
  0)
   choice=`cat ${TMPFILE}`
    [ $choice = "ver" ] && choice_ver
    [ $choice = "arch" ] && choice_arch
    [ $choice = "newrepo" ] && choice_newrepo
    [ $choice = "repoversion" ] && choice_repoversion
    [ $choice = "destdir" ] && choice_destdir
    [ $choice = "sources" ] && choice_sources
    [ $choice = "commit" ] && choice_commit
;;
  *)
    exit;;
esac
    [ "${DIALOG}" = "$XDIALOG" ] && exit

done
