#!/bin/sh
#v10.0.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="md cd"
MYDESC="Return for visible storage"
# really - this is wrapper for miscdir/disks-list
ADDHELP="md=1 - show md disks too\n\"
cd=1 - show cd disks too\n"

set -e
. ${globalconf}
set +e

. ${subr}
init $*

TOOLS_ARG=""

[ "${md}" = "1" ] && TOOLS_ARG="${TOOLS_ARG} -m"
[ "${cd}" = "1" ] && TOOLS_ARG="${TOOLS_ARG} -c"

${miscdir}/disks-list ${TOOLS_ARG}

