#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
MYARG="ip"
MYOPTARG=""
MYDESC="Return network interface name by ip"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${tools}

init $*

IP=`/bin/echo ${ip} |/usr/bin/tr "/" " " |/usr/bin/awk {'printf $1'}`

iptype ${IP}
_inet=$?

[ ${_inet} -eq 0 ] && err 1 "not ip"

#check for localip
for iface in ${jail_interface}; do
A=`/sbin/ifconfig "${iface}" | /usr/bin/grep ${IP}`
[ -z "${A}" ] || err 0 ${iface}
done

case ${_inet} in
1)
MODIF="-inet"
;;
2)
MODIF="-inet6"
;;
esac

IFACE=`/sbin/route -n get ${MODIF} ${IP} |/usr/bin/grep "interface:" |/usr/bin/awk {'printf $2'}`

# return default
if [ -z ${IFACE} ]; then
    IFACE=`/bin/echo ${jail_interface} |/usr/bin/awk {'printf $1'}`
fi

err 0 ${IFACE}

