#!/bin/sh
#v9.1.1
globalconf="${workdir}/cbsd.conf";
MYARG="ip"
MYOPTARG=""
MYDESC="Return network interface name by ip"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${tools}

init $*

ipwmask ${ip}
iptype ${IWM}
_inet=$?

[ ${_inet} -eq 0 ] && err 1 "not ip"

ifs=$( ${miscdir}/nics-list -a |xargs)

for iface in ${ifs}; do
    A=`/sbin/ifconfig "${iface}" | /usr/bin/grep ${IWM} 2>/dev/null`
    [ -z "${A}" ] || err 0 ${iface}
done

case ${_inet} in
    1)
	MODIF="-inet"
	;;
    2)
	MODIF="-inet6"
	;;
esac

IFACE=`/sbin/route -n get ${MODIF} ${IWM} |/usr/bin/awk '/interface:/{print $2}'`

# return default
[ -z ${IFACE} ] && IFACE="lo0"

err 0 ${IFACE}
