#!/bin/sh
#v9.2.2
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG=""
MYDESC="This help"

if [ "$1" = "--help" ]; then
    echo $MYDESC
    exit
fi

. ${workdir}/securecmd
. ${workdir}/ansiicolor.subr

ECHO="echo -e"

for i in ${SECCMD}; do
	_cmddesc=`cbsd ${i} --help |head -n1 2>/dev/null`
	$ECHO "${BOLD}${i} ${MAGENTA} --  ${GREEN}${_cmddesc}${NORMAL}"
done

