#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG=""
MYDESC="This help"

if [ "$1" = "--help" ]; then
    echo $MYDESC
    exit
fi

ROOTDIR="/usr/local/cbsd"
SCANDIR="/bin /jailctl /nodectl /system /tools"

for _dir in ${SCANDIR}; do
CHECKDIR="${ROOTDIR}${_dir}"
for _fl in `find ${CHECKDIR} -depth 1 -type f -perm 0755 -exec realpath {} \;`; do
CMD=`basename ${_fl}`
if [ `file ${_fl} |grep 'POSIX shell script text executable' |wc -l` = "1" ]; then
    MYDESC=`cbsd $CMD --help |head -n1`
    echo "${CMD}  - ${MYDESC}"
else
    echo "${CMD}"
fi
done
done

