#!/bin/sh
#v10.0.5
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG=""
MYDESC="Ncurses based jail creation wizard"
EXTHELP="wf_jcreate.html"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${settingstui}
. ${color}
. ${dialog}

init $*

gen_newjail_conf()
{

    local _i _required _mytest _ret

    _required="jname fqdn ip4_addr ver arch"

    msg_ok="ok"

    for _i in ${_required}; do
	eval _mytest=\$$_i
	if [ -z "${_mytest}" ]; then
	    f_dialog_msgbox "${_i} must be not non-empty" "Error"
	    return 0
	fi
    done

#check for ip if oninterface
    if [ "${interface}" != "0" ]; then
	cbsd checkip ip=${ip4_addr} check=1 2>/dev/null
	case $? in
	    2)
		msg_yes="ok"
		msg_no="not ok"
		f_dialog_noyes "It seems like ${ip4_addr} address already used on several devices on the LAN\nYou can found MAC address by \"arp -an\" command.\n If you believe that it's ok, choose 'ok' to continue or 'not ok' for another IP address" "WARNING"
		case $? in
		    0)
			;;
		    *)
			return 0
		esac
	esac
    fi
    vnet=${vimage}
    cbsd jconstruct-fromargs basename=$basename mdsize=$mdsize jname=$jname fqdn=$fqdn ip4_addr=$ip4_addr ver=$ver baserw=$baserw mount_src=$mount_src mount_ports=$mount_ports astart=$astart interface=$interface vnet=$vnet applytpl=$applytpl floatresolv=$floatresolv arch=$arch pkglist=$pkglist
    ERR=$?

    [ $ERR -eq 0 ] || err 1 "${MAGENTA}Bad conf${NORMAL}"
    err 0 ${A}
}


#### [ MAIN AREA ] ####
[ ! -f ${globalconf} ] && err 1 "${MAGENTA}no such conf file${NORMAL}"
. ${globalconf}

[ ! -f ${localcbsdconf} ] && err 1 "${MAGENTA}no such conf file${NORMAL}"
. ${localcbsdconf}
. ${inventory}

#defaults
. ${buildconf}

readconf jail.conf

msg_ok="Ok"
msg_cancel="Cancel"

while [ 1 ]; do
    pkgnum=0
    [ -n "${pkglist}" -a "${pkglist}" != "NO" ] && pkgnum=`wc -l ${pkglist}|awk '{printf $1}'`

    menu_list="
    'pkglist' 'mark pkg for install from repo $(curval pkgnum)'
    'jname' 'A short jail name $(curval jname)'
    'fqdn'  'Full (FQDN) jail hostname $(curval fqdn)'
    'ip4_addr' 'Assing IP address $(curval ip4_addr)'
    'ver' 'choose code base version $(curval ver)'
    'baserw'  'Jail base is not read-only $(curval baserw)'
    'mount_ports' 'Mount for /usr/ports $(curval mount_ports)'
    'astart'  'Auto start-up with system $(curval astart)'
    'interface' 'Interface selection and aliasing mode $(curval interface)'
    'applytpl'  'Apply cbsd templates $(curval applytpl)'
    'floatresolv' 'Auto correct for jail resolv.conf $(curval floatresolv)'
    'arch' 'target arch $(curval arch)'
    "
    #dynamic menu
    [ "${vnet}" = 1 ] && menu_list="${menu_list} 'vnet' 'Enable virtual stack for jail? $(curval vimage)'"

    #'mdsize' 'image for md or bhyve $(curval mdsize)'

    menu_list="${menu_list} 'GO' 'PROCEED!'"

    f_dialog_menu
    retval=$?
    f_dialog_menutag_fetch mtag
    case $retval in
	0)
	    [ $mtag = "pkglist" ] && get_pkglist
	    [ $mtag = "jname" ] && get_jname
	    [ $mtag = "fqdn" ] && get_jail_fqdn
	    [ $mtag = "ip4_addr" ] && get_jail_ips
	    [ $mtag = "ver" ] && get_jail_base
	    [ $mtag = "baserw" ] && get_jail_baserw
	    [ $mtag = "mount_src" ] && get_jail_mount_src
	    [ $mtag = "mount_ports" ] && get_jail_mount_ports
	    [ $mtag = "astart" ] && get_jail_astart
	    [ $mtag = "interface" ] && get_jail_oninterface
	    [ $mtag = "vnet" ] && get_jail_vnet
	    [ $mtag = "applytpl" ] && get_jail_applytpl
	    [ $mtag = "floatresolv" ] && get_jail_floatresolv
	    [ $mtag = "arch" ] && get_jail_arch
	    [ $mtag = "mdsize" ] && get_jail_mdsize
	    [ $mtag = "GO" ] && gen_newjail_conf
	    ;;
	*)
	    exit
	    ;;
    esac
done
