#!/bin/sh
#v9.2.2
globalconf="${workdir}/cbsd.conf";
MYARG="jname"
MYOPTARG="mode"
MYDESC="Generate jail secrets phrase sequence for rsync"

set -e
. ${globalconf}
set +e

. ${subr}
init $*

[ -z "${jname}" ] && err 1 "Give me jname"

PW=$( /usr/bin/head -c 30 /dev/random | /usr/bin/uuencode -m - | /usr/bin/tail -n 2 | /usr/bin/head -n1 )

SECFILE="${workdir}/etc/${jname}.secrets"
[ -f "${SECFILE}" -a "${mode}" != "force" ] && err 1 "Secrets already exist"
echo "${PW}" > ${SECFILE}
echo "${jname}:${PW}" >> ${SECFILE} 
chown root:wheel ${SECFILE} && chmod 0600 ${SECFILE}
