#!/bin/sh
#v9.2.0
globalconf="${workdir}/cbsd.conf";
MYARG="jname"
MYOPTARG="fromfile keyfile auto otherhost include exclude tofile"
MYDESC="Generate csync2.cfg for jname"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
init $*

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${initenv}
. ${tools}
init $*

JAILRCCONF="${jailrcconfdir}/rc.conf_${jname}"

[ ! -f  "${JAILRCCONF}" ] && {
    [ "${remote}" = "0" ] && try_remote
    err 1 "No such rc.conf for jail found"
}

. ${JAILRCCONF}
[ $baserw -eq 1 ] && path=$data

get_jid
errcode=$?

#defaults
if [ -n "${auto}" ]; then
    AUTO="${auto}"
else
    AUTO="younger"
fi


tofile="${jailsysdir}/${jname}/csync2.cfg"

[ -n "${fromfile}" ] && . ${fromfile}

cat > ${tofile} << EOF
nossl *-sync *-sync;

group ${jname}
{
    host ${nodename};
EOF

if [ -n "${otherhost}" ]; then
    for i in ${otherhost}; do
    cat >> ${tofile} << EOF
    host ${i};
EOF
    done
fi

if [ -n "${keyfile}" ]; then
    cat >> ${tofile} << EOF
    key ${jailsysdir}/${jname}/${keyfile};
EOF
fi

if [ -n "${include}" ]; then
    for i in ${include}; do
    cat >> ${tofile} << EOF
    include ${path}${i};
EOF
    done
fi

if [ -n "${exclude}" ]; then
    for i in ${exclude}; do
    cat >> ${tofile} << EOF
    exclude ${path}${i};
EOF
    done
fi

cat >> ${tofile} << EOF
    auto ${AUTO};
}
EOF

