#!/bin/sh
#v9.2.0
globalconf="${workdir}/cbsd.conf";
MYARG="scene"
MYOPTARG="ver arch"
MYDESC="Make jail by scenario file"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${tools}
. ${system}

init $*

[ ! -f "${scene}" ] && err 1 "No such scene file"

over=$ver
oarch=$arch

. ${scene}
. ${buildconf}

SCENEDIR=`dirname ${scene}`
PKGLIST="${SCENEDIR}/${scenename}.list"
JCONF="${SCENEDIR}/${scenename}.jconf"

[ ! -f "${JCONF}" ] && err 1 "No jconf ${JCONF}"
[ ! -f "${PKGLIST}" ] && err 1 "No package list file ${PKGLIST}"

pkgfile="${ftmpdir}/${scenename}.$$"
workjconf="${ftmpdir}/${scenename}.$$.jconf"

cut -d / -f 5 ${PKGLIST} > ${pkgfile}
cp ${JCONF} ${workjconf}
modconf ${workjconf} ver "${ver}"
modconf ${workjconf} arch "${arch}"
modconf ${workjconf} pkglist "${pkgfile}"
. ${workjconf}
modconf ${workjconf} packagesite "${packagesite}"

cbsd jcreate jconf=${workjconf}

# system dir
if [ -d "${etcdir}/scenes/${scenename}" ]; then
    [ -d "${jailsysdir}/${scenename}" ] && rm -rf "${jailsysdir}/${scenename}"
    cp -Rp ${etcdir}/scenes/${scenename} ${jailsysdir}/${scenename}
fi

if [ -f "${etcdir}/scenes/${scenename}/${scenename}-descr" ]; then
    [ ! -d "${jailsysdir}/${scenename}" ] && mkdir ${jailsysdir}/${scenename}
    cp ${etcdir}/scenes/${scenename}/${scenename}-descr ${jailsysdir}/${scenename}/descr
fi

JAILRCCONF="${jailrcconfdir}/rc.conf_${scenename}"

[ ! -f "${JAILRCCONF}" ] && err 1 "no such rc.conf after jcreate for ${scenename}"

. ${JAILRCCONF}

#Overwrite skel files
SKELDIR="${etcdir}/scenes/${scenename}/skel"

#test for zfs mounted & mount if not
    case $zfsfeat in
        1) . $zfstool
        zfsmnt ${data}
        [ $? -eq 2 ] && zfs mount "${ZPOOL}"
        ;;
    esac

if [ -d "${SKELDIR}" ]; then
    cp -rPf ${SKELDIR}/* ${data}/
fi


if [ -f "${etcdir}/scenes/${scenename}/post-install" ]; then
    cp ${etcdir}/scenes/${scenename}/post-install ${data}/tmp
    chroot ${data} sh /tmp/post-install
fi
