#!/bin/sh
#v9.2.2
globalconf="${workdir}/cbsd.conf";
MYARG="jname out"
MYOPTARG=""
MYDESC="Make jailv2 config file"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${tools}

init $*

mkjhosts()
{
    IP=$1
    JHOST=$2

    [ $applytpl -eq 0 -o "$ver" = "empty" ] && return

    #check for dup
    for i in `egrep "[:blank:]*${host_hostname}" ${JHOST} |awk '/^;/{print $1"\n"}'`; do
	if [ "$i" != "${IP}" ]; then
		TMPH="${ftmpdir}/hosts.$$"
		cp ${JHOST} ${TMPH}
		grep -v "[:blank:]*${host_hostname}" ${TMPH} > ${JHOST}
		rm -f ${TMPH}
	fi
    done

    [ `grep -c ^${IP} ${JHOST}` = "0" ] && echo ${IP} ${host_hostname} >> ${JHOST}
}


JAILRCCONF="${ftmpdir}/rc.conf_${jname}"
cbsd jmkrcconf jname=${jname} > ${JAILRCCONF}
. ${JAILRCCONF}
rm -f ${JAILRCCONF}

eval multiips4=\"\$ip4_addr\"

[ $baserw -eq 1 ] && path=$data

#rewrite from cbsd zero to null
[ "${exec_start}" = "0" ] && unset exec_start
[ "${exec_stop}" = "0" ] && unset exec_stop
[ "${exec_poststart}" = "0" ] && unset exec_poststart
[ "${exec_poststop}" = "0" ] && unset exec_poststop
[ "${exec_prestart}" = "0" ]  && unset exec_prestart
[ "${exec_prestop}" = "0" ] && unset exec_prestop
[ "${interface}" = "0" ] && unset interface

cat > ${out} << EOF
${jname} {
exec.start = "${exec_start}";
exec.stop = "${exec_stop}";
exec.poststart="${exec_poststart}";
exec.poststop="${exec_poststop}";
exec.prestart="${exec_prestart}";
exec.prestop="${exec_prestop}";
exec.clean;
#mount.devfs;
host.hostname = "${host_hostname}";
path = "${path}";
allow.raw_sockets;
allow.socket_af;
allow.chflags;
allow.sysvipc;
EOF

ALIAS4=""
ALIAS6=""
ips=`echo ${multiips4}|tr "," " "`

# autodetect correct interface
if [ -n "${interface}" ]; then
    if [ "${interface}" = "auto" ]; then
	if [ -n "${ip4_addr}" ]; then
	    ip=`echo ${ip4_addr}|awk '{printf $1}'`
	    interface=`cbsd getnics-by-ip ip=${ip}`
	else
	    interface=`cbsd getnics-by-ip ip=0.0.0.0`
	fi
    fi
    echo "interface=\"${interface}\";" >> $out
fi

for a in ${ips}; do
    iptype $a
    _inet=$?
    [ ${_inet} -eq 0 ] && continue

    ipwmask ${a}

    case ${_inet} in
	1)
	    if [ -z "$ALIAS4" ]; then
		echo "ip4.addr = ${a};" >> ${out}
		[ "${mkhostsfile}" != "0" ] && mkjhosts ${IWM} ${data}/etc/hosts
		ALIAS4="1"
	    else
		[ "${mkhostsfile}" != "0" ] && mkjhosts ${IWM} ${data}/etc/hosts
		echo "ip4.addr += ${a};" >> ${out}
	    fi
	    ;;
	2)
	    if [ -z "$ALIAS6" ]; then
		echo "ip6.addr = ${a};" >> ${out}
		ALIAS6="1"
	    else
		echo "ip6.addr += ${a};" >> ${out}
	    fi
	    ;;
    esac
done

if [ "$devfs" = "NO" ]; then
    echo "mount.nodevfs;" >> ${out}
else
    echo "mount.devfs;" >> ${out}
fi

[ -n "${devfs_ruleset}" ] && echo "devfs_ruleset=\"${devfs_ruleset}\";" >> $out

if [ "${allow_mount}" = "1" ]; then
    echo "allow.mount = \"true\";" >> ${out}
    echo "enforce_statfs=\"1\";" >>${out}
fi

if [ "${allow_nullfs}" = "1" ]; then
    echo "allow.mount.nullfs = \"true\";" >> ${out}
fi

if [ "${allow_devfs}" = "1" ]; then
    echo "allow.mount.devfs = \"true\";" >> ${out}
fi



echo "}" >> ${out}
