#!/bin/sh
#v9.2.0
globalconf="${workdir}/cbsd.conf";
MYARG="mdfile jroot"
MYOPTARG=""
MYDESC="Mount image file via md vnode to mroot"
ADDHELP="jroot - mount point\n\
mdfile - image file\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${mdtools}

init $*

[ ! -f "${mdfile}" ] && err 1 "No such ${mdfile}"
[ ! -d "${jroot}" ] && err 1 "No such ${jroot}"

mydev=`mdconfig -a -t vnode -f ${mdfile}`

echo "Running fsck on the image. Please wait"
fsck -t ufs -y "/dev/${mydev}" > /dev/null 2>&1
if [ $? -ne 0 ]; then
    cat >/dev/stdout Unrecovery error. Please run manually: <<EOF
mdconfig -a -t vnode -f \${mdfile}
fsck -t ufs -y "md devices"
mdconfig -d -u "md devices"
EOF
    err 1 "Fsck error"
fi

mount /dev/${mydev} ${jroot}
