#!/bin/sh
#v9.2.1
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG=""
MYDESC="Enable NAT service for RFC1918 Networks"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${tools}
. ${initenv}
. ${color}
init $*


if getyesno "${BOLD}Configure NAT for RFC1918 Network?${NORMAL}"; then
	configure_nat
	#Update inventory
	cbsd inventorysql --dbfile=${dbdir}/local.sqlite --action=list > ${inventory}
fi
