#!/bin/sh
#v9.2.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="nat"
MYDESC="Enable NAT service for RFC1918 Networks"
ADDHELP="nat= name of framework. default in inventory config\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
init $*

[ -n "${nat}" ] && nat_enable="${nat}"

case "${nat_enable}" in
"pf")
    [ ! -f "${etcdir}/pfnat.conf" ] && err 1 "No pfnat.conf. run cbsd natcfg first"
    kldstat -qm pf || kldload pf
    ping -c1 -S ${natip} 127.0.0.1 > /dev/null 2>&1 || err 1 "Cant assign nat address ${natip}. Probably wrong ip. Nat cfg skipped"
    cbsd natoff nat=all
    pfctl -f ${etcdir}/pfnat.conf
    pfctl -e
;;
"ipfw")
    [ ! -f "${etcdir}/ipfw.conf" ] && err 1 "No ipfw.rules. run cbsd natcfg first"
    kldstat -qm alias || kldload libalias
    kldstat -qm ipfw_nat || kldload ipfw_nat
    cbsd natoff nat=all
    ping -c1 -S ${natip} 127.0.0.1 > /dev/null 2>&1 || err 1 "Cant assign nat address ${natip}. Probably wrong ip. Nat cfg skipped"
    sh ${etcdir}/ipfw.conf
;;
esac
