#!/bin/sh
#v10.0.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="desc all skip"
MYDESC="Return for visible storage"
# really - this is wrapper for miscdir/nics-list
ADDHELP="desc=1 - show description and status too\n\
all=1 show all nics, no filtering for special interfaces\n\"
skip='lo xxx' - skip ifaces in list\n"

set -e
. ${globalconf}
set +e

. ${subr}
init $*

TOOLS_ARG=""

[ "${desc}" = "1" ] && TOOLS_ARG="${TOOLS_ARG} -d"
[ "${all}" = "1" ] && TOOLS_ARG="${TOOLS_ARG} -a"
[ -n "${skip}" ] && TOOLS_ARG="${TOOLS_ARG} -s ${skip}"

exec ${miscdir}/nics-list ${TOOLS_ARG}
