#!/bin/sh
#v9.2.0
globalconf="${workdir}/cbsd.conf";
MYARG="portsdir optionsdir"
MYDESC="Generate choosen package list from repository"
ADDHELP="out=path_to_file with result, instead of random\n"

[ -f "${globalconf}" ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${tools}
init $*

tmp1="${ftmpdir}/optionstui.$$"
out="${ftmpdir}/optionsout.$$"
DIALOG=${DIALOG=/usr/bin/dialog}

trap "rm -f $tmp1 ${out}" EXIT

[ ! -d "${portsdir}" ] && err 1 "No portsdir"
[ ! -d "${optionsdir}" ] && err 1 "No portsdir"


#MAIN

while [ 1 ]; do

LIST=`find ${optionsdir} -maxdepth 1 -depth 1 -type d -exec basename {} \;`

cat > $tmp1 << EOF
--extra-button --ok-label "Edit" --extra-label "Remove" --colors --backtitle "\Z1Select options" --separate-output --title "Select options" --checklist "Use space for mark options \n" 0 61 0
EOF

for i in ${LIST}; do
    [ -z "${A}" ] &&  echo "\"$i\" \"$i\" off \ " >> ${tmp1}
done

${DIALOG} --file ${tmp1} 2>$out

retval312=$?
case $retval312 in
        0)
	for i in `cat ${out}|xargs`; do
	    [ -z "${i}" ] && continue
	    portfolder=`pkg query "%o" ${i}`
	    if [ -z "${portfolder}" ]; then
	    ${DIALOG} --title "MESSAGE BOX" --msgbox "Cant determine port folder via \n\
% pkg query \"%o\" $i\n\
command. Please Enter for continue" 8 41
	    continue
	    fi
	    env PORT_DBDIR=${optionsdir} make -C ${portsdir}/${portfolder} config
	done
        ;;
        3)
	cd ${optionsdir} 
	for i in `cat ${out}|xargs`; do
	    [ -z "${i}" ] && continue
	    rm -rf ${i}
	done
        ;;
	*) exit
esac

done
