#!/bin/sh
#v9.2.2
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="out jname pkgdbdir filter portname"
MYDESC="Show or generate pkg list from pkgdbdir or jail"
ADDHELP="out=filename - update mode, redirect output to out=filename\n\
jname=jname info for jail jname\n\
pkgdbdir= use this path for info instead of query by jname\n\
filter= - additional argument to pkg info\n\
portname=nameport - query for nameport only\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${color}
. ${strings}

init $*

[ -z "${filter}" ] && filter=""
[ -z "${portname}" ] && portname=""

if [ -n "${jname}" ]; then
    JAILRCCONF="${jailrcconfdir}/rc.conf_${jname}"
    [ -f  "${JAILRCCONF}" ] || err 1 "no conf rc.conf file for jail"
    . ${JAILRCCONF}
    DBDIR="${data}/var/db/pkg"
else
    if [ -n "${pkgdbdir}" ]; then
	DBDIR="${pkgdbdir}"
    else
	DBDIR="/var/db/pkg"
    fi
fi

if [ -n "${out}" ]; then
    [ ! -d `dirname ${out}` ] && mkdir -p `dirname ${out}`
fi

[ -z "${out}" ] && out="/dev/stdout"
[ -d "${DBDIR}" ] || err 1 "No such pkg pkgdbdir"

env PKG_DBDIR="${DBDIR}" /usr/sbin/pkg query ${filter} ${portname} > ${out}
