#!/bin/sh
#v9.2.2
globalconf="${workdir}/cbsd.conf";
MYDESC="Replace for workdir"
MYARG=""
MYOPTARG="old file0 file1 file2 file3 file4 file5 file6 new"
ADDHELP="Replace rootdir in fileX= file (where X is increment num (from zero) when multiple files)\n\
by workdir param or new= param if sets\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

cd ${workdir}

[ -n "${new}" ] && workdir=$new

i=0

while : ; do
    eval file=\"\${file${i}}\"
    [ -z "$file" ] && break
    if [ -f "${file}" ]; then
	sed -i '' s:${old}:${workdir}:g ${file}
    fi
    i=$((i + 1))
    [ $i -ge $# ] && break
done

