#!/bin/sh
#v9.2.0
globalconf="${workdir}/cbsd.conf";
MYARG="action"
# action=list,get,put
# source=src,obj,base,kernel,img
MYOPTARG="mode arch ver sources name basename stable inter"
#mode=check,update,upgrade
MYDESC="Working with CBSD Repository"
ADDHELP="action can be: list, get, put
sources can be: src, obj, base, kernel, img\n
mode can be: check, update, upgrade, quiet\n\
stable=1 for RELENG_X\n\
ver=any for mode=list for show all version (no for cur. version only\n\
arch=any for mode=list for show all arch (no for cur. arch only\n\
inter=0 to prevent any questions and to accept answers by default\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${color}
init $*

fetchme()
{
    cbsd cfetch -u $1 -o ${TF}
    return $?
}

checkmd5()
{
    local _GOOD _OMD5 _RMD5 _i _FILE
    DIR=$1
    _GOOD=0

    for _i in `find ${DIR} -type f -depth 1 -name *.md5 -print`; do
	_FILE=`${ECHO} ${_i} |sed 's/\.md5//g'`
	_OMD5=`cat ${_FILE}.md5`
	_RMD5=`md5 -q ${_FILE}`
	if [ "${_RMD5}" != "${_OMD5}" ]; then
	    _GOOD=$((_GOOD + 1))
	fi
    done

return ${_GOOD}
}



checkrepo()
{
local _i

    for _i in ${REPO}; do
	[ -z $1 ] && printf "${MAGENTA}Check for repository${NORMAL}: ${GREEN}${_i}${NORMAL} ..."
	if fetchme "${_i}/cbsd.index" >/dev/null 2>&1; then
	    cat "${TF}"
	    exit 0
	else
	    ${ECHO} "${_i} Offline"
	    exit 1
	fi
    done
}


getsrc()
{

    if [ -d "${srcdir}/${DIR}" ]; then
	[ $UPGRADE -eq 1 ] || err 1 "You already have ${ver}"
	cbsd removesrc ver=${ver}
    fi

    for MYREPO in ${REPO}; do
	${ECHO} "${MAGENTA}REPO${NORMAL}:${GREEN}${MYREPO}${NORMAL}"
	MIRROR="${MYREPO}/src_${ver}/mirror.html"
	cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1
	if [ $? -eq 0 ]; then
	    MYREPO=`cat ${TF}`
	    ${ECHO} "${MAGENTA}Found new mirror for ${ver}${NORMAL}:${GREEN}${MYREPO}${NORMAL}"
	fi
	cbsd cfetch -o ${MYDIR}/src.txz -u ${MYREPO}/${DIR}/src.txz
	[ $? -eq 0 ] || continue
	cbsd cfetch -o ${MYDIR}/src.txz.md5 -u ${MYREPO}/${DIR}/src.txz.md5 >/dev/null 2>&1
	[ $? -eq 0 ] || continue
    done

    [ -f "${MYDIR}/src.txz" -a -f "${MYDIR}/src.txz.md5" ] || err 1 "No sources found"

    if checkmd5 ${MYDIR}; then
	${ECHO} "${MAGENTA}MD5sum correct.${NORMAL}"
	    else
	err 1 "${MAGENTA}MD5sum incorrect.${NORMAL}"
    fi

    ARCHIVE="${workdir}/tmp/src_${ver}.txz"
    [ ! -f "${ARCHIVE}" ] || rm -f ${ARCHIVE}

    ${ECHO} "${MAGENTA}Extracting...${NORMAL}"
    cd $workdir/tmp
    tar xfz ${MYDIR}/src.txz
    rm -f ${MYDIR}/src.txz
    mkdir -p ${srcdir}/src_${ver}
    mv ${workdir}/tmp/src_${ver} ${srcdir}/
    ${ECHO} "${MAGENTA}Done...${NORMAL}"
    DT=`/bin/date "+%Y%m%d"`
}

getbase()
{

    if [ -z "${basename}" ]; then
	BDIR="${basejailpref}_${arch}_${ver}"
    else
	BDIR="${basejailpref}_${basename}_${arch}_${ver}"
    fi

    DST="${basejaildir}/${BDIR}"
    MIRROR="http://ftp.freebsd.org"
    BSDBASE_DISTSITE="$MIRROR/pub/FreeBSD/releases/${arch}/${arch}/${ver}-RELEASE/base.txz"

    if [ -d "${DST}" ]; then
	[ $UPGRADE -eq 1 ] || err 1 "${MAGENTA}You already have ${ver}${NORMAL}"
	cbsd removebase ver=${ver} arch=${arch}
    fi

    if [ "$fbsdrepo" = "1" -a -z "${basename}" ]; then
	## Official fbsd repo
	printf "${MAGENTA}Looking for official FreeBSD mirror:${NORMAL}"
	ARCHIVE="$MYDIR/base.txz"
	cbsd cfetch -u ${BSDBASE_DISTSITE} -o ${ARCHIVE}
	if [ $? -eq 0 ]; then
	    printf "\n${MAGENTA}Extracting base...${NORMAL}\n"
	    mkdir $DST
	    cd $DST
	    tar xfz ${ARCHIVE}
	    rm -f ${ARCHIVE}
	    BSDBASE_DISTSITE="$MIRROR/pub/FreeBSD/releases/${arch}/${arch}/${ver}-RELEASE/lib32.txz"
	    ARCHIVE="$MYDIR/lib32.txz"
	    cbsd cfetch -u ${BSDBASE_DISTSITE} -o ${ARCHIVE}
		if [ $? -eq 0 ]; then
		    printf "\n${MAGENTA}Extracting lib32...${NORMAL}\n"
		    cd $DST
		    tar xfz ${ARCHIVE}
		    rm -f ${ARCHIVE}
		else
		    printf "${GREEN} Lib32 not found${NORMAL}\n"
		fi
	    cbsd preparebase dst=${DST}
	    ${ECHO} "${MAGENTA}Done...${NORMAL}"
	    return 0
	fi
    printf "${GREEN} Not found${NORMAL}\n"
    ### Official fbsd repo end ###
    fi

    for MYREPO in $REPO; do
	${ECHO} "${MAGENTA}REPO: ${GREEN}${MYREPO}${NORMAL}"
	if [ -z "${basename}" ]; then
	    MIRROR="${MYREPO}/base_${arch}_${ver}/mirror.html";
	else	
	    MIRROR="${MYREPO}/base_${basename}_${arch}_${ver}/mirror.html";
	fi

	cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1

	if [ $? -eq 0 ]; then
	    MYREPO=`cat ${TF}`
	    ${ECHO} "${MAGENTA}Found new mirror for ${ver}: ${GREEN}${MYREPO}${NORMAL}"
	fi

	if [ -z "${basename}" ]; then
	    cbsd cfetch -o ${MYDIR}/base_${arch}_${ver}.txz -u ${MYREPO}/${DIR}/base_${arch}_${ver}.txz
	    [ $? -eq 0 ] || continue
	    cbsd cfetch -o ${MYDIR}/base_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/base_${arch}_${ver}.txz.md5 >/dev/null 2>&1
	    [ $? -eq 0 ] || continue
	else
	    cbsd cfetch -o ${MYDIR}/base_${basename}_${arch}_${ver}.txz -u ${MYREPO}/${DIR}/base_${basename}_${arch}_${ver}.txz
	    [ $? -eq 0 ] || continue
	    cbsd cfetch -o ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/base_${basename}_${arch}_${ver}.txz.md5 >/dev/null 2>&1
	    [ $? -eq 0 ] || continue
	fi
    done

    if [ -z "${basename}" ]; then
	[ -f "${MYDIR}/base_${arch}_${ver}.txz.md5" -a -f "${MYDIR}/base_${arch}_${ver}.txz" ] || err 1 "No such sources"
    else
	[ -f "${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5" -a -f "${MYDIR}/base_${basename}_${arch}_${ver}.txz" ] || err 1 "No such sources"
    fi

    if checkmd5 ${MYDIR}; then
	${ECHO} "${MAGENTA}MD5 sum:${GREEN} correct${NORMAL}"
    else
	err 1 "${MAGENTA}MD5 sum: ${GREEN}incorrect${NORMAL}"
    fi

    if [ -z "${basename}" ]; then
	rm -f  ${MYDIR}/base_${arch}_${ver}.txz.md5
    else
	rm -f ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5
    fi

    ${ECHO} "${MAGENTA}Extracting...${NORMAL}"
    [ -d "$basejaildir" ] | mkdir -p ${basejaildir}
    #/base_${arch}_${ver}
    cd $basejaildir
    #/base_${arch}_${ver}

    if [ -z "${basename}" ]; then
	tar xfz ${MYDIR}/base_${arch}_${ver}.txz
	rm -f ${MYDIR}/base_${arch}_${ver}.txz.md5
    else
	tar xfz ${MYDIR}/base_${basename}_${arch}_${ver}.txz
	rm -f ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5
    fi

    ${ECHO} "${MAGENTA}Done...${NORMAL}"

return 0
}


getobj()
{
if [ -z "${basename}" ]; then
    DST="${srcdir}/obj_${arch}_${ver}"
else
    DST="${srcdir}/obj_${basename}_${arch}_${ver}"
fi

for MYREPO in ${REPO}; do
    ${ECHO} "REPO: ${MYREPO}"
    if [ -z "${basename}" ]; then
    	MIRROR="${MYREPO}/obj_${arch}_${ver}/mirror.html";
    else
        MIRROR="${MYREPO}/obj_${basename}_${arch}_${ver}/mirror.html";
    fi

    if [ -d "${DST}" ]; then
	[ $UPGRADE -eq 1 ] || err 1 "You already have ${ver}"
	cbsd removeobj ver=${ver} arch=${arch}
    fi
    cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1

    if [ $? -eq 0 ]; then
	MYREPO=`cat ${TF}`
	${ECHO} "Found new mirror for ${basename}: ${MYREPO}"
    fi

    if [ -z "${basename}" ]; then
	cbsd cfetch -o ${MYDIR}/obj_${arch}_${ver}.txz -u ${MYREPO}/${DIR}/obj_${arch}_${ver}.txz
	[ $? -eq 0 ] || continue
	cbsd cfetch -o ${MYDIR}/obj_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/obj_${arch}_${ver}.txz.md5 >/dev/null 2>&1
	[ $? -eq 0 ] || continue
    else
	cbsd cfetch -o ${MYDIR}/obj_${basename}_${arch}_${ver}.txz -u ${MYREPO}/${DIR}/obj_${basename}_${arch}_${ver}.txz
	[ $? -eq 0 ] || continue
	cbsd cfetch -o ${MYDIR}/obj_${basename}_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/obj_${basename}_${arch}_${ver}.md5 >/dev/null 2>&1
	[ $? -eq 0 ] || continue
    fi
done

if [ -z "${basename}" ]; then
    [ -f "${MYDIR}/obj_${arch}_${ver}.txz.md5" -a -f "${MYDIR}/obj_${arch}_${ver}.txz" ] || err 1 "No sources found"
else
    [ -f "${MYDIR}/obj_${basename}_${arch}_${ver}.txz.md5" -a -f "${MYDIR}/obj_${basename}_${arch}_${ver}.txz" ] || err 1 "No sources found"
fi

if checkmd5 ${MYDIR}; then
${ECHO} "MD5sum correct."
    else
err 1 "MD5sum incorrect."
exit
fi

rm -f ${MYDIR}/obj_${arch}_${ver}.txz.md5

${ECHO} "Extracting..."
cd $srcdir
tar xfz ${MYDIR}/obj_${arch}_${ver}.txz
rm -f ${MYDIR}/obj_${arch}_${ver}.txz
${ECHO} "Done..."
}


getkernel()
{
    [ -z "${name}" ] && name="GENERIC"
    DST="${basejaildir}/kernel_${name}_${arch}_${ver}"

    if [ -d "${DST}" ]; then
	[ $UPGRADE -eq 1 ] || err 1 "${MAGENTA}You already have kernel ${name} for ${ver}${NORMAL}"
	cbsd removekernel ver=${ver} arch=${arch} name=${name}
    fi

    for MYREPO in $REPO; do
	${ECHO} "${MAGENTA}REPO: ${GREEN}${MYREPO}${NORMAL}"
	MIRROR="${MYREPO}/kernel_${name}_${arch}_${ver}/mirror.html"
	cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1

	if [ $? -eq 0 ]; then
	    MYREPO=`cat ${TF}`
	    ${ECHO} "${MAGENTA}Found new mirror for ${ver}: ${GREEN}${MYREPO}${NORMAL}"
	fi

	cbsd cfetch -o ${MYDIR}/kernel_${name}_${arch}_${ver}.txz -u ${MYREPO}/${DIR}/kernel_${name}_${arch}_${ver}.txz
	[ $? -eq 0 ] || continue
	cbsd cfetch -o ${MYDIR}/kernel_${name}_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/kernel_${name}_${arch}_${ver}.txz.md5 >/dev/null 2>&1
	[ $? -eq 0 ] || continue
    done

    [ -f "${MYDIR}/kernel_${name}_${arch}_${ver}.txz" -a -f "${MYDIR}/kernel_${name}_${arch}_${ver}.txz.md5" ] || err 1 "${MAGENTA}No such sources${NORMAL}"

    if checkmd5 ${MYDIR}; then
	${ECHO} "${MAGENTA}MD5 sum: ${GREEN}correct${NORMAL}"
    else
	err 1 "${MAGENTA}MD5 sum: ${GREEN}incorrect${NORMAL}"
	exit 1
    fi

    rm -f ${MYDIR}/kernel_${name}_${arch}_${ver}.txz.md5

    ${ECHO} "${MAGENTA}Extracting...${NORMAL}"
    cd $basejaildir
    tar xfz ${MYDIR}/kernel_${name}_${arch}_${ver}.txz
    rm -f ${MYDIR}/kernel_${name}_${arch}_${ver}.txz
    ${ECHO} "${MAGENTA}Done...${NORMAL}"
}


getimg()
{
DST="${importdir}/${name}.img"

[ -f "${DST}" ] && {
    getyesno "You already have ${DST}. Remove them?"
    [ $? -eq 1 -o $? -eq 3 ] && err 0 "You already have ${DST}."
    rm -f ${DST}
}

JAILRCCONF="${jailrcconfdir}/rc.conf_${name}"
[ ! -f  ${JAILRCCONF} ] || err 1 "You already have installed jail ${name}"

for MYREPO in $REPO; do
    ${ECHO} "REPO: ${MYREPO}"
    MIRROR="${MYREPO}/img_${arch}_${ver}_${name}/mirror.html"
    cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1

    if [ $? -eq 0 ]; then
	MYREPO=`cat ${TF}`
	${ECHO} "${MAGENTA} Found new mirror for ${name} ${NORMAL}: ${MYREPO}"
    fi

    ${ECHO} "Fetching ${name} [${MYREPO}${DIR}]..."
    cbsd cfetch -o ${DST} -u ${MYREPO}${DIR}
    [ $? -eq 0 ] || continue
done

[ -f "${DST}" ] || err 1 "No such remote file or network problem"
${ECHO} "Done... Importing..."
cbsd jimport jname=${name}
cbsd jsetup-tui jname=${name} ip4_addr interface astart host_hostname
cbsd jconfig mode=list jname=${name}
}

#### MAIN ####
UPGRADE=0
QUIET=0
TF="${ftmpdir}/test.$$"
MYDIR="${workdir}/tmp/src.$$"
REPO=`cbsd getinfo -q repo`

[ -z "${action}" ] && err 1 "Give me action"

case "${mode}" in
    "upgrade") UPGRADE=1;;
    "quiet") QUIET=1;;
esac

case "${action}" in
"ping")
    if [ $QUIET -eq 1 ]; then
	checkrepo quiet
    else
	checkrepo
    fi
;;
"list")
for i in ${REPO}; do
    if fetchme "${i}/${sources}ls" >/dev/null 2>&1; then
	${ECHO} "Available sources for $i:"
	if [ "${ver}" = "any" ]; then
	    ver="[[:alnum:]]"
	else 
	    [ -z "${ver}" ] && ver=`/sbin/sysctl -n kern.osrelease|cut -d "-" -f1`
	fi
	if [ "${arch}" = "any" ]; then
	    arch="[[:alnum:]]"
	else
	    [ -z "${arch}" ] && arch=`/sbin/sysctl -n hw.machine_arch`
	fi
	    grep -E ${arch}_${ver} ${TF} |cut -d " " -f2-100
    #rm -f ${TF}
    fi
done
;;
"get")
. $buildconf
[ -z "${sources}" ] && err 1 "Give me sources"

case "${sources}" in
"src")
    DIR="src_${ver}"; 
    DST="${srcdir}/src_${ver}"
    LOCKFILE=${DST}.lock
    makelock ${LOCKFILE} "rm -f ${TF}; rm -rf ${MYDIR}" safe
    mkdir -p ${MYDIR}
    getsrc ;;
"base")
    if [ -z "${basename}" ]; then
	DIR="base_${arch}_${ver}"; 
    else
	DIR="base_${basename}_${arch}_${ver}"; 
    fi
    SRC="${srcdir}/src_${ver}"
    LOCKFILE=${SRC}.lock
    makelock $LOCKFILE "rm -f ${TF}; rm -rf ${MYDIR}" safe
    mkdir -p ${MYDIR}
    getbase ;;
"obj")
    if [ -z "${basename}" ]; then
	DIR="obj_${arch}_${ver}";
    else
	DIR="obj_${basename}_${arch}_${ver}";
    fi

    SRC="${srcdir}/src_${ver}"
    LOCKFILE=${SRC}.lock
    makelock $LOCKFILE "rm -f ${TF}; rm -rf ${MYDIR}" safe
    mkdir -p ${MYDIR}
    getobj ;;
"kernel")
    [ -z "${name}" ] && name="GENERIC"
    DIR="kernel_${name}_${arch}_${ver}"
    SRC="${srcdir}/src_${ver}"
    LOCKFILE=${SRC}.lock
    makelock $LOCKFILE "rm -f ${TF}; rm -rf ${MYDIR}" safe
    mkdir -p ${MYDIR}
    getkernel ;;
"img")
    [ -z "${name}" ] && err 1 "Give me name"
    DIR="img_${arch}_${ver}_${name}/${name}.img"
    LOCKFILE="${jaildir}/${name}.lock"
    makelock ${LOCKFILE} "rm -f ${TF}; rm -rf ${MYDIR}"
    mkdir -p ${MYDIR}
    getimg ;;
esac ## END of source case

esac ## END of action case
