#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG=""
MYDESC="Enable RSYNC service for jail migration"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${initenv}
. ${tools}
init $*

rsyncd_enable
service rsyncd start
