#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
MYARG="jroot fstab"
MYOPTARG=""
MYDESC="Unmount jail by fstab file"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

[ -f "${fstab}" ] || err 1 "No fstab"
[ -d "${jroot}" ] || err 1 "Wrong jroot $jroot"


SYSMNT=`/sbin/mount |grep " on " |awk {'printf $3" "'}`
tail -r ${fstab} | while read _device _mountpt _fs _mode _a _b; do
case ":${_device}" in
:#* | :)
continue
;;
esac
    /sbin/umount -f ${jroot}${_mountpt}
done
