# Copyright (c) 2026 The FreeBSD Foundation
#
# SPDX-License-Identifier: BSD-2-Clause
#
# This file was written by Alfonso Sabato Siciliano <asiciliano@FreeBSD.org>
# under sponsorship from the FreeBSD Foundation.

### bsddialog theme - Wed Apr  8 00:15:07 2026

## Settings
# Available colors: black, red, green, yellow, blue, magenta, cyan, white.
# Available attributes: bold, reverse, underline, blink, halfbright, highlight.
# Prefix f_* indicates the focused state of an element, whether selected or not.

version 1.2-wip

# Terminal
theme.screen.color red green

# Shadow
theme.shadow.color black black
# shift down right from main widget
theme.shadow.y 1
theme.shadow.x 2

# Main widget
theme.dialog.color black white
theme.dialog.delimtitle true
theme.dialog.titlecolor red white bold
theme.dialog.lineraisecolor black white
theme.dialog.linelowercolor black white
theme.dialog.bottomtitlecolor black white bold
theme.dialog.arrowcolor red white

# Menus: --checklist, --menu, --radiolist
# prefix [selector] shortcut name desc bottomdesc
theme.menu.f_prefixcolor black white
theme.menu.prefixcolor black white
theme.menu.f_selectorcolor white green
theme.menu.selectorcolor black white
theme.menu.f_namecolor white green
theme.menu.namecolor green white
theme.menu.f_desccolor white green
theme.menu.desccolor black white
theme.menu.f_shortcutcolor red green
theme.menu.shortcutcolor red white
theme.menu.bottomdesccolor white green
# bsddialog_menutype BSDDIALOG_SEPARATOR
theme.menu.sepnamecolor red white
theme.menu.sepdesccolor red white

# Forms
theme.form.f_fieldcolor white green bold
theme.form.fieldcolor white red bold
theme.form.readonlycolor red white bold
theme.form.bottomdesccolor white green

# Bar of --gauge, --mixedgauge, --pause, --rangebox
theme.bar.f_color white red bold
theme.bar.color red white bold

# Spinbox of --calendar, --datebox, --timebox
theme.spinbox.f_color white green bold
theme.spinbox.color black white

# Buttons
theme.button.minmargin 1
theme.button.maxmargin 5
theme.button.leftdelim [
theme.button.rightdelim ]
theme.button.f_delimcolor white green bold
theme.button.delimcolor black white
theme.button.f_color white green bold
theme.button.color black white
theme.button.f_shortcutcolor red green bold
theme.button.shortcutcolor red white bold
