#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
MYARG="jname status"
MYOPTARG="mode"
#mode=force
MYDESC="Jail switch mode between master/slave with rename"
ADDHELP="mode=force for force\n\
status= master or slave\n"

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${inventory}
. ${jfs}
init $*

FORCE=0
[ "${mode}" = "force" ] &&  FORCE=1
[ -n "${status}" ] || err 1 "Give me status"
[ -n "${jname}" ] || err 1 "Give me jname"

ST=`cbsd jstatus jname=${jname}`
[ $? -eq 0 ] && err 1 "No such jail"
[ $ST -gt 0 ] && err 1 "Jail is online. Please stop them for switching mode"

JAILDIR="${jaildatadir}/${jname}-${jaildatapref}"

JAILFSTAB="${jailfstabdir}/${jailfstabpref}${jname}"
SJAILFSTAB="${jailfstabdir}/${jailfstabpref}${jname}.slave"

JAILRCCONF="${jailrcconfdir}/rc.conf_${jname}"
SJAILRCCONF="${jailrcconfdir}/rc.conf_${jname}.slave"

JAILDATADIR="${jaildatadir}/${jname}-${jaildatapref}"
SJAILDATADIR="${jaildatadir}/${jname}-${jaildatapref}.slave"

case $status in
"master")
[ -f "${SJAILFSTAB}" ] || err 1 "No jail slave fstab for ${jname}"
[ -f "${SJAILRCCONF}" ] || err 1 "No jail slave rcconf for ${jname}"
[ -d "${SJAILDATADIR}" ] || err 1 "No jail slave datadir ${SJAILDATADIR} for ${jname}"
# force key here
if [ $FORCE -eq 1 ]; then
    [ ! -f "${JAILFSTAB}" ] || err 1 "Master fstab already exist for ${jname}"
    [ ! -f "${JAILRCCONF}" ] || err 1 "Master rcconf already exist for ${jname}"
    [ ! -d "${JAILDATADIR}" ] || err 1 "Master datadir already exist for ${jname}"
fi

mv ${SJAILFSTAB} ${JAILFSTAB}
mv ${SJAILRCCONF} ${JAILRCCONF}
unmountdata ${SJAILDATADIR}
migratedata ${SJAILDATADIR} ${JAILDATADIR} mv

;;
"slave")
[ -f "${JAILFSTAB}" ] || err 1 "No jail master fstab for ${jname}"
[ -f "${JAILRCCONF}" ] || err 1 "No jail master rcconf for ${jname}"
[ -d "${JAILDATADIR}" ] || err 1 "No jail master datadir for ${jname}"
# force key here
if [ $FORCE -eq 1 ]; then
    [ ! -f "${SJAILFSTAB}" ] || err 1 "Slave fstab already exist for ${jname}"
    [ ! -f "${SJAILRCCONF}" ] || err 1 "Slave rcconf already exist for ${jname}"
    [ ! -d "${SJAILDATADIR}" ] || err 1 "Slave datadir already exist for ${jname}"
fi

mv ${JAILFSTAB} ${SJAILFSTAB}
mv ${JAILRCCONF} ${SJAILRCCONF}
unmountdata ${JAILDATADIR}
migratedata ${JAILDATADIR} ${SJAILDATADIR} mv
;;
esac
