#!/bin/sh
#v9.1.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="ver arch maxjobs clean basename stable"
MYDESC="Buildworld from sources"
ADDHELP="ver=head for current.\n\
stable=1 for RELENG_X\n"

set -e

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

. ${buildconf}

SRC="${srcdir}/src_${ver}"
[ -d "${SRC}" ] || err 1 "No such version at ${SRCDIR}"
[ "${arch}" = "amd64" -o "${arch}" = "i386" ] || err 1 "Only amd64 or i386 arch supported"
if [ `uname -m` = "i386" -a "${arch}" = "amd64" ]; then
    err 1 "Cannot build amd64 on i386 hosts"
fi

if [ -z "${basename}" ]; then
    export __MAKE_CONF=${etcdir}/make.conf
else
    export __MAKE_CONF=${etcdir}/make-$basename.conf
fi

if [ -z "${basename}" ]; then
    export MAKEOBJDIRPREFIX=${srcdir}/obj_${arch}_${ver}
else
    export MAKEOBJDIRPREFIX=${srcdir}/obj_${basename}_${arch}_${ver}
fi

if [ -z "${basename}" ]; then
    export SRCCONF=${etcdir}/src.conf
else
    export SRCCONF=${etcdir}/src-${basename}.conf
fi

NUMJOBS=""
[ $maxjobs -eq 0 ] || NUMJOBS="-j${maxjobs}"

NOCLEANUP=""
[ ${clean} -eq 1 ] || NOCLEANUP="-DNO_CLEAN"

DST="${srcdir}/src_${ver}/src"
LOCKFILE=${ftmpdir}/src_${ver}.lock
makelock ${LOCKFILE}

/usr/bin/make $NUMJOBS -C ${SRC}/src buildworld TARGET=${arch} ${NOCLEANUP}
