#!/bin/sh
# v9.1.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="ver stable rev"
MYDESC="CSUP from official cvsup server"
ADDHELP="ver=head for current.\n\
stable=1 for RELENG_X\n\
rev=XXX wherei XXX - svn revision\n"

set -e

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

FREEBSD_SVN="svn://svn.freebsd.org"
[ -f "/usr/local/bin/svn" ] || err 1 "No svn in base. Please install subversion"

. ${buildconf}

DST="${srcdir}/src_${ver}/src"
LOCKFILE=${ftmpdir}/src_${ver}.lock
makelock ${LOCKFILE}
[ -d "${DST}" ] || /bin/mkdir -p ${DST}

if [ "$ver" = "10.0"  ]; then
    SVN_URL="${FREEBSD_SVN}/base/head"
else
    SVN_URL="${FREEBSD_SVN}/base/releng/${ver}"
fi

[ "${stable}" = "1" ] && SVN_URL="${FREEBSD_SVN}/base/stable/${ver}"

[ -d "${DST}/.svn" ] && /usr/local/bin/svn cleanup ${DST}
/usr/local/bin/svn checkout -r ${rev} ${SVN_URL} ${DST}

if [ -f "$DST/Makefile" ]; then
    # Make max username length greate then 17
    #usr/jails/src/src_9_1/src/sys/ 
    sed -i '' 's/MAXLOGNAME[[:space:]]*17/MAXLOGNAME 255/g' ${DST}/sys/sys/param.h
else
    rm -rf ${DST}
    err 1 "No source code for ${ver}"
fi
