#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="ver arch stable"
MYDESC="make delete-old and delete-old-libs for base"
ADDHELP="ver=9_1 for 9.1 ver=. for current.\n\
stable=1 for RELENG_X\n"

set -e

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

# By default ver=current version
[ -n "${ver}" ] || ver=`/sbin/sysctl -n kern.osrelease|cut -d "-" -f1 |tr "." "_"`
[ "${stable}" = "1" ] && ver=${ver%%_*}
[ -n "${arch}" ] || arch=`/sbin/sysctl -n hw.machine_arch`

SRC="${srcdir}/src_${ver}"
DST="${basejaildir}/${basejailpref}_${arch}_${ver}"

[ -d "${DST}" ] || err 1 "No such dir: $DST"
yes |make -C ${SRC}/src DESTDIR="${DST}" delete-old delete-old-libs
