#!/bin/sh
#v9.1.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="ver arch stable"
MYDESC="make delete-old and delete-old-libs for base"
ADDHELP="ver=9_1 for 9.1 ver=. for current.\n\
stable=1 for RELENG_X\n"

set -e

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

# By default ver=current version
. ${buildconf}

SRC="${srcdir}/src_${ver}"
DST="${basejaildir}/${basejailpref}_${arch}_${ver}"

[ -d "${DST}" ] || err 1 "No such dir: $DST"
yes |make -C ${SRC}/src DESTDIR="${DST}" delete-old delete-old-libs
