#!/bin/sh
#v9.1.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="ver arch maxjobs clean name stable"
MYDESC="Build kernel from sources"
ADDHELP="ver=9_1 for 9.1 ver=. for current.\n\
stable=1 for RELENG_X\n\
destdir= for alternative install path in root dir\n"

set -e

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

. ${buildconf}
[ -n "${clean}" ] || clean=0

SRC="${srcdir}/src_${ver}"
[ -d "${SRC}" ] || err 1 "No such version at ${SRCDIR}"
[ "${arch}" = "amd64" -o "${arch}" = "i386" ] || err 1 "Only amd64 or i386 arch supported"
if [ `uname -m` = "i386" -a "${arch}" = "amd64" ]; then
    err 1 "Cannot build amd64 on i386 hosts"
fi

if [ -z "${name}" ]; then
    export __MAKE_CONF=${etcdir}/make.conf
else
    export __MAKE_CONF=${etcdir}/make-$name.conf
fi

if [ -z "${name}" ]; then
    export MAKEOBJDIRPREFIX=${srcdir}/obj_${arch}_${ver}
else
    export MAKEOBJDIRPREFIX=${srcdir}/obj_${name}_${arch}_${ver}
fi

if [ -z "${name}" ]; then
    export SRCCONF=${etcdir}/src.conf
else
    export SRCCONF=${etcdir}/src-${name}.conf
fi

NUMJOBS=""
[ $maxjobs -eq 0 ] || NUMJOBS="-j${maxjobs}"

NOCLEANUP=""
[ ${clean} -eq 1 ] || NOCLEANUP="-DNO_CLEAN"

if [ -z "${name}" ]; then
    LOCKFILE=${SRC}.lock
else
    LOCKFILE=${SRC}-${name}.lock
fi

[ -z "${name}" ] && name="GENERIC"

if [ -n "${destdir}" ]; then
    DST="${destdir}"
else
    DST="${basejaildir}/kernel_${name}_${arch}_${ver}"
fi

[ -f "${etcdir}/kernel-${name}-${arch}-${ver}" ] || err 1 "No such config kernel-${name}-${arch}-${ver} in ${etcdir}"
cp ${etcdir}/kernel-${name}-${arch}-${ver} ${SRC}/src/sys/${arch}/conf/${name}
makelock $LOCKFILE "rm -f ${SRC}/src/sys/${arch}/conf/${name}"
/usr/bin/make $NUMJOBS -C ${SRC}/src installkernel TARGET=${arch} KERNCONF=${name} DESTDIR=${DST} ${NOCLEANUP}

