#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="ver arch name stable"
MYDESC="Remove base dir"
ADDHELP="ver=9_1 for 9.1 ver=. for current.\n\
stable=1 for RELENG_X\n"

set -e

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
. ${system}

init $*

# By default ver=current version
[ -n "${ver}" ] || ver=`/sbin/sysctl -n kern.osrelease|cut -d "-" -f1 |tr "." "_"`
[ "${stable}" = "1" ] && ver=${ver%%_*}
[ -n "${arch}" ] || arch=`/sbin/sysctl -n hw.machine_arch`

SRC="${srcdir}/src_${ver}"
DST="${basejaildir}/${basejailpref}_${arch}_${ver}"

if [ -z "${name}" ]; then
    DST="${basejaildir}/${basejailpref}_${arch}_${ver}"
else
    DST="${basejaildir}/${basejailpref}_${name}_${arch}_${ver}"
fi

[ -d "${DST}" ] || err 1 "No such dir: $DST"

if  on_mounted "${DST}"; then
    err 1 "Current dir in use. Unmount first"
fi

LOCKFILE=${SRC}.lock
makelock $LOCKFILE
chflags -R noschg ${DST} && rm -rf ${DST}
