#!/bin/sh
#v9.1.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="ver arch basename stable"
MYDESC="Remove obj-dir"
ADDHELP="ver=9_1 for 9.1 ver=. for current.\n\
stable=1 for RELENG_X\n"

set -e

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

# By default ver=current version
. ${buildconf}

SRC="${srcdir}/src_${ver}"
if [ -z "${basename}" ]; then
    OBJDIR="${srcdir}/obj_${arch}_${ver}"
else
    OBJDIR="${srcdir}/obj_${basename}_${arch}_${ver}"
fi

[ -d "${OBJDIR}" ] || err 1 "No such object dir: ${OBJDIR}"

LOCKFILE=${SRC}.lock
makelock $LOCKFILE
rm -rf ${OBJDIR}
