#!/bin/sh
#v9.0.0
globalconf="${workdir}/cbsd.conf";
MYARG=""
MYOPTARG="ver arch name stable"
MYDESC="Remove obj-dir"
ADDHELP="ver=9_1 for 9.1 ver=. for current.\n\
stable=1 for RELENG_X\n"

set -e

[ -f ${globalconf} ] || err 1 "no such conf file";
. ${globalconf}
. ${subr}
init $*

# By default ver=current version
[ -n "${ver}" ] || ver=`/sbin/sysctl -n kern.osrelease|cut -d "-" -f1 |tr "." "_"`
[ "${stable}" = "1" ] && ver=${ver%%_*}
[ -n "${arch}" ] || arch=`/sbin/sysctl -n hw.machine_arch`

SRC="${srcdir}/src_${ver}"
if [ -z "${name}" ]; then
    OBJDIR="${srcdir}/obj_${arch}_${ver}"
else
    OBJDIR="${srcdir}/obj_${name}_${arch}_${ver}"
fi

[ -d "${OBJDIR}" ] || err 1 "No such object dir: ${OBJDIR}"

LOCKFILE=${SRC}.lock
makelock $LOCKFILE
rm -rf ${OBJDIR}
