name: Build-CBSD-FreeBSD-jails-test
on:
  push:
    branches: [ master, develop ]

jobs:
  build-all-freebsd-x86-64:
    name: build-all-freebsd-x86-64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Startup VM
        uses: cross-platform-actions/action@v0.32.0
        env:
          ASSUME_ALWAYS_YES: yes
        with:
          operating_system: freebsd
          version: '15.0'
          architecture: x86-64
          memory: 4G
          cpu_count: 2
          shell: sh
          shutdown_vm: false
          environment_variables: ASSUME_ALWAYS_YES
          run: uname -a

      - name: Install CBSD run/build dependencies
        uses: cross-platform-actions/action@v0.32.0
        env:
          ASSUME_ALWAYS_YES: yes
        with:
          operating_system: freebsd
          version: '15.0'
          architecture: x86-64
          memory: 4G
          cpu_count: 2
          shell: sh
          shutdown_vm: false
          sync_files: false
          environment_variables: ASSUME_ALWAYS_YES
          run: |
            sudo pkg install -y ftp/curl textproc/jq devel/oniguruma security/libssh2 textproc/jq net/rsync devel/automake devel/autoconf devel/gmake security/sudo devel/pkgconf databases/sqlite3 devel/git
            pkg info

      - name: Build CBSD from source
        uses: cross-platform-actions/action@v0.32.0
        env:
          ASSUME_ALWAYS_YES: yes
        with:
          operating_system: freebsd
          version: '15.0'
          architecture: x86-64
          shell: sh
          cpu_count: 2
          memory: 4G
          shutdown_vm: false
          sync_files: false
          environment_variables: ASSUME_ALWAYS_YES
          run: |
            sudo git clone https://github.com/cbsd/cbsd.git /usr/local/cbsd
            sudo ln -s /usr/local/cbsd/rc.d/cbsdd /usr/local/etc/rc.d/cbsdd
            sudo pw useradd -n cbsd
            sudo /usr/local/cbsd/sudoexec/initenv /usr/local/cbsd/share/initenv.conf default_vs=1
            sudo cbsd version
            #sudo service cbsdd start

      - name: CBSD jails tests
        uses: cross-platform-actions/action@v0.32.0
        env:
          ASSUME_ALWAYS_YES: yes
        with:
          operating_system: freebsd
          version: '15.0'
          architecture: x86-64
          shell: sh
          cpu_count: 2
          memory: 4G
          shutdown_vm: false
          sync_files: false
          environment_variables: ASSUME_ALWAYS_YES
          run: |
            sudo env NOINTER=1 cbsd jcreate jname=test runasap=1 inter=0
            sudo cbsd jexec jname=test hostname


#      - name: CBSD jails tests
#        uses: cross-platform-actions/action@v0.32.0
#        env:
#          ASSUME_ALWAYS_YES: yes
#        with:
#          operating_system: freebsd
#          version: '15.0'
#          architecture: x86-64
#          shell: sh
#          cpu_count: 2
#          memory: 4G
#          shutdown_vm: false
#          sync_files: false
#          environment_variables: ASSUME_ALWAYS_YES
#          run: |
#            sudo env NOINTER=1 /usr/local/cbsd/tests/runall-jail

      - name: Shutdown VM
        uses: cross-platform-actions/action@v0.32.0
        env:
          ASSUME_ALWAYS_YES: yes
        with:
          operating_system: freebsd
          version: '15.0'
          architecture: x86-64
          shell: sh
          memory: 4G
          cpu_count: 2
          sync_files: false
          shutdown_vm: true
          environment_variables: ASSUME_ALWAYS_YES
          run: true

